bin/xunion, lib/utils/util.js, lib/xunion.js
This commit properly passes the command line arguments for `xunion` to
the `Config` constructor in a format that will override existing
configuration parameters.
=> using args for xu daemon

lib/Logger.js, package-lock.json, package.json
`createLogger` is supported in winston only from v3.0.0-rc0.
=> Upgrading winston logger to v3.0

lib/Xud.js, lib/lndclient/LndClient.js, lib/p2p/P2P.js, lib/p2p/P2PServer.js, lib/rpcserver/RpcMethods.js, lib/rpcserver/RpcServer.js, lib/utils/utils.js
Adds basic jsdoc code commenting for code related to the xud daemon
excluding database and orderbook classes.
=> Adding jsdoc comments

README.md, bin/xucli, bin/xud, lib/cli/.eslintrc.json, lib/cli/command.js, lib/cli/commands/connect.js, lib/cli/commands/getinfo.js, lib/cli/commands/getorders.js, lib/cli/commands/placeorder.js, lib/cli/commands/shutdown.js, lib/cli/commands/tokenswap.js, lib/utils/utils.js, package-lock.json, package.json
This commit replaces the command-line-args package with the more
powerful yargs package. Each command that can be called from xucli is
now its own module with a description of the parameters for that
command.
=> Using yargs with command modules

README.md, doc/jsdoc.md, lib/p2p/P2P.js, lib/rpc/RpcMethods.js, lib/utils/utils.js, package-lock.json, package.json
Updated a bit of the jsdoc in the code and generated a markdown file using the `jsdoc-to-markdown` package. Running `npm run doc` regenerates the markdown file.
=> Generated JSDoc

CONTRIBUTING.MD
This is simply a basic disclaimer and link to the full guide in our docs repo.
=> Add barebones CONTRIBUTING.MD

lib/BaseClient.ts, lib/lndclient/LndClient.ts, lib/raidenclient/RaidenClient.ts, lib/xuclient/XUClient.ts, test/integration/OrderBook.spec.ts
This commit enforces several variable type restrictions and creates a shared base client class for the lnd and raiden clients. I ran some basic tests and the class inheritance seems to work properly.
=> Refactoring raiden and lnd clients

lib/Config.ts, lib/db/DB.ts, lib/lndclient/LndClient.ts, lib/orderbook/OrderBook.ts, lib/orderbook/OrderBookRepository.ts, lib/raidenclient/RaidenClient.ts, lib/rpc/RpcMethods.ts, lib/rpc/RpcServer.ts, test/unit/MatchingEngine.spec.ts
These are some incremental changes towards refactoring to take advantage of TypeScript. I used types to define the object structure for our configuration and for some of the methods exposed by the RPC layer.
=> Adding types to config structure and rpc methods

lib/raidenclient/RaidenClient.ts
Using typed variables in our raiden client.
=> Create and use types for raiden client

lib/cli/command.ts, lib/cli/commands/connect.ts, lib/cli/commands/getinfo.ts, lib/cli/commands/getorders.ts, lib/cli/commands/getpairs.ts, lib/cli/commands/placeorder.ts, lib/cli/commands/shutdown.ts, lib/cli/commands/tokenswap.ts, package-lock.json, package.json
This is a mainly janitorial change to bring the `commands` used by yargs in line with the typescript style and convention used in the rest of the project.
=> Use typescript convention for cli commands

.travis.yml, lib/db/DB.ts, package.json, test/integration/OrderBook.spec.ts
Resolves #73 The main objective of this PR is TravisCI's `MySQL` connectivity for DB integration tests but not integration tests themselves(which are failing currently and needs to be fixed).
=> Db travis tests

test/unit/MatchingEngine.spec.ts
Added tests for the MatchingEngine as in #86 and I moved `MatchingEngine.getOrdersPriorityQueueComparator`out of the `MatchingEngine.getMatchingQuantity` test because they have nothing to do with each other.
=> Added tests for MatchingEngine

lib/BaseClient.ts, lib/Config.ts, lib/Logger.ts, lib/Xud.ts, lib/db/DB.ts, lib/lndclient/LndClient.ts, lib/nodekey/NodeKey.ts, lib/orderbook/MatchesProcessor.ts, lib/orderbook/MatchingEngine.ts, lib/orderbook/OrderBook.ts, lib/orderbook/OrderBookRepository.ts, lib/p2p/Peer.ts, lib/p2p/SocketAddress.ts, lib/p2p/packets/OrderPacket.ts, lib/raidenclient/RaidenClient.ts, lib/rpc/RpcMethods.ts, lib/rpc/RpcServer.ts, lib/xuclient/XUClient.ts, package.json, tasks/db/dropTables.ts, tasks/db/init.ts, tasks/db/truncate.ts, test/integration/OrderBook.spec.ts, tslint.json
This adds a new tslint rule to require accessibilty modifiers for all class members, and fixes all places in the code currently in violation of this rule. I erred on the side of making things `private` when I was unsure, if members need to be used in other classes in the future we can just change them to public.
=> Require member accessibility modifiers

lib/Config.ts, lib/Logger.ts, lib/orderbook/OrderBook.ts, lib/rpc/RpcServer.ts, lib/utils/utils.ts
Some minor refactoring/restructuring of the utils file to better use our typescript patterns.
=> Refactor utils with method exports

.travis.yml, docker/xud/Dockerfile
This PR reverts the changes from #117 and fixes the Docker build by installing `rsync`.
=> Fixed Docker build

bin/xud, lib/Config.ts, lib/Xud.ts, lib/grpc/GrpcServer.ts, lib/grpc/webproxy/GrpcWebProxyServer.ts
As in #113. And I renamed the config section `rpc` to `grpc`.
=> added gRPC host to config

lib/p2p/Parser.ts, lib/p2p/Peer.ts, lib/p2p/Pool.ts, lib/p2p/SocketAddress.ts, lib/p2p/packets/HelloPacket.ts, lib/p2p/packets/OrderPacket.ts, lib/p2p/packets/Packet.ts, lib/p2p/packets/PacketType.ts, lib/p2p/packets/PingPacket.ts, lib/p2p/packets/PongPacket.ts, lib/p2p/packets/index.ts, lib/p2p/packets/packetUtils.ts, lib/utils/utils.ts
Mostly adding  P2P request-response support. In addition:
* new packets: `Hello`, `Ping`, `Pong`
* sending `Ping` on intervals
* define response packet type and response timeout on each packet
* the ability to `wait` for a response, and easily consume it as a `Promise`
The mechanism might change after we'll add a packet header, and do the p2p protocol handshake.
The packets folder files and classes are not well structured, that will be taken care of later.
=> p2p request-response

README.md, lib/cli/commands/getorders.ts, lib/cli/commands/getpairs.ts, lib/grpc/webproxy/GrpcWebProxyServer.ts, lib/orderbook/OrderBookRepository.ts, lib/proto/xudrpc.swagger.json, lib/service/Service.ts, package-lock.json, package.json, proto/README.md, proto/xudrpc.proto
Closes #133. This PR updates some comments and adds a script to generate a swagger definition from our proto file.
=> Generate Swagger

lib/p2p/Pool.ts
=> p2p listen config

.travis.yml, package-lock.json, package.json, test/integration/WebProxy.spec.ts, tsconfig.json
=> Webproxy Sanity Integration Tests

lib/grpc/GrpcServer.ts, lib/grpc/errors.ts
=> Catch Bind port number to make sure grpc started successfully

lib/p2p/Parser.ts
This changes were probably lost while resolving conflicts with master
=> fix parser issue

lib/p2p/PeerList.ts, lib/p2p/Pool.ts, lib/p2p/errors.ts, lib/service/Service.ts
#122 Implements disconnect Peers via RPC
=> Disconnect Peers

lib/cli/commands/placeorder.ts, lib/orderbook/MatchingEngine.ts, lib/orderbook/OrderBook.ts, lib/proto/xudrpc.swagger.json, lib/proto/xudrpc_grpc_pb.js, lib/service/Service.ts, lib/types/orders.ts, proto/xudrpc.proto, test/integration/OrderBook.spec.ts
Closes #105 
I had to recreate #188 because I unintentionally deleted the branch and closed the PR. Sorry for the hassle.
=> Added market orders

lib/cli/commands/cancelorder.ts, lib/grpc/GrpcService.ts, lib/orderbook/MatchingEngine.ts, lib/orderbook/OrderBook.ts, lib/proto/annotations_pb.d.ts, lib/proto/google/api/http_pb.d.ts, lib/proto/google/protobuf/descriptor_pb.d.ts, lib/proto/lndrpc_pb.d.ts, lib/proto/xudrpc.swagger.json, lib/proto/xudrpc_pb.d.ts, lib/proto/xudrpc_pb.js, lib/service/Service.ts, package-lock.json, package.json, proto/xudrpc.proto, test/unit/MatchingEngine.spec.ts
Implements #121 own order cancellation.
=> Order Cancellation

.gitignore, package.json
This PR implements:
- Updates minimum node version to transpile and run on. (@kilrau had issues setting up due wrong node version).
- Adds myself to contributors list.
=> Bump required node version

docker/xud/Dockerfile
This PR adds gRPC & protogen swagger plugin deps to dockerfile.
=> Add grpc & protogen deps to Dockerfile

gulpfile.ts, lib/db/DB.ts, lib/p2p/Host.ts, lib/p2p/Peer.ts, lib/p2p/Pool.ts, tasks/db/init.ts
This pr implements:
- seeding from official bootstrap XU Nodes (#233) .
- xud1.test.exchangeunion.com
- xud2.test.exchangeunion.com
- xud3.test.exchangeunion.com
=> P2P Seeding

package-lock.json, package.json
Closes https://github.com/ExchangeUnion/xud/issues/260
=> Change version from 1.0.0-alpha.1 to 1.0.0-prealpha.1

lib/p2p/Pool.ts
=> Remove extraneous hostId missing logging

lib/p2p/Peer.ts, package-lock.json, package.json, tasks/db/init.ts
Solved #285 
If we want to keep the hosts values hardcoded in `DB` class, then this is the solution. It was failing because these values insertion was duplicated.
=> db:init task fix

lib/BaseClient.ts, lib/Xud.ts, lib/cli/commands/executeswap.ts, lib/db/models/Currency.ts, lib/grpc/GrpcService.ts, lib/orderbook/MatchesProcessor.ts, lib/orderbook/OrderBook.ts, lib/proto/xudrpc.swagger.json, lib/proto/xudrpc_pb.d.ts, lib/proto/xudrpc_pb.js, lib/raidenclient/README.md, lib/raidenclient/RaidenClient.ts, lib/service/Service.ts, lib/types/db.ts, proto/xudrpc.proto
*EDITED*
Progress towards #190. Progress towards #106.
This PR represents progress towards raiden swap functionality including automatically initiated swaps upon order matches, and removing orders and updating gRPC clients upon successful swap completion.
=> Preparation for Raiden swaps

lib/Xud.ts, lib/service/Service.ts
Since we're having releases and using versioning now - and since there will likely be breaking changes between pre-release versions - I thought it would be helpful to share the actual local version on handshake.
=> Set version on handshake

lib/proto/annotations_pb.d.ts, lib/proto/google/api/http_pb.d.ts, lib/proto/google/protobuf/descriptor_pb.d.ts, lib/proto/lndrpc_pb.d.ts, lib/proto/xudrpc_pb.d.ts, package-lock.json, package.json, proto/README.md
enhance protoc command to make sure it is using the correct plugin and correct syntax
remove unneeded protc package that causes conflics
=> protoc enhancements - macos/linux

test/integration/Pool.spec.ts
=> LND swap protocol

lib/Xud.ts, lib/grpc/GrpcService.ts, lib/lndclient/LndClient.ts, lib/p2p/Pool.ts, lib/service/Service.ts
Last step - integrating with LND using the swapResolver gRPC interface
=> LND swap resolver support

lib/p2p/NodeList.ts, lib/p2p/Peer.ts, lib/p2p/Pool.ts
=> Share only connected peers on GET_NODES

lib/p2p/Pool.ts
Fixes log message format as in #231
=> Peer disconnect log message format

bin/xud, lib/Config.ts, lib/Logger.ts, lib/Xud.ts, test/integration/Service.spec.ts, test/integration/WebProxy.spec.ts, test/p2p/sanity.spec.ts
This PR adds `logFile` to the config. If it is set to an empty string no logs will be written to a file. 
@moshababo I know that you said that I should keep `contextFileMap` but it adds just unnecessary complexity if we are not planning to use it imo. Tell me what you think.
=> Added logPath to config

lib/grpc/GrpcServer.ts, lib/grpc/GrpcService.ts, lib/proto/lndrpc_grpc_pb.d.ts, lib/proto/lndrpc_grpc_pb.js, lib/proto/lndrpc_pb.d.ts, lib/proto/lndrpc_pb.js, proto/lndrpc.proto
This PR implements the rpc.proto of the LND's resolver branch.
In this branch, rpc.proto includes also the hash-resolver service definition.
=> hash-resolver rpc in lnd.proto

lib/p2p/Peer.ts, lib/p2p/Pool.ts
This commit changes and adds log messages pertaining to connecting to
peers to make them clearer and more informative.
Closes #463.
=> feat(p2p): logging enhancements

CONTRIBUTING.MD
This PR links to our Developer Guide wiki page as well as external resources on best practices for creating and managing pull requests.
=> docs: update contributing.md with links

lib/Config.ts
This PR fixes a bug that resulted in incorrect values for fields like `dbPath` whose default value is derived from the `xudir` config property. The custom `xudir` value was not being applied to `dbPath` and other paths with default values that derive from `xudir`.
=> fix(config): correctly set default paths

docs/api.md, lib/grpc/GrpcService.ts, lib/p2p/Peer.ts, lib/proto/xudrpc.swagger.json, lib/proto/xudrpc_pb.d.ts, lib/proto/xudrpc_pb.js, proto/xudrpc.proto
=>  Refactor: add LND information to listpeers output

lib/orderbook/OrderBook.ts, lib/swaps/Swaps.ts
This PR changes the event emitted for failed swaps during matching from `peerOrder.filled` to `peerOrder.invalidated`. It also doesn't add back peer orders to the book if they could not be swapped, and it makes the `verifyExecution` method private. This is so that we don't confuse orders that are removed from the order book because they were successfully swapped with those that were removed without being swapped.
=> refactor: treat failed swaps as invalidations

lib/Xud.ts, lib/grpc/GrpcService.ts, lib/orderbook/OrderBook.ts, lib/service/Service.ts, lib/types/orders.ts
This PR sends handshake state updates to peers when trading pairs are added or removed, and also broadcasts order invalidations for any orders belonging to a trading pair that we are removing.
=> P2P integration for added/removed trading pairs

docs/api.md, lib/proto/xudrpc.swagger.json, lib/service/Service.ts, proto/xudrpc.proto
This changes the http path for `GetNodeInfo` to match the call name and adds an arg check to ensure a node pub key is specified. It also adds some comments to the proto file.
=> GetNodeInfo comments/minor changes

lib/orderbook/OrderBook.ts
Small fix for the new naming, introduced in #594.
=> fix: logging text

package-lock.json, package.json
The old version of typedoc was hitting an error that was resolved by updating to latest.
=> chore: update typedoc dependency

docs/api.md, lib/grpc/GrpcService.ts, lib/proto/xudrpc.swagger.json, lib/proto/xudrpc_pb.d.ts, lib/proto/xudrpc_pb.js, package-lock.json, proto/xudrpc.proto
=> Refactor(Order proto) added hold value

lib/swaps/Swaps.ts
=> Refactor(Swaps.ts) checks if r_hash exists before making swap

lib/p2p/NodeList.ts, lib/p2p/Parser.ts, lib/p2p/Peer.ts, lib/p2p/Pool.ts, lib/p2p/packets/PacketType.ts, lib/p2p/packets/types/DisconnectingPacket.ts, lib/p2p/packets/types/index.ts, lib/types/enums.ts
Implements #152.
I haven't implemented saving the packet to the database on the receiver side. I thought that having it in the logs will be sufficient. If you think otherwise, let me know.
=> feat: disconnecting packet

lib/p2p/Peer.ts
This properly cancels the timer to retry a connection to a peer when the peer is closed. Not canceling the timer could interfere with gracefully shutting down `xud`, as the process would continue waiting for the timer.
Edit: Evidently does not fix completely #699 - but still is a potential bug.
=> fix(p2p): cancel retry connection timer

lib/orderbook/OrderBook.ts
This commit adds logic that will:
1. Accept a swap request for a reduced amount when the full amount is not available due to part of the order being on hold.
2. Retry the portion that was not accepted when matching a newly placed order and having a swap request only partially accepted.
Closes #550.
I started trying to write a test case for this but it was too complex, this would be a good case to cover once the simulation tests are up and running.
=> feat(orderbook/swaps): accept partial swaps

lib/p2p/Pool.ts
This tracks inbound peer connections so that they can be closed when `xud` is gracefully shutdown. Previously, pending inbound peers could prevent `xud` from shutting down gracefully.
=> fix(p2p): terminate inbound peers on shutdown

lib/p2p/NodeList.ts, lib/p2p/Pool.ts, lib/service/Service.ts
=> refactor: fix ban functionality

test/integration/Pool.spec.ts
Add test for ban/unban.
Closes #764
=> feat: added test for ban/unban functionality

docs/api.md, lib/cli/commands/cancelorder.ts, lib/grpc/GrpcService.ts, lib/orderbook/OrderBook.ts, lib/orderbook/errors.ts, lib/proto/xudrpc.swagger.json, lib/proto/xudrpc_grpc_pb.js, lib/proto/xudrpc_pb.d.ts, lib/proto/xudrpc_pb.js, lib/service/Service.ts, proto/xudrpc.proto
This replaces #796. Closes #714.
=> Partial order removal

lib/lndclient/LndClient.ts
=> feat: listen to subscribeInvoices to verify lnd connection

lib/p2p/Peer.ts
This fixes a bug where xud could crash due to an unhandled error event when a socket connection attempt times out due to an unreachable peer. Previously we manually set a timeout upon attempting a connection which would call the `onError` function, which in turn called `cleanup` to remove all listeners. The socket is not destroyed in cases where we automatically retry connecting, but the `bind` function that sets new listeners isn't called until the delay between automatic retries is up. Since the socket would still be live, when the `ETIMEDOUT` internal error is raised there is no listener and it crashes the process.
This removes the manual connection timeout and instead relies on the internal `ETIMEDOUT` error. I have tested this and failed connection attempts still time out and get …
=> fix(p2p): fix connection timeout unhandled error

lib/proto/annotations_pb.js, lib/proto/google/api/http_pb.js, lib/proto/google/protobuf/descriptor_pb.js, lib/proto/hash_resolver_grpc_pb.js, lib/proto/hash_resolver_pb.js, lib/proto/lndrpc_grpc_pb.js, lib/proto/lndrpc_pb.js, lib/proto/xudrpc.swagger.json, lib/proto/xudrpc_grpc_pb.js, lib/proto/xudrpc_pb.js, package-lock.json, package.json
This downgrades grpc-tools to fix an issue with the lnd `QueryRoutes` call until https://github.com/grpc/grpc-node/issues/789 is resolved.
=> chore: downgrade grpc-tools to 1.6.0

test/simulation/actions.go
This attempts to fix a potential race condition that occasionally caused the simulation tests to fail. In `placeOrderAndBroadcast` we call `SubscribeAddedOrders` on node A, then immediately place an order on node B, which immediately broadcasts the order to node A. It's possible that the order subscription is not active on node A by the time it hears about the order since there's no latency between nodes.
This fix calls `ListPeers` after `SubscribeAddedOrders` to ensure that the two nodes are still connected and moves the `getOrdersCount` call to after `SubscribeAddedOrders`. This in turn creates a slight delay between subscribing for added orders and adding the order, resolving the race.
=> test: fix placeOrderAndBroadcast race condition

lib/grpc/GrpcService.ts, lib/orderbook/OrderBook.ts, lib/orderbook/TradingPair.ts, lib/p2p/Peer.ts, lib/p2p/Pool.ts, lib/p2p/packets/Packet.ts, lib/p2p/types.ts, lib/service/Service.ts, test/integration/OrderBook.spec.ts, test/integration/Service.spec.ts, test/unit/TradingPair.spec.ts
This commit adds and rewords comments in an attempt to have them more clearly explain the codebase. It also renames a few variables to make their naming more clear and specific.
=> docs: clarifying code and adding comments

.travis.yml, test/simulation/xudtest/node.go
This fixes an issue in the travis configuration that was causing builds to fail.
=> Travis install

lib/orderbook/OrderBook.ts, test/integration/OrderBook.spec.ts
This mocks the `Swaps` class in tests and makes it non-nullable to simplify code and eliminate unnecessary null checks.
=> refactor: mock swaps module for tests

lib/Xud.ts, lib/db/DB.ts, lib/lndclient/LndClient.ts, lib/lndclient/types.ts, lib/p2p/Pool.ts, lib/raidenclient/RaidenClient.ts, lib/swaps/SwapClient.ts, lib/swaps/SwapClientManager.ts, lib/swaps/Swaps.ts, test/integration/Pool.spec.ts, test/integration/Service.spec.ts, test/jest/Orderbook.spec.ts, test/jest/SwapClientManager.spec.ts, test/p2p/networks.spec.ts, test/p2p/sanity.spec.ts, test/simulation/xudtest/node.go, test/unit/DB.spec.ts
This splits out commits related to refactoring code and fixing/modifying tests in preparation for the master key changes in #1006. These commits can stand on their own and be merged separately to simplify the review process.
=> Master key refactor

lib/p2p/seeds/testnet.ts
=> feat: add testnet seed node

lib/p2p/seeds/simnet.ts
Closes https://github.com/ExchangeUnion/xud-simnet/issues/36
=> refactor: change xud simnet uris to follow naming convention

lib/lndclient/LndClient.ts, lib/raidenclient/RaidenClient.ts, lib/swaps/SwapClient.ts
=> style: use "units" for smallest currency unit vars

lib/lndclient/LndClient.ts
This refactors the `verifyConnection` logic to use the grpc `waitForReady` function to wait for the client to be ready before attempting a `GetInfo` call to lnd. This cuts down on the number of calls we need to make to an offline lnd instance to determine when it has come back online.
=> refactor(lnd): wait for grpc when verifying conn

lib/grpc/GrpcService.ts, lib/orderbook/OrderBook.ts
=> feat: if order placed and raiden disabled throw error

lib/constants/limits.ts, lib/grpc/GrpcService.ts, lib/orderbook/OrderBook.ts, lib/orderbook/errors.ts, lib/p2p/Pool.ts, test/integration/OrderBook.spec.ts, test/jest/Orderbook.spec.ts
=> Limit trade & order sizes for mainnet

lib/cli/commands/channelbalance.ts, lib/cli/commands/executeswap.ts, lib/cli/commands/getinfo.ts, lib/cli/commands/getnodeinfo.ts
#558 
Adds cli enhancements for:
- `getinfo`
- `getnodeinfo`
- `removeorder`
- `channelbalance`
=> feat: cli enhancements

lib/swaps/Swaps.ts, test.js
=> feat(swaps): logging improvements

docs/api.md, lib/cli/commands/addcurrency.ts, lib/cli/commands/listcurrencies.ts, lib/grpc/GrpcService.ts, lib/orderbook/OrderBook.ts, lib/proto/xudrpc.swagger.json, lib/proto/xudrpc_grpc_pb.d.ts, lib/proto/xudrpc_grpc_pb.js, lib/proto/xudrpc_pb.d.ts, lib/proto/xudrpc_pb.js, lib/service/Service.ts, proto/xudrpc.proto
This should resolve #1067, I'm not really sure about global identifiers tho. So a review from your side would be great.
=> List currencies enhancements

lib/swaps/Swaps.ts
=> fix(swaps): calc lock duration hours correctly

lib/grpc/GrpcService.ts, lib/service/Service.ts
=> refactor: remove localId from ExecuteSwap response

lib/db/seeds/simnet.ts, lib/db/seeds/testnet.ts
Related to https://github.com/ExchangeUnion/xud-docker/pull/167
=> feat: seed ports adjustment

test/simulation/README.md
=> docs: update simulation test cases

npm-shrinkwrap.json
=> chore: run `npm dedupe` with 6.11.3

lib/cli/commands/listpeers.ts, lib/cli/utils.ts
#558 
Formats cli response for `listpeers`.
=> feat(cli): enhance listpeers output

lib/cli/commands/create.ts
Closes #1263
The new output will look like this: 
```
The following wallets were initialized: LTC, BTC, ERC20(ETH)
```
=> fix: simplify wallet creation output

test/jest/Pool.spec.ts
This makes some minor cleanup and fixes to the Pool jest test suite. It also splits the `it connects exactly once if two peers attempt connections to each other simultaneously` case into two, one where the first connection is completed before the second connection is attempted, and another where the connections begin simultaneously. The latter results in a race condition that occasionally causes the test case to fail, which will be fixed in a separate commit.
=> test: pool suite cleanup

lib/swaps/Swaps.ts
Closing https://github.com/ExchangeUnion/xud/issues/1264.
I'm not sure if this is the desired behaviour - please review.
=> feat(swaps): Resolve unknown hashes from database

lib/lndclient/LndClient.ts, lib/swaps/SwapClient.ts, test/integration/Service.spec.ts
Alternative approach to solving same issue as #1360, still testing/WIP.
=> feat(lnd): retry init if misconfigured (WIP)

lib/lndclient/LndClient.ts
This makes lnd go into `WaitingUnlock` status any time a call - besides WalletUnlocker calls - fails due to the `UNIMPLEMENTED` error which generally indicates that lnd is locked. This covers edge cases where lnd is restarted while xud is running.
Previously only the channel balance update call and the GetInfo call within `verifyConnection` would handle an `UNIMPLEMENTED` error properly.
=> refactor(lnd): lock on any unimplemented error

lib/lndclient/LndClient.ts
Fixes #1367.
This fix prevents an undefined error by better handling the case where the lnd client attempts a call when it is not in a valid status to make that call. Instead it throws the appropriate `UNAVAILABLE` error with a helpful message.
=> fix(lnd): prevent undefined error

bin/xud, lib/Config.ts, lib/grpc/getGrpcError.ts, lib/p2p/Pool.ts, lib/p2p/errors.ts, lib/p2p/types.ts, test/integration/Pool.spec.ts
EDIT by @kilrau: Closes https://github.com/ExchangeUnion/xud/issues/1154
=> feat(p2p): add p2p tor config option

lib/lndclient/LndClient.ts
This fixes the logic around automatically unlocking lnd if it is restarted and comes back online in a locked state while xud is running. Previously, it would be possible for lnd to go down, come back online, get unlocked, then quickly go down again leaving it in a `WAITING_UNLOCK` status. If lnd comes back online while still in this status, it would not be automatically unlocked. This fix ensures that lnd would be unlocked even in this case. Although it is somewhat of an edge case, it can manifest when lnd is unable to communicate with its backing node as its behavior is to immediately shut down after unlock when that is the case.
=> fix(lnd): auto unlock consistently

CHANGELOG.md, npm-shrinkwrap.json, package.json
I had to make some manual adjustments to the changelog as it was including changes from previous releases. I'll investigate why that was happening separately.
I needed to update the typedoc dependency for the script to work correctly, as well.
=> chore(release): 1.0.0-beta.1

test/simulation/docker-lnd/Dockerfile
Closing https://github.com/ExchangeUnion/xud/issues/1423.
=> test(sim): upgrade lnd to v0.9.2-beta

lib/service/InitService.ts
This corrects unintentional behavior that prevented xud from unlocking when any enabled instance of lnd is disconnected or unavailable when we go to unlock it. This behavior is desired for the `create` and `restore` calls - we want to ensure that we fully initialize and restore all wallets. However, for unlock calls we can start up even if one lnd instance is temporarily unavailable. When it comes back online it will be automatically unlocked and activated to be prepared for swaps.
=> fix: allow unlock with disconnected lnd

lib/lndclient/LndClient.ts
This improves the logic behind waiting for an lnd grpc client to be ready so that it is more robust. Occasionally the callback is never triggered in cases where lnd is abruptly shut down and restarted immediately, meaning we never attempt to reconnect to lnd because we are never notified that the client is ready. To prevent this and any other flakiness we set a max time to wait for the client to be ready and attempt a grpc call regardless after this time. The time uses an exponential backoff to prevent repeated calls to an offline server.
I've tested this pretty extensively within docker and it's working well through multiple stops, starts, and restarts of lnd, whether or not bitcoind/litecoind is ready to receive rpc calls. Lnd is always recognized and unlocked once it is ready. Note …
=> fix(lnd): exponential backoff for grpc client wait

lib/swaps/SwapClient.ts
This is an experimental change to see if it can resolve #1457. If it turns out to work I'll update this PR & commit with more details.
=> fix: prevent hang on first updateCapacity call

lib/cli/placeorder.ts
Re: https://github.com/ExchangeUnion/xud/issues/1499#issuecomment-618324594
=> feat(cli): print placeorder swapfailure reason

lib/p2p/Pool.ts
=> feat(p2p): log reason enum for SwapFailed packet

lib/cli/commands/addcurrency.ts
=> fix(cli): cleaner message if decimal_places NaN

lib/cli/placeorder.ts, lib/grpc/GrpcServer.ts
This is an initial step towards resolving #1514.
Once this is in I'll work towards printing peer order matches (but not swaps) for streaming placeorder calls.
=> feat(cli): use streaming PlaceOrder by default

package.json, test/simulation/README.md
I ran into some issues when updating the custom-xud patch for #1549 and wound up tweaking the scripts and README for modifying the patch.
=> Custom xud patch improvements

lib/swaps/Swaps.ts, test/simulation/tests-security.go
This removes all code from the `Swaps` module that would cancel an invoice as maker when encountering a `sendPayment` failure. Instead, we put swaps that fail when sending a payment from maker to taker into `SwapRecovery`, where incoming invoices are only canceled after confirming that payment has failed permanently via a `lookupPayment` call. This is to ensure that the maker never gives up the ability to claim an incoming payment while the corresponding outgoing payment can still be claimed by the taker.
This is a followup to #1580.
=> feat(swaps): use SwapRecovery for maker pay errors

CHANGELOG.md, npm-shrinkwrap.json, package.json, sample-xud.conf
This is an updated version of #1589, squashed to a single commit with the latest fix from #1592.
=> chore(release): 1.0.0-beta.3

lib/db/seeds/mainnet.ts, lib/db/seeds/simnet.ts, lib/db/seeds/testnet.ts
TODO:
- add mainnet bootstrap node once new xud-docker release is tagged (@reliveyy )
- anybody else with a stable 24/7 box: shoot over your data and I can add them here
=> feat: add additional seed nodes

lib/swaps/Swaps.ts
This ensures that we don't attempt to advance an accepted swap that we have already failed, as can be the case when we fail a deal that timed out during the acceptance stage. If the maker accepts our swap after we already timed out and failed the deal, this situation can arise.
This can cause xud to crash due to an AssertionError from attempting to change the phase of a swap that has already failed.
Fixes #1614.
=> fix(swaps): don't try to accept a failed deal

lib/connextclient/ConnextClient.ts
This handles the http request xud receives from connext when an outgoing hash lock transfer is created by logging an appropriate message. Previously this would be logged as a `warn` due to an unknown incoming transfer.
=> feat(connext): log created outgoing hashlock xfers

lib/swaps/Swaps.ts
This changes the order of events when a swap enters the `PaymentReceived` phase and is considered complete. Currently, we mark the swap as complete right away but we don't cancel the swap timer until after we've updated the database to persist the swap. When the database write is delayed at all, it presents the edge case risk where the swap timer hits its limit while are writing to the database and after we've already marked the swap as complete. This results in an assertion error as we try to fail a swap due to a timeout when that swap is already complete.
Instead, we cancel the swap timer immediately after marking the swap complete and only then persist the update to the database.
Fixes #1634.
=> fix(swaps): cancel timer immediately on complete

lib/swaps/Swaps.ts
This moves the check to ensure that we are connected to the swap clients for both sides of a swap before accepting a deal request to before we create the swap deal object and begin the swap timer. It also makes some minor refactoring of the surrounding code and variables to make it more concise and readable.
=> refactor(swaps): check inactive currencies sooner

lib/connextclient/ConnextClient.ts
This uses the channel balance for a Connext currency as its max outgoing trading limit.
Closes #1609.
=> feat(connext): use channel balance as max outgoing

lib/grpc/GrpcService.ts, lib/service/Service.ts
This removes internal listeners that are created to handle streaming rpc calls. When the rpc call is canceled, we remove all listeners related to that call.
Fixes #1640.
=> fix(rpc): close listeners for streaming calls

README.md
=> feat: travis ci badge -> github action badges

lib/utils/aliasUtils.ts, test/jest/aliasUtils.spec.ts
=> bigger set, same aliases

lib/p2p/NodeList.ts
This sets an upper bound for the reputation score that a node can achieve. This is to prevent a node that has built up a reputation over time to get away with malicious or dishonest activity for very long before being banned.
Closes #1422.
=> feat(p2p): max reputation score

lib/orderbook/OrderBook.ts
This temporarily removes peer orders from the order book when they fail swaps during the matching routine for a locally placed order. Placed orders that fail any swaps will retry matching for the quantity that failed, and previously this meant they may match again with the same order resulting in a swap that will likely fail yet again.
This ensures that the two orders won't be matched again and that any other orders in the order book with a matching price would be tried instead. Once matching is complete, the order is added back to the
order book so it may be swapped again in the future by which time the  reason for the swap failure may be resolved.
This replaces the `debug.testing` behavior for order matching.
Closes #1595.
=> feat(orderbook): don't match same orders twice

lib/connextclient/ConnextClient.ts, lib/service/Service.ts
This improves the parallelization and error handling of the `GetBalance` call particularly as it pertains to Connext. Behind the scenes, Connext has a single call that returns both on chain and off chain balance, unlike lnd where the two calls are separate. xud was calling this twice, which puts unnecessary load on Connext.
Instead, Connext now tracks when there is already an ongoing balance request that it is waiting for a response for. Any `getBalance` calls that happen while there is this wait will listen for the same response rather than making separate calls.
Also, the error handling is changed for the `GetBalance` call such that if we get errors for only some of the currencies for which we are checking balances, we still return the balances for currencies which did not give us any …
=> fix(connext): async getbalance & error handling

npm-shrinkwrap.json, package.json
This updates the grpc dependency for compatibility with node v14.
Fixes #1727.
=>  chore: upgrade grpc dependency 

lib/lndclient/LndClient.ts
This improves the initialization flow for LndClient when creating a new wallet in lnd. Sometimes `admin.macaroon` is not created immediately after calling `InitWallet` on lnd. Previously, this could lead to us being stuck in a loop on `awaitWalletInit` immediately after creating or restoring a wallet in lnd. If there are no macaroons by the first time we attempt to verify the connection, we treated it as if lnd had never received an `InitWallet` command and wait for that command to happen, however that call never comes since it had already happened.
Instead, this adds new logic to detect the above scenario and skip ahead to simply wait for `admin.macaroon` to be written to disk and made available for lnd calls by xud.
=> feat(lnd): handle delayed macaroon creation

test/simulation/docker-build.sh, test/simulation/docker-connext/Dockerfile
Upgrade connext indra to 7.0.0 stable and connext client to latest commit. Only relevant for simtests.
=> chore: upgrade connext to 7.0.0

lib/cli/placeorder.ts
This ensures that a "no more matches" message is printed by the cli when a market order is only partially matched due to no more orders in the order book. It does this by tracking the remaining quantity. Previously, a message would only get printed if the matching ended on a failed swap, but didn't cover the case where there were simply no more orders available in the order book.
Closes #1596.
=> feat(cli): print no more matches on partial mkt

lib/cli/commands/walletwithdraw.ts, lib/connextclient/ConnextClient.ts, lib/connextclient/types.ts, lib/grpc/GrpcService.ts, lib/lndclient/LndClient.ts, lib/swaps/SwapClient.ts, lib/swaps/SwapClientManager.ts
*Untested*
This PR implements withdrawals from the Connext onchain wallet
=> feat: implement Connext wallet withdrawals

lib/p2p/Pool.ts
=> fix: order invalidation only be sent to peers with active pair (#1530)

lib/cli/commands/addpair.ts, lib/cli/commands/walletwithdraw.ts
resolves #1844
Replaces #1846.
=> fix: grpc throws error for addpair/withdraw for wrong argument (#1844)

lib/db/DB.ts
=> fix: propagating nodes on database if initDB true even DB is filled

lib/db/seeds/mainnet.ts, lib/db/seeds/simnet.ts
- disable BTC/DAI to not dilute liquidity and list BTC/USDT first
- disable LTC/USDT
- sort by name, prepare future pairs
Final pairs should be the interesting ones and demonstrate swap capability in all directions.
- BTC/USDT
- ETH/BTC
- LTC/BTC
- USDT/DAI
=> refactor: clean up default currencies & pairs

lib/cli/commands/unlock.ts
=> fix(cli): typo in unlock.ts

lib/grpc/getGrpcError.ts, lib/orderbook/OrderBook.ts, lib/orderbook/errors.ts
=> fix: addpair should prevent adding same base and quote assets (#1559)

lib/cli/commands/getinfo.ts
=> fix: getinfo output for lnd channels (#1940)

lib/swaps/Swaps.ts, test/jest/integration/Swaps.spec.ts
=> fix: added swap success log entry (#1649)

lib/p2p/Pool.ts
=> fix: manual ban causes an undefined log entry (#1779)

lib/cli/commands/openchannel.ts
=> fix(cli): openchannel assertion error for string amount

lib/orderbook/OrderBook.ts
This fixes a bug in the logic to calculate whether a request to place a new order exceeds the available capacity and trading limits by properly accounting for the quantity that is being replaced by the new order request. Previously, this was not accounted for and attempting to replace an order, even if not changing quantity, could result in an error due to exceeding the trading capacity.
Closes #1999.
I'm still working on some tests to cover this case but figured I'd open the PR for testing/review so we can get this merged soon.
=> fix: limits account for replaced order quantity

test/simulation/README.md
Closes https://github.com/ExchangeUnion/xud/issues/1995
=> feat: enhance simulation test README

lib/swaps/SwapClientManager.ts
=> fix: wrong error message on insufficient inbound capacity (#2003)

lib/connextclient/ConnextClient.ts, lib/swaps/consts.ts, test/jest/Connext.spec.ts, test/jest/HttpServer.spec.ts, test/jest/HttpService.spec.ts, test/jest/SwapClientManager.spec.ts, test/jest/__snapshots__/Connext.spec.ts.snap, test/simulation/actions.go, test/simulation/docker-build.sh, test/simulation/docker-compose.yml, test/simulation/docker-run.sh, test/simulation/tests-instability.go, test/simulation/tests-integration.go, test/simulation/xud_test.go, test/simulation/xudtest/harness.go, test/simulation/xudtest/node.go
Adding this a separate PR into `feat/connext-vector` branch so that it's easier to review the history when enabling the connext v2 tests.
=> test: connext vector remove simtests

lib/service/InitService.ts, lib/swaps/SwapClientManager.ts
attempts to fix #1815 
But as a followup I don't know if this affects next startups when L2 is setup properly @sangaman
=> feat: ignore unavailable swap clients on create (#1815)

lib/connextclient/ConnextClient.ts
This PR adds connext testnet router public key to xud codebase. Additional changes are required from xud-docker side for the testnet setup to start correctly. Will create xud-docker PR after this PR is merged.
=> feat(connext): add connext testnet router pubkey
