ExchangeUnion/xud

- .travis.yml
- package.json
This is a basic travis config to run linting and our tests (once they exist). It's configured to test node v7, which is the lowest version to support await/async, as well as the latest stable version.
> Enable Travis

- lib/Logger.js
This change allows error objects to be logged with full stack trace. The `error()` function now accepts either a custom message and an error or just an error as parameters.
> Logging error objects

- lib/Config.js
- lib/XUnion.js
to enable command line args to override config:
* pass args object to config constructor
* override config with args regardless of xunion.conf file
> Config args

- .eslintrc.json
- lib/Config.js
- lib/Xud.js
- lib/constants/errors.js
- lib/rpcserver/RpcMethods.js
Basic swapProtocols config
* I disabled the `no-else-return` eslint rule because I think it enforces a bad practice
* lndClient obviously need more connectivity checks - later on
* feel free to fix this PR as you wish and merge it yourself (i'll be away for a few days).
> swap protocols config

- bin/xucli
- lib/Xud.js
- lib/p2p/P2P.js
- lib/p2p/P2PServer.js
- lib/rpcserver/RpcMethods.js
- lib/rpcserver/RpcServer.js
- lib/xuclient/XUClient.js
The graceful shutdown call disconnects from all peers and stops all servers.
Later, this method can be used to ensure we don't close xud while in the
middle of trades or any other important activity.
> adding graceful shutdown rpc call

- lib/db/DB.js
- lib/db/baseRepository.js
- lib/db/models/Currency.js
- lib/db/models/Order.js
- lib/db/models/Pair.js
- lib/db/models/Peer.js
- lib/orderbook/OrderBook.js
- lib/orderbook/OrderBookRepository.js
- lib/p2p/P2PRepository.js
- tasks/db/data/populate.js
Don't mind the previous commits. I accidentally used an existing remote branch name.
* Seperated DB models to multiple files
* in the end I did used `tableName` for sequelize models, because of how `sequelize.import` works.
* Adding the repository layer. Currently it makes the service layer merely a proxy, but soon it will change. 
* adding `baseRepository` for generic db interfaces. I didn't use class inheritance because it wasn't appropriate since a repository can span multiple models.
> DB repository layer

- lib/p2p/P2P.js
- lib/rpcserver/RpcMethods.js
This is a set of changes to improve peer to peer functionality.
Connecting to a peer first attempts to resolve the hostname. If a
connection attempt is made to an ip address and port that is already
connected, the connection attempt is aborted. Bad data received from a
peer no longer crashes the daemon, instead a warning is logged.
> improving p2p robustness

- bin/xucli
- lib/Config.js
- lib/Xud.js
- lib/raidenclient/RaidenClient.js
- lib/rpcserver/RpcMethods.js
- lib/rpcserver/RpcServer.js
- lib/xuclient/XUClient.js
This adds basic integration with the Raiden REST API and specifically the `token_swaps` endpoint which is used to swap one token for another. I've tested this manually and verified that the calls work and get back the successful response from Raiden, but the channels aren't being updated as expected. This is something we can revisit when Raiden is in a more stable state, but for now I thought we could merge the framework for interacting with it.
The command line `tokenswap` call is probably only temporary for demo/testing purposes, as in the future this will be called as part of an order being matched and not manually.
> Raiden Integration

- lib/Config.js
- lib/Xud.js
- lib/lndclient/LndClient.js
This fixes the default path for the rpc.proto file included in the
source on windows, and also restructures the config parameters related
to lnd.
> Standardizing default rpcProtoPath

- lib/Config.js
- lib/utils/utils.js
`utils.copyObject` had some issues with null & string properties.
Trying to fix it made the code too clumsy, so I used a different implementation instead.
I change its name to `deepMerge` because that's the standard name for this kind of util.
> utils - deepMerge

- lib/lndclient/LndClient.js
This improves the error handling around issues #20 and #27 when lnd is not installed.
> check if lnd tls.cert file exists

- README.md
- bin/xucli
- bin/xud
- lib/Config.js
- lib/Xud.js
- lib/cli/command.js
- lib/cli/commands/connect.js
- lib/cli/commands/placeorder.js
* Fixing an existing issue with `rpcPort` (the name wasn't consistent, sometime it was `rpcport`), I ended up making it nested, as `rpc.port` (better approach since `rpc` will have more config, and this is our pattern anyway).
* Adding relevant description for the `./bin/xud` symlink (he's necessary if you want to create few `xud` instances). 
* Made it more clear that in the `connect` cli command, the args (host, port) are referring to the p2p server.
> config and cli

- lib/Config.ts
- lib/constants/enums.ts
- lib/constants/errorCodesPrefix.ts
- lib/db/baseRepository.ts
- lib/db/models/Order.ts
- lib/db/models/Pair.ts
- lib/lndclient/LndClient.ts
- lib/lndclient/errors.ts
- lib/orderbook/MatchingEngine.ts
- lib/p2p/Peer.ts
- lib/raidenclient/RaidenClient.ts
- lib/raidenclient/errors.ts
- lib/utils/utils.ts
- tslint.json
This adds tslint rules to match the airbnb javascript style guide (`no-consecutive-blank-lines` & `no-trailing-whitespace`) and typescript documentation convention (`typedef-whitespace`). I'm going to open a PR to add the first two rules directly to the style guide we are using, because they really should be included there I figure.
> Add tslint rules

- README.md
- bin/xucli
- lib/cli/command.ts
- lib/xuclient/XUClient.ts
This adds the option to specify a host besides `localhost` for `xucli` commands.
> Add host arg to cli

- README.md
- bin/xucli
- bin/xud
- lib/Config.ts
This updates the `xud` command line arguments along with the readme. I renamed `xuDir` to `xudir` to be consistent with the lower case config/arg names.
> Updating xud command arguments

- lib/Xud.ts
- lib/nodekey/NodeKey.ts
- package-lock.json
- package.json
This allows for creation of an ECDSA key pair (node key) for establishing node identity and signing messages. A node key is generated randomly and automatically if none exists. Generated node keys are saved to disk in the xu data folder and read on future starts. Methods to encrypt and decrypt stored keys on disk are included but currently are not used.
I didn't replace the placeholder node key in P2P.ts because the file is being replaced in a separate PR, but eventually we'll want to use this there.
This addresses #39.
> generate nodekey and persist to disk

- package-lock.json
- package.json
This commit uses the `cross-os` package to enable separate npm scripts based on OS platform. Currently the only script affected is `compile`.
> Add cross-platform scripts

- package.json
This addresses the mysterious recent issue of `npm run lint` not working on linux/mac. I've tested the new script on both windows and linux and it works as expected. @moshababo could you just sanity test this on mac?
> Fix lint script issues on linux

- lib/db/DB.ts
- package.json
- tasks/db/dropTables.ts
- tasks/db/init.ts
- tasks/db/restart.ts
This pr fixes 
- the integration test failing if the database does not exist before running
- the error `Specified key was too long; max key length is 767 bytes` by enforcing the database charset `utf8`
and adds the TypeScript files in the tasks folder to `npm run lint`.
Edit: this fixes also the issues with Travis and the integration tests in #75
> Database fixes

- README.md
- bin/xud
- lib/Config.ts
- lib/lndclient/LndClient.ts
This solves the bug from #80, allowing `xud` to be run from any working directory without interfering with the default path to `lndrpc.proto`. I don't think there's any need to keep this configurable, as even multiple instances of `xud` should be using the same version of `lnd`.
> Use __dirname to load lndrpc.proto

- docker/xud/Dockerfile
Following Docker [best practices](https://docs.docker.com/v17.09/engine/userguide/eng-image/dockerfile_best-practices/#workdir) and using `WORKDIR` instead of `cd`.
> Use WORKDIR instead of cd for xud Dockerfile

- package-lock.json
- package.json
- test/unit/MatchingEngine.spec.ts
It looks like #89 and #88 crossed wires and, thanks partly to Travis-CI not being able to build NodeJS 10.2.1, we missed a resulting compilation error. I've fixed that here plus made a few minor legibility changes.
On a related note, it looks like NodeJS does weekly releases so 10.2.2 should be out in a few days. I'm hoping that resolves the issues with Travis, otherwise I'm thinking we should only test against Node v8 until it's all working again.
> Fix MatchingEngine unit test

- lib/lndclient/LndClient.ts
This adds calls to expose useful lnd API methods for wallet and channel management. Furthermore, existing code is refactored using generics to minimize code repetition.
> Add lnd wallet & channel methods, use generics

- lib/raidenclient/RaidenClient.ts
- lib/raidenclient/errors.ts
This adds several methods that are useful for managing payment channels and the raiden ETH account, as well as some minor refactoring to better use typescript.
> Add raiden wallet & channel methods

- bin/xucli
- bin/xud
- lib/lndclient/LndClient.ts
- package.json
- tsconfig.json
- tslint-alt.json
This PR does the following:
- Adds an `npm stop` script,
- Skips compiling each time `npm start` is called, and splits the `dev` script into `dev` - which compiles and starts - and `dev:watch` - which watches for changes to the code while running. 
- Fixes the lint script by combining two `tslint` commands, one according to the tsconfig.json project file (which only inspects files/folders that are being compiled) and one according to specified folders with a modified config to avoid warnings for required type information.
- Only compiles the `lib` folder. As a result, no `lib` folder is created within `dist` and therefore
all references to `dist/lib` have been adjusted. 
- Disables javascript compiling (not currently used).
- Enables the `noImplicitThis` rule, which the project currently …
> Update npm scripts & tsconfig compiler options

- lib/BaseClient.ts
- lib/Logger.ts
- lib/db/DB.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/MatchesProcessor.ts
- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/OrderBookRepository.ts
- lib/p2p/P2PRepository.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/raidenclient/RaidenClient.ts
- lib/rpc/RpcMethods.ts
- lib/rpc/RpcServer.ts
This pr adds contexts to the logger as in #99.
But I am not sure about the fact that every context has its own static instance in the `Logger` class. What about a constructor that takes only the context as argument? `logDir` and `level` are the same anyway.
> Added contexts for logger

- lib/orderbook/OrderBook.ts
- lib/rpc/RpcMethods.ts
- test/integration/OrderBook.spec.ts
A small PR for just defining the order book high-level API.
* making `addPeerOrder` a private method, because it won't be consumed directly by exchanged, but rather by the P2P layer. 
* defining two public methods, to be directly consumed by exchanged: `addFillOrder` & `addMarketOrder`. both are implicitly referring to an `OwnOrder`.
The idea of how to implement a Market Order: 
* Buy orders `price` will be set to `Number.MAX_VALUE`.
* Sell order `price` will set to 0.
* After matching, the remaining order won't become a maker order: it won't be added to the queues (for internal matching), and won't be broadcasted to peers. 
@kilrau 
#105
> Market Order task - consolidation

- lib/cli/commands/getorders.ts
- lib/orderbook/OrderBookRepository.ts
`getOrders` calls from the command line without specifying `max_results` now default to 10 rows max. Specifying a `max_results` value of 0 will return an unlimited number of orders.
> Set default 10 maxResults for cli getorders

- lib/p2p/SocketAddress.ts
This adds some type safety to the `SocketAddress` class and switches to arrow functions to follow the style of other classes.
> Type safety for SocketAddress

- lib/Xud.ts
- lib/bootstrap.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/service/Service.ts
Fixes #126 
Plus:
* crashing the process on `unhandledRejection`. there's no reason to swallow them. 
* creating a separate `bootstrap` function, to be accessible from different entry points (tests, etc.).
> Pool silent conn error

- bin/xucli
This PR takes care of two things:
`xucli` demands one command which means that if none is specified help will be shown. 
If the specified is not found help and the error `Unknown argument: foo` will be shown. `.strict()` enforces that. But it doesn't play nicely with options containing dots (`Unknown argument: rpc`). I found two ways to handle that:
Adding
```
"yargs": {
"dot-notation": false
}
```
to `package.json`. That means that nested object won't be possible. For example: `argv.rpc.host` would become `argv['rpc.host']`.
Or initializing `rpc` is an empty object in `bin/xucli`:
```
rpc: {
default: {},
},
```
The disadvantage of this method is that the help of `xucli` would look like this:
```
xucli <command>
Commands:
xucli connect <host> [port]               connect to an xu node …
```
> cli improvements

- README.md
- bin/xud
- lib/Config.ts
- lib/lndclient/LndClient.ts
- lib/service/Service.ts
This is similar to the changes in #129 except applied to the LND client. Now all LND calls use the generated request/response types, and the main purpose of LNDClient.ts is to establish the grpc connection and to wrap calls with promises.
I did the bare minimum to make the `getinfo` cli call working, as it is being reworked in #131.
> Refactor lndclient

- README.md
- bin/xud
- lib/Config.ts
- lib/db/DB.ts
- package-lock.json
- package.json
This PR restores the `mysql2` dependency removed in #140 because it is required when Sequelize is using the mysql dialect. This also removes sql dialect as one of the configurable db options, thereby enforcing the use of a mysql-compatible database via the code.
> Restore mysql2 dependecy, hardcode mysql dialect

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/Packet.ts
- lib/p2p/packets/index.ts
- lib/p2p/packets/packetUtils.ts
- lib/p2p/packets/types/HelloPacket.ts
- lib/p2p/packets/types/OrderPacket.ts
- lib/p2p/packets/types/PingPacket.ts
- lib/p2p/packets/types/PongPacket.ts
This is a followup to #189. I think I found a reasonable approach to the packet classes using generics. The body property itself is generic, and all classes extended `Packet` share a single constructor which itself is overloaded in that it accepts either a packet body type and an optional request hash (for creating outgoing packets) or a string (for deserializing incoming packets).
This refactors the Packet class and its derivations in the following ways:
- Adding a generic type parameter to Packet which is used for a generic constructor and to define the `body` type.
- Generic constructor that accepts either a packet body type or a string. If passed a string, it attempts to deserialize it into a packet.
- Renaming `MessageType` to `PacketDirection` to differentiate itself from …
> Refactor packets

- lib/Xud.ts
- lib/p2p/HostList.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/PacketType.ts
- lib/p2p/packets/index.ts
- lib/p2p/packets/packetUtils.ts
- lib/p2p/packets/types/GetHostsPacket.ts
- lib/p2p/packets/types/GetOrdersPacket.ts
- lib/p2p/packets/types/HostsPacket.ts
- lib/p2p/packets/types/index.ts
- lib/service/Service.ts
Resolves #147. I split this into two commits, the first is an attempt at some general cleanup, refactoring, and code documentation around the p2p module. The second implements the new packets. Currently the `GetHostsPacket` is empty, but we can modify this in the future to specify some criteria for which hosts should be returned. When we successfully establish an outbound connection to a peer, we send a `GetHostsPacket` which kicks off recursion of connecting to new hosts as long as we keep finding out about new ones.
> Hosts and Get_Hosts Packets

- lib/nodekey/NodeKey.ts
- lib/p2p/Peer.ts
- lib/p2p/packets/types/HelloPacket.ts
Closes #160. I only renamed the instances where it's referring to the `string` form of the actual public key. The class representing the private/public keypair is still `NodeKey`. In a separate PR I'll implement putting this value into the HelloPacket.
> Rename nodeKey to nodePubKey

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
This defines types of the `.on()`, `.once()`, and `.emit()` `EventEmitter` functions for the `Peer` class. If this looks good, I can use the same approach to our other classes that extend `EventEmitter`.
> Define peer events interface

- lib/cli/commands/cancelorder.ts
- lib/cli/commands/placeorder.ts
- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/Service.ts
- lib/types/matchingEngine.ts
- lib/types/orders.ts
- proto/xudrpc.proto
- test/integration/OrderBook.spec.ts
- test/unit/MatchingEngine.spec.ts
Closes #175 
I thought `internalId` (because it is doesn't leave the exchange) is more suitable than `clientOrderId`. Thoughts?
> Split order IDs

- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- package-lock.json
- test/unit/MatchingEngine.spec.ts
I created a typed interface for our priority queues in the MatchingEngine.ts class, and in the process detected and fixed a bug with the way peer orders were previously being removed.
> Priority queue types & removePeerOrders fix

- lib/orderbook/OrderBook.ts
- lib/p2p/Parser.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/OrderInvalidationPacket.ts
- lib/types/orders.ts
This adds event types like with #212 to our other `EventEmitter` classes. I also fixed a bug where the peer id was accidentally getting assigned to the `hostId` value on peer orders.
> Event types

- README.md
fixes #46 
- Added to the readme,
@kilrau But couldn't add for typedoc, since typedoc is an auto generated documentation from codes, where should I add this information in the code since we didn't do any change on code ?
> Added Auto-Restart section to Readme #46

- lib/cli/command.ts
- lib/constants/errorCodesPrefix.ts
- lib/grpc/GrpcService.ts
- lib/lndclient/errors.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
- lib/p2p/errors.ts
- lib/raidenclient/RaidenClient.ts
- lib/raidenclient/errors.ts
- lib/service/Service.ts
- lib/service/errors.ts
Fixes #229. Partially addresses #116. This gracefully handles invalid `placeOrder` requests such that they don't crash the main xud process. I changed `xucli` to not print the stack trace, since I don't think it's helpful for developers/testers and it's even less helpful for end users. I also tried to standardize the `errors` classes to not use the `any` type, and I added a `.` separator in the `code` after the prefix.
> placeOrder gRPC error handling

- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
Fixes #257. @kilrau give this a quick test if you can, it's a minor change so we can merge without much review. I did also rename `DUPLICATED_ORDER` to `DUPLICATE_ORDER` since "duplicate" and "duplicated" have [slightly different meanings](https://english.stackexchange.com/questions/67463/duplicate-data-or-duplicated-data) and I think the former is more appropriate here.
> Handle duplicate placeorder localId

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/service/Service.ts
Fixes #253.
This changes the `socket` property on the `Peer` class to be nullable and adds null checks before we attempt to write to the socket. It also removes a duplicate socket error handler, and it removes the `destroy` call from the other `error` event handler. As per the Node.js Net module documentation. the `close` event is called right after the `error` event, and we already call `destroy` within the `close` handler. Lastly, this renames the `connect` and `disconnect` methods in Pool.ts to `open` and `close` to match the corresponding method names in Peer.ts.
I have run some limited tests with this and verified that connecting works. @kilrau, can you pull down this branch and see if it makes the crash you were seeing go away?
> Fix socket error & close handling

- lib/db/models/Host.ts
- lib/p2p/HostList.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/HostsPacket.ts
Fixes #226.
This fixes a bug that was causing xud to attempt to add existing hosts to the database. The `HOSTS` packet was serializing `Host` objects to JSON. Upon receiving this packet, xud would create JSON objects which did not inherit the function definitions of the `Host` class and, critically, of the `SocketAddress` class which was used as a unique identifier for hosts. The `toString()` method of `SocketAddress` was therefore lost and reverted to that of `Object`. `getOrCreateHost` would use the `toString` method to see if a Host exists, but then create using the actual `address` and `port` fields which would still exist on the object.
This commit changes the `HOSTS` packet to pass `HostFactory` typed objects, from which a new `SocketAddress` is constructed. `getOrCreateHost` …
> Fix bug causing host uniqueness violation

- lib/grpc/GrpcService.ts
This fixes the error described in #263 when attempting to connect to an already connected peer via the API.
Here's what the cli output looks like:
```bash
xucli connect localhost 9885
Error: 6 ALREADY_EXISTS: Address (localhost) already connected
```
> Handle already connected grpc error

- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Pool.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/types/db.ts
- lib/types/orders.ts
- proto/xudrpc.proto
- test/unit/MatchingEngine.spec.ts
This replaces the `hostId` identifier on orders with `peerId`. Since orders are no longer being persisted between sessions, and since all orders for a peer are removed once that peer is disconnected, we no longer need to associate orders with a persistent identifier like `hostId`. This will make it easier to associate matched, swapped, or invalidated orders with an actual live peer.
This functionality is a prerequisite for #106 and #236.
> Replace hostId with peerId on orders

- lib/orderbook/OrderBook.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/types/orders.ts
- proto/xudrpc.proto
Fix #276 
* renaming existing `isOwnOrder` to `isOwnOrdersMap`
* after match, doing order update, without assuming it was an internal match
* proto `Order` message: remove `peer_id`, change `host_id` to int32 (it caused an error). 
Please regenerate the proto files for me, because I still didn't downgrade my version.
> non-internal match order update

- lib/orderbook/MatchesProcessor.ts
- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Pool.ts
- lib/service/Service.ts
- test/integration/OrderBook.spec.ts
- test/unit/MatchingEngine.spec.ts
Closes #176 
The `OrderBook` sends the `OrderInvalidationPacket` after a match. After the Raiden swap integration the packet should be sent after a successful swap. And the `OrderBook` is able to handle `OrderInvalidationPacket` with a quantity (= partially filled orders).
And I would prefer that #265 gets merged first.
> Order invalidation implementation

- lib/Xud.ts
Fixes #294. This moves the initialization of the p2p pool until after the orderbook is initialized. This is because peer connections will trigger `ORDERS` and `GET_ORDERS` packets that depend on an initialized orderbook to work properly. It also ensures that the p2p pool is initialized before starting the gRPC server.
> Initialize pool after orderbook

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
This removes calls of the `Peer.close` method before a socket is open, which prevents the `close` event from firing, instead relying on the `cleanup` method to tie up loose ends when a connection to a peer errors or times out. It also removes duplicate log messages when a socket errors or is closed, and prevents logging stack traces for non-fatal peer errors.
> Remove extraneous p2p logging & closes

- lib/Logger.ts
- lib/Xud.ts
- lib/p2p/Peer.ts
- tslint.json
This adds a new lint rule enforcing a style of declaring public, protected, and private fields in each class in that order. It also requires that methods come after the constructor and that static methods come before instance methods.
This was suggested by @michael1011 and I think it's a good idea, plus conforming to these rules only required a handful of changes meaning we were already more or less following this style. I think it'd be good to enforce it as a rule.
> Member-ordering lint rule

- lib/p2p/Peer.ts
Something small -
* move connection timeout value to a static field
* don't do `this.connectTimeout = undefined` on timeout. `cleanup` is handling this
> connection timeout handling

- lib/BaseClient.ts
- lib/Xud.ts
- lib/cli/command.ts
- lib/db/DB.ts
- lib/grpc/GrpcServer.ts
- lib/grpc/webproxy/GrpcWebProxyServer.ts
- lib/lndclient/LndClient.ts
- lib/nodekey/NodeKey.ts
- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
- lib/p2p/PeerList.ts
- lib/p2p/Pool.ts
- lib/p2p/SocketAddress.ts
- lib/p2p/packets/Packet.ts
- lib/raidenclient/RaidenClient.ts
- lib/service/Service.ts
- lib/types/matchingEngine.ts
- lib/utils/utils.ts
- test/integration/OrderBook.spec.ts
- test/unit/MatchingEngine.spec.ts
I'm looking to regenerate the typedoc for the codebase soon, and before doing that I wanted to try to clean up the codebase a bit and add comment blocks anywhere I felt it was lacking or the code wasn't particularly clear. This PR:
- Adds typedoc comments to help document and clarify the code.
- Renames several variables and properties in an attempt to make their use and purpose more clear.
- Replaces internal use of `null` with `undefined`. The code base previously used both interchangeably, but undefined was more common and is the default value for properties defined with the nullable `?` operator.
- Replaces objects used for mapping key-value pairs with `Map` instances.
- Attempts to follow the [javadoc style guide](http://www.oracle.com/technetwork/java/javase/documentation/index-13786 …
> Add comments, rename variables, minor refactoring

- lib/orderbook/OrderBook.ts
Addressing #142
At the moment it's checking that the order is duplicated, and not solely `id`. 
More precisely, that the id+pairId+orderSide tuple is duplicated. That's because we're dividing the orders by pairId, and then by sell/buy. 
Having a support for a duplication only on the order id would be messy right now. If we want that support, it should be a part of #215.
I didn't add tests, because it requires p2p tests, and not integration tests. But I temporarily turned `addPeerOrder` method to public, run some quick tests, and it looks fine.
> drop duplicated peer orders

- lib/Xud.ts
- lib/lndclient/LndClient.ts
This ensures that lnd clients are closed properly during shutdown and that we wait for the database to close. Previously, xud would never shutdown if it was attempting to reconnect to lnd.
I tested the `xucli shutdown` command both while connected to peers and while not connected to any peers and it works as expected with these changes.
> Fix shutdown procedure

- bin/xucli
- lib/cli/commands/orders/limitorder.ts
- lib/cli/commands/orders/marketorder.ts
Closes #249 
This PR separates the CLI command `placeorder` into `limitorder` and `marketorder`.
>  Separated placeorder command

- lib/orderbook/MatchingEngine.ts
- package-lock.json
- package.json
Unless we have any more plans for changes to the `fastpriorityqueue` package, I figure we might as well switch back to the upstream version rather than our fork.
> Switch to upstream fastpriorityqueue

- lib/p2p/NodeList.ts
- lib/p2p/P2PRepository.ts
- lib/p2p/Pool.ts
- test/integration/Pool.spec.ts
- test/p2p/sanity.spec.ts
This makes it so the database is updated with listening addresses from a node after the handshake, even if we already had a record for that node in the db. Currently, once a row is written to the nodes table it won't be updated, but it makes sense that we should update with the freshest info we've received from a peer.
I also added a new test suite for `Pool` with a couple of test cases that test this new functionality.
Lastly I caught a few issues during testing with the way we were initializing and shutting down the Pool, the `listen` and `unlisten` methods were not resolving properly, and fixed those here as well.
> Update node addresses on handshake

- lib/p2p/Pool.ts
- lib/p2p/errors.ts
- lib/utils/utils.ts
*EDIT:*
Closes #181 
This PR appends the nodes external IP to `handshakeData.addresses` if no address was specified by the user.
> Discover node's external IP

- test/p2p/sanity.spec.ts
- tslint.json
This adds some tslint rules around whitespace that were already de facto rules - as you can see there was only one place in the entire codebase that needed to be corrected - so that they will be enforced automatically going forward.
> Add tslint whitespace rules

- bin/xud
Closes #356. This adds aliases for `db.database` and `webproxy.port`, the other common arguments you'd need to set when wanting to run two xud instances on the same machine. By default running `xud` will use p2p port 8885, rpc port 8886, db name xud, and web proxy port 8080. With this you can run `xud -p 9885 -r 9886 -d xud2 -w 9080` on separate ports and a different database without needing to do too much typing.
Edit: You'd actually need to specify the xud directory too, where the node key is stored, which already has its own alias. So something like `xud -p 9885 -r 9886 -d xud2 -w 9080 -x ~/.xud2` would work.
> Add aliases for db name and webproxy port

- bin/xud
- lib/Config.ts
- lib/Xud.ts
- test/integration/Pool.spec.ts
- test/integration/WebProxy.spec.ts
- test/p2p/sanity.spec.ts
This ensures that if a custom xudir is specified via the command line, the config file from that folder will be loaded rather than the config file in the default location. Currently, the config file in the default location will always be used.
> Fix custom folder config

- package-lock.json
- package.json
Solves #290. This prepares the xud package for distribution and installation via `npm install -g xud` with just the compiled files needed for execution and no source code for development. The `google-protobuf` package is included in the `grpc_tools_node_protoc_ts` dev dependency, and is added as a regular dependency for distribution.
I tested this myself by installing the package globally and confirmed that `xud` and `xucli` were added to my path.
> Configure package for distribution

- lib/grpc/GrpcServer.ts
- lib/grpc/GrpcService.ts
- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
- lib/service/Service.ts
This aims to be at least an intermediate solution to #339.  It's in an unfinished state but I wanted feedback before I went and applied the same pattern to every call. `getInfo` is the main call to look at, you can ignore the others for the purposes of initial review. It works and can be tested. I also refactored `connect` and `cancelOrder`.
This uses our static generated files for creating the xud grpc server - doing so requires that we use the actual generated gRPC classes for the callback. Passing a plain javascript object with the right fields won't work. This restricts the code to only be able to return valid grpc responses.
The current structure is basically that Service.ts deals with our internal types and plain javascript objects but doesn't touch anything grpc-related. It passes …
> Refactor gRPC

- docs/api.md
- lib/cli/commands/orders/limitorder.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/Service.ts
- proto/xudrpc.proto
This changes the placeOrder proto definition to only have fields that are used for placing orders.
> Refactor placeOrder

- docs/api.md
- lib/Xud.ts
- lib/grpc/GrpcService.ts
- lib/p2p/Pool.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.js
- lib/service/Service.ts
- proto/xudrpc.proto
- test/integration/Pool.spec.ts
- test/integration/Service.spec.ts
- test/integration/WebProxy.spec.ts
- test/p2p/sanity.spec.ts
This creates a test suite with a sampling of some test cases for our API service methods which are exposed via gRPC, and is a step towards resolving #119.
Running these tests actually revealed a bug with the shutdown call, which I actually accidentally introduced myself in #332. As part of that PR I added an `await` statement to the shutdown procedure to wait on the grpc server (among other things) to close before returning, but the grpc server wouldn't close until the method returned a response, thus they were waiting on each other and would hang. The first commit fixes that and adds a `shutdown` event for the `Xud` class to notify listeners when the server has completely shut down, it's used in the service shutdown test.
> Service tests

- lib/p2p/Pool.ts
This PR fixes a bug that caused the external IP of the node not getting added to the `addresses` array in `Pool.ts`.
> Fixed addresses bug

- lib/Xud.ts
- lib/orderbook/SwapDeals.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/DealRequestPacket.ts
- lib/p2p/packets/types/SwapResponsePacket.ts
- lib/service/Service.ts
- lib/types/enums.ts
- test/integration/Pool.spec.ts
This is a follow-up to #359 to resolve a circular import, TODOs, and other unresolved issues as well as fix failing tests.
Reslolves a circular import between the Peer and Pool classes by moving swap packet handling logic into Pool. Also makes some minor naming and logging changes regarding the swap packets.
> Resolve peer-pool circular import

- test/unit/Parser.spec.ts
addressing #373 
The result of this test isn't consistent for some reason. I saw the problem, fixed it, but when I revoked my changes, the problem didn't reproduce.
I expect it to be a problem with `chai-as-promised` comparing thrown exception object.
I made a fix, so please check it on your env.
If that wouldn't work, i'll change the the expectation for `wait()` to simply get rejected, without any expected error.
If that wouldn't work, then the only think I can think of now is that emitting events isn't always synchronous, so line 20 isn't stable.
> parser unit tests

- lib/types/p2p.ts
- package-lock.json
- package.json
- tslint.json
This adds a tslint plug-in and rule to check for circular imports, which we have been trying to avoid in our codebase. The rule caught one violation, a minor one with the `NodeConnectionInfo` for `NodeFactory`. I corrected it just by respecifying the type from scratch, which is not too bad because it's a short type definition.
> Add tslint circular import rule

- .travis.yml
Docker Image builds are now taken care by [Docker Hub](https://hub.docker.com/r/exchangeunion/xud/) builds are automatically triggered up on push / merge into the master branch. Hence, removed from Travis CI and this should also be speeding up our tests execution times.
> Remove Docker image build on Travis CI

- lib/Config.ts
- test/p2p/sanity.spec.ts
The tests could not run on my env because config wasn't loaded, and in my case it's necessary, because i'm using a password for the database.
In addition to that, I changed a bit how we create the config for each xud instance in the test.
> p2p sanity config fix

- lib/orderbook/OrderBook.ts
- test/integration/OrderBook.spec.ts
Closes #353 by removing `remainingOrder` from market orders
>  Removed remainingOrder from market orders

- lib/p2p/Pool.ts
Resolves #387. This no longer waits for connections to resolve on start before completing the startup process.
> Don't wait for outgoing connections on start

- lib/orderbook/MatchesProcessor.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/SwapDeals.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/DealRequestPacket.ts
- lib/p2p/packets/types/OrderPacket.ts
- lib/types/orders.ts
- test/unit/MatchingEngine.spec.ts
This is the first step towards integration of swaps with the orderbook. The initial DealRequest packet is now triggered by a match with a peer order with the deal specifics from the order.
This currently treats each swap attempt as a success, assuming the "happy path", but going forward it will need to track updates to the swap flow. I think that will depend partly on #380, where the new `Swaps` class can be an event emitter to emit events when a swap executes, fails, times out, etc... and the orderbook can listen to these events and update the orders accordingly.
I took the buffer/queue out of MatchesProcessor because I believe that all matches will be handled sequentially and synchronously. We might not need this file/class going forward since it currently doesn't have any state.
I left …
> Swap orderbook integration

- lib/grpc/GrpcService.ts
- lib/orderbook/MatchesProcessor.ts
- lib/orderbook/SwapDeals.ts
- lib/p2p/Pool.ts
- lib/service/Service.ts
Edit: Closes #348
This fixes a bug to properly set the amounts and taker lnd pub key for swaps triggered by order book matches.
To perform this yourself, first setup lnd according to the instructions in #348. Once you have btcd, ltcd, and 2 running lnd instances for each, run two instances of xud listening for rpc requests on the same ports as specified in the `resolver.conf` files.
Connect the nodes to each other, then place matching orders (I'm using the default 8886 rpc port for exchange a, and 9886 for exchange b)
```bash
xucli limitorder LTC/BTC 1 .1 .01
{
"matchesList": [],
"remainingOrder": {
"price": 0.01,
"quantity": 0.1,
"pairId": "LTC/BTC",
"peerPubKey": "",
"id": "ea55dc70-a86c-11e8-81de-35e735f1f1ab",
"localId": "1",
"createdAt": 1535204637623,
"invoice": "",
"canceled": …
```
> Order match swap execution fixes

- instructions-for-devs.md
- lib/db/DB.ts
- test/integration/OrderBook.spec.ts
- test/integration/Service.spec.ts
- test/unit/MatchingEngine.spec.ts
- test/unit/Parser.spec.ts
I realized we'd been using the `BTC/LTC` ticker everywhere, when in fact the ticker that's in use across every exchange I checked used the `LTC/BTC` ticker which prices LTC in terms of BTC. This fixes all references to that ticker, for further testing one must either manually add `LTC/BTC` to the pairs database, or delete the database and it will be added automatically when it's recreated.
> Fix BTC/LTC ticker to LTC/BTC

- lib/orderbook/MatchesProcessor.ts
This PR attempts to fix a rounding error @offerm has observed on swaps executed via the orderbook. I have not seen this myself but below is a sample error message:
```bash
8/28/2018, 1:24:20 AM [P2P] error: Got exception from sendPaymentSync {"dest":"","destString":"02fe35d3c066601c5e9f3f5de0972e0c0b3478661544c0d0eb6991355c3e676926","amt":2000.0000000000002,"paymentHash":"","paymentHashString":"3e9df9798c2d5313896834dd0873b8f069d493e0c08c8f9294a9a655cb296391","paymentRequest":"","finalCltvDelta":0} AssertionError: Assertion failed`
```
> Fix rounding error on swap amounts

- lib/Logger.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- test/p2p/sanity.spec.ts
Closes #182 
This PR takes care of verifying that the node's advertised addresses are reachable. If that is not the case the user is alerted with the message: `Could not connect to advertised address: <host>:<port>`
> Verify reachability of advertised addresses

- lib/orderbook/OrderBook.ts
This fixes logic that would throw an `INVALID_PAIR_ID` error when there are no orders for a given pair id, even though that pair id is supported.
> Fix cancelorder invalid pair false positive

- lib/cli/commands/cancelorder.ts
- lib/cli/commands/channelbalance.ts
- lib/cli/commands/getorders.ts
- lib/cli/utils.ts
This commit makes all pair and currency arguments from cli upper case before passing them to xud. As all currencies are represented in upper case strings internally, this prevents xucli errors when arguments are not typed in all upper case.
> Make pairs & currencies upper case for cli

- lib/Xud.ts
- lib/p2p/Pool.ts
- test/p2p/sanity.spec.ts
Solves #369 (I hope, @offerm can confirm). The p2p tests started failing out of the blue for me and after some digging it turns out that one of the hardcoded ports (9002 in my case) was in use. This PR makes the sanity tests use a random available port, and also adds the option to configure xud to use a dynamic p2p listening port during normal operation.  It fixed the failing tests for me.
>  Make p2p sanity tests use dynamic ports

- lib/grpc/GrpcService.ts
- lib/p2p/NodeList.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/errors.ts
- lib/service/Service.ts
- lib/types/p2p.ts
- lib/utils/addressUtils.ts
- test/p2p/sanity.spec.ts
Solves #311 
* retries are blocking `initConnection`
* retries are not activated when manually trying to connect to a peer. if it would, the user won't get a response for a very long time upon failure, since the retries are blocking.
* if max retries period exceeds, and peer was previously connected (exists on `nodes` table)
peer supposed to get banned. Banning doesn't work now for pre-handshake peers, but can be fixed. I'm not sure banning is the right solution, because in the future it might also block inbound connections. Deleting or soft deleting the node entry might not be the right thing either. Perhaps penalizing, which we haven't implemented yet. 
Anyway - that will hardly happen, because it will trigger only after 1 week, and only for previously connected peers.
The main thing …
> connection retries

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- test/integration/Pool.spec.ts
This commit delays calling the `bindSocket` method until after an outgoing connection is established. It also moves beginning an outgoing peer socket connection from the `fromOutbound` method to the `initConnection` method. This ensures that we bind the `connection` listener immediately after beginning the connection.
> Bind socket after connection

- lib/p2p/Peer.ts
This addresses an edge case whereby we receive a `HelloPacket` before we've started waiting for one, resulting in an "[peer] sent an unsolicited Hello packet" error message. Previously, there was a small disconnect between when a socket was established and when waiting for the HelloPacket began. This changes it so that the wait for the HelloPacket begins immediately after the socket becoming connected and before any packets can be received.
EDIT: Closes #448
> Relax HelloPacket checks

- .travis.yml
Hello just removed mysql configuration from travis and added a pre-required npm install to make travis build possible, somehow travis operating system wasn't able to find `node-pre-gyp` I just added it as a `before_install` condition to the configuration.
Also I've just tried to run with sqlite with your development seems okay to me, you're way better than me since that's your creation mostly so I didn't check codes in detail just checked how you implemented it :+1:
> Fixing travis build for PR 461

- .travis.yml
This fixes an issue that was causing travis builds to fail by installing `node-pre-gyp`. It also removes mysql queries that are obsolete after the transition to sqlite.
Credit to @rsercano.
> Chore: fixing travis build

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
This fixes a bug (introduced by me in #429) where sockets that failed during connection were not being properly destroyed. This is because `peer.socket` would not be initilaized until after a successful connection, whereas `peer.close()` would only destroy `this.socket`. The fix assigns a value to `peer.socket` during connection attempts, so that the socket will be properly destroyed on error.
Edit: I believe this fixes #462.
> Fix bug on failed connection

- .git-commit-template.txt
- CONTRIBUTING.MD
Closes #432
This PR introduces guidelines for crafting commit messages, with the goal of making the commit history easier to read and allowing for automated changelog generation for releases. It also puts general
contribution guidelines directly in CONTRIBUTING.md.
I'm proposing following the AngularJS commit message guidelines, as they are recommended by https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli for generating changelogs automatically.
> Docs: add contribution and git commit guidelines

- .travis.yml
Travis finally works with node 10! I made this build the latest stable node version as well as the long term support version. I figure it makes sense to keep pace with node releases and stop supporting any versions once they lose support from nodejs.
> Chore: add nodejs current and lts travis builds

- docs/api.md
- lib/cli/commands/cancelorder.ts
- lib/cli/commands/getorders.ts
- lib/grpc/GrpcServer.ts
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.js
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/Service.ts
- proto/xudrpc.proto
- test/integration/OrderBook.spec.ts
- test/integration/Service.spec.ts
Closes #424
I don't think that `OrderTypes` is a good for a gRPC message name but I couldn't come up with anything better so feel free to suggest something else.
It is still unclear if `getOrders` should be renamed to `listOrders`. Any decisions on that?
> CLI enhancements

- docker/docker-compose.yml
This commit removes reference to `db` container removed by @sangaman in `docker-compose.yml` file.
> fix: remove reference to db in docker-compose.yml

- docs/api.md
- lib/cli/commands/getorders.ts
- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/Service.ts
- proto/xudrpc.proto
- test/integration/OrderBook.spec.ts
- test/integration/Service.spec.ts
This PR removes `maxResults` and `limit` from the `getOrders` rpc call and all related internal calls. The reason for this is because orders are not ordered according to price internally - limiting the
number of orders returned simply picks an arbitrary set of orders rather than the orders with the best price. It is up to the client to sort and discard orders after they've been retrieved from `xud`.
I left a `max_results` argument on the cli call for now in case we want the cli itself to limit the number of orders displayed, which seems like a desirable feature.
> refactor: remove maxResults from getOrders

- lib/raidenclient/RaidenClient.ts
- tslint.json
This adds an automatically fixable rule to enforce style regarding a space before function parentheses. This style was already unofficially enforced and only one line in the code required fixing.
> style(lint): add space-before-function-paren rule

- test/integration/OrderBook.spec.ts
- test/integration/Pool.spec.ts
- test/p2p/sanity.spec.ts
This commit prevents the tests from loading the local configuration file. It also prevents loading the local node pub key from disk. This is unnecessary after the sqlite migration since we no longer may depend
on the local config to provide mysql connection info. Rather, errors in the local config file could cause tests to fail, and should no longer be a dependency for tests to pass.
I think a next step would be to stop the p2p simulation from reading & writing its node keys to disk. This could be done a couple of ways, one way would be to store the node key in the database (since tests use temporary databases stored only in memory), which I know we've discussed a bit and maybe should revisit.
> test: prevent loading local config

- docs/api.md
- lib/grpc/GrpcService.ts
- lib/lndclient/LndClient.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- proto/xudrpc.proto
For ease of navigation, getinfo response for lndbtc and lndltc includes  the LND's alias.
Also fix a bug that error is not being provided in case LND is disable or not connected.
> feat(CLI): getinfo presents LND's alias

- package.json
This commit removes unnecessary/informational files from our list of published files. This is because users that install from npm won't be looking in their `node_modules` folder for documentation, but rather in
our GitHub repository and similar online resources. Proto files are not needed because we use the static, generated files instead. The README is needed for use in the npm website. The LICENSE should be included with all copies of the code.
> chore: modify list of published files

- README.md
- proto/hash_resolver.proto
- proto/lndrpc.proto
- proto/xudrpc.proto
This PR applies the MIT license to our proto definitions and copies the license from the lnd project into the lndrpc.proto file. This is because projects that incorporate the `xud` rpc API via the proto files
may be unwilling to follow the copyleft restrictions of the AGPL-3.0 license - the MIT license makes it easier for closed source and propietary software (as many exchanges use) to incorporate our proto files or any files generated from it.
It also updates the readme to explicitly state that the AGPL-3.0 license applies to all files in the repository except for those with licenses provided in the header of the file.
> docs: add licenses to protos and update readme

- bin/xud
- lib/Config.ts
- lib/grpc/GrpcService.ts
- lib/lndclient/LndClient.ts
- lib/p2p/packets/types/SwapRequestPacket.ts
- lib/p2p/packets/types/SwapResponsePacket.ts
- lib/service/Service.ts
- lib/swaps/Swaps.ts
Both maker and taker can now specify via command line or configuration file a value for final hope cltv-delta. This value is used to calculate the cltv-delta when sending to the maker and to the taker. the maker's cltv-delta includes the taker's cltv-delta converted by the ration between the two cltv-deltas.
Both maker and taker now verify the received amount to make sure it matches the agreed amount.
In additon both take and maker verify the received cltv-delta time lock against the agreed one.
These checks are done as part of the resolver work. In case of a wrong value, the preImage is not discloused and error is raised.
Left to be done: cltv-delta in case of multi hops route.
> feat(SWAPS): cltv-delta

- lib/Config.ts
This fixes a bug where passing a custom `xudir` argument does not load the config file from that directory, but rather the default `xudir` directory.
Fixes bug introduced in #502.
> fix(config): use custom config file path

- test/integration/OrderBook.spec.ts
This adds a test case to the order book integration tests to simulate adding, partially filling, and then canceling the remaining portion of the order.
#506 made me realize we don't have any logic like this and it seemd like a worthwhile case to have.
> test(orderbook): add case to partly fill & cancel

- lib/p2p/Pool.ts
- test/p2p/sanity.spec.ts
This commit gets an unused port for use in the test case of connecting to a non-existing node. Previously a hardcoded value of 9003 was used for the port which would cause the test to fail if the port was in use.
> test(p2p): get unused port

- lib/lndclient/LndClient.ts
This PR exposes getInfo as a public method so it can be used when considering different routes to a peer as part of a swap. It also returns a native grpc object.
> refactor(LND): exposes getInfo as public method using native objects

- lib/lndclient/LndClient.ts
- lib/p2p/packets/types/SwapErrorPacket.ts
- lib/swaps/Swaps.ts
closes #431 
closes #421
closes #413 (with the exception of RPC timeouts which deserve a separate issue)
Maker to Taker routes
Place holder for isOrderOnBook - checks by maker before accepting a swap
Place holder for checkAndHoldAmount - uses by maker before accepting a swap. currently can't return partial amount (all or nothing).
Verify LND setup - checks that peer has LNDs PubKeys for BTC and LTC
Queryroutes - use queryroutes to check if there is a route between the maker and the taker and the implication of the route on the maker's cltvDelta.
Maker's cltvDelta better calcualtion.
> feat(SWAPS): cltv-delta Part 2

- bin/xud
- lib/Config.ts
- lib/Xud.ts
- test/integration/Service.spec.ts
- test/integration/WebProxy.spec.ts
- test/p2p/sanity.spec.ts
This commit uses all lower case for all config variables to be both internally consistent and consistent with the config naming style found in both btcd/bitcoind and lnd.
> style(config): use lower case for all config vars

- test/integration/WebProxy.spec.ts
This makes the web proxy tests use an in-memory database instead of loading an existing database from disk.
> test: use in-memory db for web proxy tests

- docs/api.md
- lib/cli/utils.ts
- lib/grpc/GrpcService.ts
- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/proto/hash_resolver_grpc_pb.js
- lib/proto/lndrpc_grpc_pb.js
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.js
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/Service.ts
- lib/swaps/Swaps.ts
- lib/types/enums.ts
- lib/types/orders.ts
- proto/xudrpc.proto
- test/integration/OrderBook.spec.ts
- test/integration/Service.spec.ts
- test/unit/MatchingEngine.spec.ts
This PR refactors how we represent buy and sell orders. Previously, sell orders were represented with a negative quantity. However, I believe this to be potentially confusing especially in regards to the API and quantity updates to existing orders, and this was echoed in our discussions. Instead, orders now have a `side` property to indicate whether they are buys or sells, and all standing orders and order matches are represented with positive quantities.
This passes all tests as well as some limited local testing of mine, namely manually placing buy and sell orders via the cli and ensuring they match as expected.
> refactor: use positive quantity for buys & sells

- lib/orderbook/OrderBook.ts
- lib/p2p/Pool.ts
- lib/swaps/Swaps.ts
This commit fixes a bug where a a maker sends an invalidation packet to the taker after an order is executed. The taker will have already adjusted the orderbook locally upon successful execution, resulting in
a duplicate attempt. This fix makes it so makers don't send invalidation
packets to takers.
Fixes #506. Fixes #478.
> fix: don't send order invalidation to taker

- test/integration/WebProxy.spec.ts
- test/p2p/sanity.spec.ts
- test/utils.ts
This changes the web proxy tests to use a dynamic, unused port instead of the default 8080 port, which could cause the tests to fail if 8080 is being used.
> test: use dynamic port for web proxy tests

- lib/Config.ts
- lib/types/enums.ts
- test/integration/WebProxy.spec.ts
- test/p2p/sanity.spec.ts
- test/utils.ts
This PR adds a config option that specifies the network for lnd clients, defaulting to `testnet`, and uses it for setting the default macaroon paths to use the new paths in lnd 0.5.
I'd originally had a `network` value for both lndbtc and lndltc clients, but changed it to be global. Will we envision ever having a use case of running lnd clients simultaneously on separate networks? e.g. simnet on one and testnet on the other?
> Use new lnd 0.5 macaroon paths

- lib/db/DB.ts
- lib/db/models/ReputationEvent.ts
- lib/p2p/NodeList.ts
- lib/p2p/P2PRepository.ts
- lib/p2p/Pool.ts
- lib/types/db.ts
- lib/types/enums.ts
- test/integration/OrderBook.spec.ts
- test/p2p/sanity.spec.ts
Closes #470 
This PR implements reputation events as described in issue #470. Those events track the history of the behaviour of a node and are stored in the database.
I decided to move the pruning of old events and informing nodes that they got banned into separate follow up PRs.
> feat(p2p): add reputation events

- .gitattributes
- .gitignore
- package.json
- sample-xud.conf
- tasks/config/sample.ts
This commit updates the publish configuration to generate a sample config file before publishing and to include it among the published files.
Edit: The new approach generates the sample config file on the `npm version` script and checks it in via git. Closes #498.
> chore: generate sample config on new version

- lib/proto/hash_resolver_grpc_pb.js
- lib/proto/lndrpc_grpc_pb.js
- lib/proto/xudrpc_grpc_pb.js
- package.json
- winFixDeprecation.ps1
This is a simple fix we used at [`walli-server`](https://github.com/dopetard/walli-server) it simply changes `new Buffer` to `Buffer.from`.
> fix :Deprecation warning 

- lib/Xud.ts
- lib/lndclient/LndClient.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/types/p2p.ts
Closes #513.
This commit creates an event for when a LightningClient verifies (or re-verifies) a connection to an lnd server. It includes the lnd identity pub key if it changed. When the pub key changes, the new value
is broadcast to all currently connected peers within a new Hello packet. This allows for switches of lnd servers without requiring a restart of xud, and also will inform peers of lnd pub keys when lnd comes back online should lnd be offline at the time of peer connection.
I've tested this locally and it seems to be working well. Here's what the log output looks like on the remote peer receiving the handshake update, below is the original and the updated handshake.
```
2018-9-23 15:46:03 [P2P] verbose: received hello packet from 127.0.0.1:9885: …
```
> feat: update handshake on lnd pubkey change

- README.md
Changed README.md wording from 'Exchange Union' to 'XUD'. XUD is the correct description of the node and technology, whereas Exchange Union is the business use case "connecting exchanges" on top.
> doc: Exchange Union -> XUD

- lib/p2p/Pool.ts
- test/integration/WebProxy.spec.ts
Fixes #516.
This PR addresses two issues identified in the issue above:
1. It disables the `initdb` option when creating an `xud` instance for the web proxy tests. Initializing the database is not necessary for these tests.
2. It ensures that no connections that are in a pending state when the p2p pool is disconnected are allowed to complete. It closes all pending connections and any connections that open after
disconnection of the pool. Previously, a connection that's attempted right before disconnecting could have interfered with shutting down `xud`.
> Disable initdb for web proxy tests & prevent new connections after closing pool

- lib/swaps/Swaps.ts
Recently all order quantities were changed to be positive, therefore negating the negative in `calculateSwapAmounts` is not needed and can actually result in negative amounts.
> fix(swaps): don't calculate negative amounts

- bin/xud
- lib/Config.ts
- lib/lndclient/LndClient.ts
This PR adds a `nomacaroons` option for lnd clients to disable use of macaroons, which can be a helpful shortcut for testing purposes.
> feat(lndclient): add nomacaroons option

- bin/xud
This PR adds a command line argument for the recently added `network` config option, which specifies the network for all lnd clients.
> feat: add network command line argument

- lib/lndclient/LndClient.ts
This removes code that subscribes to lnd invoices. This is currently unused and as far as I know there are no plans to use it in the foreseeable future given the hash resolver approach we have taken for swaps.
> refactor(lndclient): remove invoice subscription

- lib/cli/commands/addcurrency.ts
Fixes #527.
This PR fixes a bug where the available swap client choices in the cli for the `addcurrency` call did not match the internal `SwapClient` enum values.
> fix(cli): fix addCurrency swapClient arg

- lib/Config.ts
- lib/Xud.ts
This PR fixes the derivation of the default lnd macaroon paths based on the active network. Previously, changing the `network` config value from `testnet` would not change the default macaroon paths, they would need to be manually specified. This also correctly sets the testnet directory for the litecoin network as `testnet4` instead of `testnet`.
> fix(config): properly set default macaroon paths

- lib/BaseClient.ts
- lib/lndclient/LndClient.ts
When testing with an old node that's been offline for a while, I've noticed that xud starts up just fine even while lnd is still catching up and is not yet fully functional. This PR checks to make sure lnd is synced to the backend chain when verifying a connection to it. If out of sync, we set a timer to reverify the same as if we could not call `getInfo` and hit a `Disconnected` status. This also removes the check against verifying the connection after a connection has been verified, as we might want to make checks going forward that lnd is still responsive and in sync.
I think we may want to consider setting a timer to periodically recheck that the chain is in sync and all is well. I've found that lnd continues to accept and send payments if it loses connectivity to the backing bitcoin …
> feat(lndclient): check if chain is out of sync

- lib/orderbook/OrderBook.ts
- lib/p2p/packets/types/SwapResponsePacket.ts
- lib/swaps/Swaps.ts
- lib/types/enums.ts
- lib/types/orders.ts
This PR moves much of the swap request handling logic to the order book where new checks verify that the order being swapped is available. If an order is unavailable, the swap requested is rejected with a
reason. If the order is at least partly available, the swap is accepted for the available amount. On partial accepts, the taker will readjust the swap amounts for the partly accepted quantity. This also removes
the unused `swap.accepted` and `swap.rejected` events.
Some functionality that will be needed to follow this up:
- Actually call queryRoutes (I have a separate commit ready to open after this PR, just didn't think it was best to put this in the same PR).
- Don't always invalidate the full order when an order is swapped, instead check how much quantity the swap was for and adjust …
> feat: check order book before accepting swap

- lib/db/DB.ts
This PR comments out the ZRX/GNT trading pair from being initialized for new databases, since they currently have no swap support.
> refactor(db): remove seed ZRX/GNT trading pair

- lib/orderbook/OrderBook.ts
- lib/swaps/Swaps.ts
This PR adds a check before broadcasting an order to peers to ensure that we have active swap clients for both sides of the trading pair for that order. In other words, we check to make sure that an order can be swapped before advertising it to peers. This is done to avoid polluting peers' order books with orders that can't possibly be swapped, which can result in unnecessary swap failures and banning.
> feat: check if order is swappable before broadcast

- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
- test/unit/MatchingEngine.spec.ts
This PR makes it so we only remove part of our own maker orders when only part of them get swapped. Previously, the full order was removed from the order book even if only part of it was swapped. Now,
a partial swap results in a quantity reduction but leaves the order in the order book.
> feat: leave partially swapped orders in order book

- lib/orderbook/OrderBook.ts
This fixes a bug where an order's local id was not being set on the `ownOrder.filled` event.
Thanks to @michael1011 for noticing the behavior.
> fix(orderbook): set localId on own order removals

- lib/lndclient/LndClient.ts
- lib/service/Service.ts
This PR attempts to standardize the way `LndClient` methods return values, going with native gRPC objects rather than the converted plain `AsObject` types. It also removes methods that are no longer expected to be used.
It may also make sense to standardize the way parameters are passed to LndClient methods - either as a native object or just as standard method parameters with the native request object being created inside the LndClient class. I think i prefer the latter - it seems like the much cleaner way to handle empty request objects and overall it reduces the potential for boiler plate code I believe.
> refactor(lndclient): remove asObject types

- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
Fixes #539 
Hello,
first of all this was a bit tricky to reproduce but I managed in the end, in my opinion current simple commit fixes the issue, maybe not calling `this.removePeerOrders` on `peer.close` in `bindPool` method would be better, I couldn't decide, current fix seemed easier to me.
Would you please check ?
> Fixes #539, tricky bug for removing ownOrders when there's an unreachable node

- lib/Logger.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/NodeList.ts
- lib/p2p/Parser.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/Packet.ts
This makes all static constant fields `readonly` so that they can't be reassigned a new value and also uses a consistent UPPER_SNAKE_CASE naming convention.
> refactor: make static constants readonly

- lib/swaps/Swaps.ts
This makes `errorReason` nullable, so that we don't have to explicitly assign an empty string to it when creating `SwapDeal` objects.
> refactor(swaps): make errorReason nullable

- lib/grpc/GrpcService.ts
- lib/p2p/Pool.ts
- lib/p2p/errors.ts
This commit fixes the logic that prevents us from connecting to banned nodes or creating duplicate connections to any node. Some of that logic was only applied for connecting to a set of nodes, but not on attempts to connect to a single node like through the rpc `connect call. All general checks have been moved to the `addOutbound` method which is a key method that all outgoing peer connection attempts go through.
> fix(p2p): consistent checks before connecting

- lib/swaps/types.ts
This commit puts types related to swaps that are used throughout the project in their own file. It also properly derives the `SwapResult` type from `SwapDeal`, of which it is a subset.
I'm using the `types.ts` pattern we discussed several weeks back, eventually I think all the current types files should be moved to `types.ts` files within their respective folders.
> refactor: create types file for swaps

- lib/lndclient/LndClient.ts
This commit properly schedules automatic retries to verify a connection to lnd when the backing chain is out of sync. It also adds a separate hardcoded delay for reconnecting due to chain being out of sync, it is longer since syncing the chain typically takes longer to resolve than other intermittent connection issues.
Fixes #593.
> fix(lnd): automatically retry if chain out of sync

- .travis.yml
A temporary solution until we can figure out why the build is failing with Node 11.
> chore: skip current node build to fix travis

- lib/types/orders.ts
This commit adds comments to better explain the various order types used within `xud`.
@ImmanuelSegol Let me know if you think this makes things clearer or if there are any types that are still not very clear.
> docs: add comments to order types

- docs/api.md
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.js
- proto/xudrpc.proto
This attempts to provide more clarity, consistency, and detail in the proto comments. It is an incremental change and more detail should follow.
I intentionally left the order-related messages and calls alone until after we've finalized no matching mode.
> docs: improve proto comments.

- lib/orderbook/MatchingEngine.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Pool.ts
- test/unit/MatchingEngine.spec.ts
Adds logic to check that `peerPubKey` on the order matches the pub key
of the peer who sent the invalidation packet.
Closes: https://github.com/ExchangeUnion/xud/issues/242
> refactor(p2p/orderbook): group peer orders by peerPubKey

- lib/p2p/Pool.ts
This fixes a bug whereby we would not connect to nodes that did not have listening addresses advertised but *did* have a `lastAddress` that we'd used to connect to them in the past and should use again.
Fixes #606.
> fix(p2p): connect to peers with lastAddress only

- lib/orderbook/OrderBook.ts
I saw this issue after checking #612. I'm not sure it's the entire problem, we'll need to have testing for this section soon.
> fix: addOwnOrder iteration call

- docs/api.md
- lib/proto/hash_resolver_grpc_pb.js
- lib/proto/lndrpc_grpc_pb.js
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.js
Our `protoFixDeprecation` npm script fix was missing.
> proto deprecation fix

- lib/swaps/Swaps.ts
- test/unit/Swaps.spec.ts
This fixes a bug in the `SwapDeal` and `SwapResult` logic for setting values for `takerAmount`, `makerAmount`, `amountReceived`, and `amountSent`. Previously the values could be mistakenly switched.
Fixes #604.
> fix(swaps): correctly set taker & maker amounts

- lib/orderbook/TradingPair.ts
- lib/orderbook/errors.ts
- test/unit/TradingPair.spec.ts
This is a minor change to the `ORDER_NOT_FOUND` error message to make it more readable. Instead of `peerPubKey` and `orderId` being separated by only a `/` for peer orders, they are clearly differentiated.
I'd found myself confused when reading the old error message, thinking that it was using `peerPubKey` in place of `orderId`.
> refactor(orderbook): change ORDER_NOT_FOUND msg

- lib/grpc/GrpcService.ts
- lib/lndclient/LndClient.ts
- lib/lndclient/errors.ts
This adds the `UNAVAILABLE` code as one of the possible grpc status codes that can be returned by `xud`. This status is intended for calls that can fail due to transient conditions and may be successful if tried again at a later time. The two existing errors that meet that description are `LND_IS_UNAVAILABLE` (renamed from `LND_IS_DISCONNECTED` because lnd may be reachable via grpc but out of sync with the chain)) and `COULD_NOT_CONNECT` from the p2p context. We automatically attempt to reestablish a connection to lnd, and nodes that are offline may come back online.
> feat(rpc): add UNAVAILABLE grpc error status code

- package.json
This renames and updates the script to generate typedoc html and makes it run every time a new version is tagged. It removes the `xud` README from the generated typedoc.
> chore: update typedoc script and run on version

- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
This creates a `LOCAL_ID_DOES_NOT_EXIST` exist error for when `xud` is asked to look up a local id that does not exist. This error is used in place of the `ORDER_NOT_FOUND` error.
> refactor(orderbook): localId does not exist error

- package-lock.json
- package.json
This updates the typescript dependency to be in sync with the version used by typedoc as discussed in #629. The older version of tslint was not compatible with the new version of typescript, so that was updated as well.
> chore: update typescript dependency

- .npmrc
- package-lock.json
- package.json
This adds a new dependency and script used to generate a changelog from the commit history and makes it part of the `npm version` routine to automatically generate and check in CHANGELOG.md when a new version is tagged.
> chore: add script to generate changelog

- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/p2p/Pool.ts
- lib/service/Service.ts
- lib/types/orders.ts
- test/integration/OrderBook.spec.ts
- test/unit/TradingPair.spec.ts
This releases the hold placed on an order when we accept a swap once the swap either completes or fails. Previously, holds would remain on orders post-swap which would make part or all of the order unavailable for future swaps.
Closes #549.
> feat(orderbook/swaps): release order hold

- lib/orderbook/OrderBook.ts
- lib/p2p/packets/types/SwapRequestPacket.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- lib/types/db.ts
- lib/types/enums.ts
- test/unit/Swaps.spec.ts
This makes each node involved in a swap determine the swap amounts and currencies (`makerCurrency`, `takerCurrency`, `makerAmount`, and `takerAmount`) independently. If there is any discrepancy in these
values, the swap will fail. These values are no longer sent as part of the `SwapRequestPacket`. Previously, only the taker (who initiates the swap) would determine these values and the maker would blindly accept them.
It also updates the Swap unit tests to align with the new methods and logic used in the `beginSwap` and `acceptDeal` routines.
Closes #615.
> feat(swaps): calculate swap amounts locally

- lib/orderbook/OrderBook.ts
- lib/swaps/Swaps.ts
- lib/types/enums.ts
- test/unit/Swaps.spec.ts
This adds a check when deciding whether to accept a swap request to ensure that it is valid. For now, a swap is considered invalid if it has non-positive proposed quantity or if its rHash is not exactly 64 characters.
> feat(swaps): check that swap request is valid

- lib/db/DB.ts
- lib/db/models/Currency.ts
- lib/db/models/Node.ts
- lib/db/models/Order.ts
- lib/db/models/Pair.ts
- lib/db/models/ReputationEvent.ts
- lib/db/models/SwapDeal.ts
- lib/db/models/Trade.ts
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/OrderBookRepository.ts
- lib/orderbook/TradingPair.ts
- lib/p2p/Pool.ts
- lib/raidenclient/RaidenClient.ts
- lib/service/Service.ts
- lib/swaps/SwapRepository.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- lib/types/db.ts
- lib/types/matchingEngine.ts
- lib/types/orderBook.ts
- lib/types/orders.ts
- test/integration/OrderBook.spec.ts
- test/unit/DB.spec.ts
- test/unit/TradingPair.spec.ts
This PR closes #621 and resolves the first part of #437.
I set out to restructure the database models ahead of persisting trades to the database as we'd discussed, it wound up being a bit more complicated than anticipated (and this PR bigger than expected) but I tried to separate every conceptually distinct change into its own commit. Details are in the body of each commit message but I'll go over the important parts here:
- `initialQuantity` on stamped orders: Currently all `quantity` usage in `xud` refers only to the currently available quantity for an order, but we had nothing to track the initial quantity of an order before being matched, canceled, etc... I added this new property to stamped orders because I expect that it will be useful info when saving orders to the database. …
> Add Order & Trade Models, restructure & rename order types

- lib/p2p/NodeList.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/types/enums.ts
> refactor(peer) removing banning logic

- lib/db/models/SwapDeal.ts
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBookRepository.ts
- lib/p2p/Pool.ts
- lib/swaps/SwapRepository.ts
- lib/types/db.ts
- test/unit/DB.spec.ts
This modifies `SwapDealAttributes` to include a references to its corresponding `Order` and `Node` attributes. When swap deals are fetches from the database, it now also fetches info about the order and node.
This also amends the type definitions for the attributes passed to `sequelize.define` to allow nullable attributes. Previously, we had to make all attribute type definitions non-nullable to avoid compilation errors, even on attributes that were nullable in the database.
This will be helpful for #625, @ImmanuelSegol after this is merged you can get everything you need for the `ListSwapDeals` call from `getSwapDeals`.
>  feat(db): join swapdeal to order & node

- lib/orderbook/OrderBook.ts
- lib/orderbook/OrderBookRepository.ts
Edit: This addresses most of #608 but not the case where a swap is initiated by a remote peer.
> feat(OrderBook.ts) persist trades to DB

- lib/orderbook/TradingPair.ts
- test/integration/OrderBook.spec.ts
- test/unit/TradingPair.spec.ts
This is a follow-up to resolving #649. Previously it wasn't straightforward to log when orders were removed from the orderbook due to matching, because the matching routine would *always* remove the top order from the queue and then add back a part of it if it was only partially matched. Adding and removing orders executes in `O(log n)`, as opposed to `O(1)` for peeking the top of the queue. 
Instead, this handles partial matches by creating only one new object with the matching quantity while reducing the quantity of the existing order (similar to how order invalidations or removes from the API are handles). Orders are only removed from the queue when they are fully matched. By reducing the number of adds/removes to the queue and new objects being created, this should improve performance …
> Streamline matching logic and add log statements

- test/unit/Command.spec.ts
This adds the newly added `hold` value to orders in the newly added cli command unit tests to fix compilation issues for the test suites. This had slipped by our automated travis builds because both PRs (#668 and #645) were in progress at the same time.
> test: add hold value to orders

- lib/cli/commands/getorders.ts
- lib/cli/utils.ts
This attempts to make the cli output for the `buy` and `sell` commands more human-readable and succint.
Closes #620.
The missing features that will need to be added in separate PRs are adding `price` to the swap result (#656) and adding an event for failed swaps to the streaming `placeOrder` rpc call (#609).
> feat(cli): format buy & sell output

- lib/Config.ts
- lib/Xud.ts
- lib/db/DB.ts
- lib/grpc/GrpcServer.ts
- lib/grpc/webproxy/GrpcWebProxyServer.ts
- lib/lndclient/LndClient.ts
- lib/nodekey/NodeKey.ts
- lib/swaps/Swaps.ts
- lib/utils/fsUtils.ts
- lib/utils/utils.ts
- test/integration/Pool.spec.ts
- test/unit/NodeKey.spec.ts
This replaces all synchronous calls to the NodeJS `fs` and `crypto.randomBytes` methods with asynchronous calls. This improves performance by preventing blocking of the event loop. I was inspired after reading [Don't Block the Event Loop](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/). Most of the benefit is during startup/initialization, but there should also be a small benefit when proposing swaps which should happen quite frequently. 
I also added a test suite for NodeKey.ts, I was primarily motivated by having a quick way to test that the async `crypto.randomBytes` call was working but it would also be good expand in the future.
> perf: use async fs & crypto methods

- lib/BaseClient.ts
- lib/Xud.ts
- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
This fixes a bug introduced in #672 whereby the lnd clients are not properly initializing. That PR removed synchronous calls to methods that had asynchronous alternatives, which necessitated moving code from the synchronous `LndClient` constructor to an asynchronous init method.
Included in the code that was moved was logic to determine whether to change the client's status from the default value of `Disabled`. This impacted the xud initialization procedure which would only attempt
to initialize (or previously verify a connection for) an lnd client that was not disabled.
This PR creates a new `NotInitialized` status as the default to reflect the status of a newly created client. It gets changed when the `init` method is called.
> fix(lnd): don't default lnd clients as disabled

- .gitignore
Here's the auto-generated files as in https://github.com/ExchangeUnion/xud-wiki/blob/7c561a22663ba6590f68baa9c094085a0cf921c5/Docker.md
```
git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   package-lock.json
Untracked files:
(use "git add <file>..." to include in what will be committed)
docker/xud/nodekey.dat
docker/xud/tls.cert
docker/xud/tls.key
docker/xud/xud.db
no changes added to commit (use "git add" and/or "git commit -a")
```
I believe it's okay to not gitignore the `package-lock.json` file. However, please correct me if wrong if that's not the case for the Docker-generated files in …
> Docker auto-generated files added to .gitignore

- lib/db/models/Order.ts
- test/unit/DB.spec.ts
This sets the price for market orders as db null when they get saved to the database. We use prices the max number value and 0 for buy and sell orders internally, respectively. This can be helpful for matching purposes but it does not need to be stored in the databases.
>  feat(db): set null price for market orders

- lib/orderbook/TradingPair.ts
- test/unit/TradingPair.spec.ts
Closes #666 
If maker own order has quantity on hold, don't match it, but keep the order in the queue for the next match.
> feat(orderbook): don’t match with quantity on hold

- lib/grpc/GrpcServer.ts
- lib/grpc/GrpcService.ts
Fixes #699.
This tracks all active streaming gRPC calls and closes them when the gRPC server is shut down. Previously, active streaming calls would prevent `xud` from shutting down gracefully.
I've tested this and it works well for me. I also confirmed that the `cancelled` event is fired when any streaming call is ended by the client.
> fix(rpc): close streaming calls on shutdown

- lib/orderbook/OrderBook.ts
- lib/service/Service.ts
This aims to remove some code duplication and make the `executeSwap` method in OrderBook.ts handle the required logic for when a swap we've initiated fails or succeeds.
> refactor(orderbook): reuse executeSwap code

- lib/Xud.ts
This intercepts SIGINT and begins the graceful shutdown process.
> feat: graceful shutdown on SIGINT

- lib/grpc/GrpcServer.ts
- lib/grpc/serverProxy.ts
There's no built-in support in grpc-node for interceptors. But I found a [package](https://github.com/echo-health/node-grpc-interceptors) which implemented a proxy to the server, so used its code. 
Other option is to log every request separately, but I wanted to avoid doing that. 
If the approach is acceptable, I can add better TS support.
> feat: grpc server logging

- docs/api.md
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.js
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/Service.ts
- proto/xudrpc.proto
- test/integration/Service.spec.ts
Closes #552.
This handles the possibility that we attempt to remove an order via the rpc layer while that order has a hold for a pending swap. Instead of removing the entire order immediately, this only removes the available portion of the order and then waits until any swaps finish before removing the portions that were on hold.
It also adds a field to the `RemoveOrder` rpc response which indicates whether any portion of the order was on hold. This gives feedback up front as to whether an order was removed immediately, or whether there are ongoing swaps which are being allowed to finish.
It also adds some assertions to the `removeOrder` logic to ensure that we don't try to remove any part of an order that is on hold.
>  feat(rpc/orderbook): handle remove order with hold

- lib/cli/commands/executeswap.ts
This fixes the argument names passed to the `ExecuteSwap` rpc call in the corresponding cli command.
> fix(cli): use correct args for executeswap

- lib/proto/annotations_pb.d.ts
- lib/proto/google/api/http_pb.d.ts
- lib/proto/google/protobuf/descriptor_pb.d.ts
- lib/proto/hash_resolver_pb.d.ts
- lib/proto/lndrpc_pb.d.ts
- lib/proto/lndrpc_pb.js
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- package-lock.json
- package.json
- proto/lndrpc.proto
This adds `jstype = JS_STRING` annotations on the channel ids in the lnd proto definition so that they use `string` types instead of numbers. Javascript does not natively support 64 bit numbers and precision can be lost, and the channel ids are known to cause issues because of this.
This also adds a new package to generate type definitions from the `.proto` files. This is because of a known bug in the previously used plugin, agreatfool/grpc_tools_node_protoc_ts#10, which does not update the generated type definition when `jstype = JS_STRING` is used.
I hit a wall with my first approach of generating code and type definitions using the [protobuf.js](https://github.com/dcodeIO/protobuf.js) package. I found out the hard way that does not support generating the grpc server/client code and …
> fix(proto): use 64 bit chan_id ints as strings

- lib/p2p/Parser.ts
- lib/p2p/packets/Packet.ts
- lib/p2p/packets/types/DisconnectingPacket.ts
- package-lock.json
- package.json
Solves #157.
As discussed [here](https://github.com/ExchangeUnion/xud/pull/712#issuecomment-445180853), the packet body serialization for the hash function is done with `JSON.stringify`. Lack of consistency in the serialization was already found, so I used `json-stable-stringify` to fix it. Without it the tests would fail.
> feat(p2p): verify data integrity

- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- lib/types/enums.ts
This adds `SwapFailureReason` values to cover every reason that a swap may fail. Previously we only set a string error message on swaps when they fail/error. The failure reason can be used to take different actions according to the reason, and is a clean way to categorize the reasons that a swap has failed.
Left to do is updating the swap failure packet to send the failure reason to a peer, and also to update the database to store the failure reason in its own field. But since these are breaking changes, I'm going to put these in a separate PR to be merged shortly before a new release.
Closes #671.
> feat(swaps): comprehensive SwapFailureReason

- lib/p2p/packets/types/HelloPacket.ts
- lib/p2p/packets/types/NodesPacket.ts
- lib/p2p/packets/types/OrdersPacket.ts
This uses the `every` Array method for arrays rather than `filter` to check that every object in a list within a packet passes validation. They function similarly but `every` does not create a new array, whereas `filter` does, so this cuts out an unnecessary step and may provide a very minor performance improvement.
> refactor(p2p): use every() to validate packets

- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/Packet.ts
- test/integration/Pool.spec.ts
- test/p2p/sanity.spec.ts
This includes several fixes I uncovered while trying to figure out what was causing #758, as well as logging enhancements to help debug p2p issues. Each commit has its own description, but the key one is the last one:
> This fixes a bug where the hash calculated for outgoing Order and Orders packets wouldn't match the calculated hash for the packet received by the peer due to the order objects being hashed having extraneous properties that are not transmitted to the peer, namely `hold` and `initialQuantity`.
I've tested the fix between two peers using this branch and they don't stall and disconnect from each other any more, but it would be helpful if we could try this on the seed nodes before merging.
Fixes #758.
> Fix peer stalling

- docs/api.md
- lib/cli/commands/executeswap.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- proto/xudrpc.proto
This call removes the `peer_pub_key` field from the `ExecuteSwap` request. This is not truly required information and it is inconvenient to have to provide, particularly from the cli. Finding which peer an order belongs to is not much of a performance concern.  It is constant time in regards to the number of orders and linear in regards to the number of peers.
Closes #694.
> feat(rpc): remove peerpubkey from executeswap

- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- test/integration/Pool.spec.ts
This adds logic to drop a peer's orders for a given trading pair when we receive an updated handshake state that does not include a trading pair that was supported according to the previous handshake. Without this, we may keep orders in our order book for a peer that no longer supports (and can swap) those orders.
Closes #599.
> feat(p2p/orderbook): drop orders for dropped pairs

- lib/db/DB.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/P2PRepository.ts
- tsconfig.json
This updates the typescript configuration to generate type declarations in the `dist` folder. This will allow typescript projects to use `xud` as a dependency.
> chore: generate type declarations

- lib/orderbook/OrderBook.ts
This is an attempt to fix #766. It removes an unnecessary step of converting an iterable to an array when iterating over the supported pair ids for removing peer orders.
> fix(orderbook): use pairs keys iterable

- lib/p2p/Pool.ts
- lib/p2p/packets/types/OrderInvalidationPacket.ts
This fixes a bug where the hash calculated for outgoing order invalidation packets wouldn't match the calculated hash for the packet received by the peer due to the order objects being hashed having extraneous properties that are not transmitted to the peer. This would cause the order invalidations to be ignored by the receiver.
Fixes #767.
> fix(p2p): hash order invalidations correctly

- lib/p2p/NodeList.ts
- lib/p2p/Peer.ts
- lib/p2p/packets/types/OrderInvalidationPacket.ts
- lib/types/enums.ts
- test/unit/Parser.spec.ts
* fix typing mismatch in order invalidation conversion return type
* fix the tests to be able to find such problems
* adding data integrity errors logging/penalization (taken from #756)
Still need to check if it actually solves #767 or that we have another problem.
> fix(p2p): order invalidation packet

- lib/db/models/SwapDeal.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/packets/types/SwapCompletePacket.ts
- lib/p2p/packets/types/SwapFailedPacket.ts
- lib/proto/xudp2p_pb.d.ts
- lib/proto/xudp2p_pb.js
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- lib/types/enums.ts
- proto/xudp2p.proto
- test/integration/Swap.spec.ts
- test/unit/Parser.spec.ts
This is a followup to #753 which includes breaking changes. Here's an overview of what it changes:
- Adds the `failureReason` field to the `SwapDeal` database model as well as the `SwapFailed` packet. It removes the `PeerFailedSwap` failure reason, and assigns swaps the failure reason specified by the peer in cases when the peer fails the swap. It adds a `PaymentHashReuse` reason which was missing to cover all current swap failure reasons.
- Tweaks the Parser tests to verify parsed packets with the
stable `stringify` method we use when hashing packets. This was done to
work around issues where the parsed packet did not deeply equal the
original packet because of the presence of an undefined `failureReason`.
- Renames the `errorReason` swap deal property to `errorMessage` to help …
> Swap failureReason field for SwapDeal db model and SwapFailedPacket

- lib/orderbook/OrderBook.ts
This is a fix for a bug introduced in #773 to persist the maker trade to the database before removing it from the order book.
> fix(orderbook): persist trade before remove order

- lib/swaps/Swaps.ts
This ignores any swap failed packets received for deals that are not active. Attempting to fail a completed deal would throw an assertion error that could crash `xud`.
> fix(swaps): ignore swap failed for inactive swaps

- lib/service/Service.ts
- lib/utils/uriUtils.ts
- lib/utils/utils.ts
- test/p2p/sanity.spec.ts
- test/unit/NodeKey.spec.ts
- test/unit/uriUtils.spec.ts
This allows for node connection uris without a specified port to be parsed and assigned a default port of 8885. This allows the port to be left off in the rpc `Connect` call when connecting to the default port.
>  feat: parse uri without port

- lib/proto/xudrpc.swagger.json
- proto/xudrpc.proto
This corrects overlapping http endpoint naming for the `SubscribeAddedOrders` and `SubscribeRemovedOrders` rpc calls.
> fix(rpc): subscribeorders http endpoints

- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- lib/types/enums.ts
This adds timeouts to all swap deals to fail them after a certain amount of time. Current time limits are set to 10 seconds for a swap to be accepted and 30 seconds for a swap to be completed once accepted. Previously, swaps that stalled out due to an unresponsive peer or swap client would last indefinitely and the corresponding order would remain on hold.
Closes #653.
> feat(swaps): timeout stalled swaps

- docs/api.md
- lib/cli/commands/streamorders.ts
- lib/cli/utils.ts
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.js
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/types/orderBook.ts
- proto/xudrpc.proto
This adds a `FailedSwap` message type to the asynchronous `PlaceOrder` rpc call. It is used to notify the caller in real time when a swap fails for a given order.
Closes #609.
Edit: Closes #734 as well I believe.
> feat(rpc): failed swaps for PlaceOrder

- tasks/config/sample.ts
- tslint.json
This adds a rule to enforce existing style in the codebase regarding whitespace before keywords like `else`, `catch`, and `finally` when they are on the same line as the closing brace for the previous block.
> style: add one-line tslint rule

- docs/api.md
- lib/cli/commands/streamorders.ts
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/OrderBookRepository.ts
- lib/orderbook/types.ts
- lib/proto/xudrpc.swagger.json
- lib/service/Service.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- proto/xudrpc.proto
- test/integration/OrderBook.spec.ts
- test/integration/Swap.spec.ts
This begins all swaps in parallel when placing/matching an order and retries failed swaps immediately. Any unmatched quantity is tracked and added to the orderbook (for limit orders) after matching and swaps are complete. Previously, swaps would execute one at a time and any failed quantity would wait to be retried until all first-attempt swaps completed. This should result in significantly faster order execution for orders that match with multiple peer orders and therefore require multiple swaps.
Closes #654.
> Execute swaps in parallel when matching orders

- lib/db/types.ts
This adds type definitions for the getter methods for database objects associated with `TradeInstances`, namely the maker & taker orders and swap deal.
> refactor(db): add getter types for TradeInstance

- lib/cli/commands/removeorder.ts
- lib/orderbook/OrderBook.ts
Fixes #804.
This fixes an unintentional assertion error when removing an order via the API where removing an order without specifying a quantity, which should remove the entire order, was instead removing none of it.
> fix(orderbook): remove entire order correctly

- lib/constants/enums.ts
- lib/orderbook/TradingPair.ts
- lib/p2p/NodeList.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/swaps/Swaps.ts
- test/integration/Swap.spec.ts
- tsconfig.json
- tslint.json
Closes #661.
This adds logic to handle swap failures according to the reason for the failure. Certain failures suggest a persistent, underlying issue with swaps for that peer and trading pair, and in this case we drop all orders for that peer and trading pair to avoid subsequent failures. We also penalize the peer for swaps that fail due to potential misbehavior or due to a timeout. Timeouts result in delays that degrade the trading experience moreso than regular swap failures.
> feat(swaps): define behavior for swap errors

- lib/orderbook/OrderBook.ts
This changes the `removeOwnOrder` method to pass on any exceptions it encounters rather than returning `true` or `false`. In all instances where the method is being used, the return value is ignored anyway and the expectation is that the order removal will succeed, so throwing exceptions when order removal fails will ensure errors are not unintentionally ignored.
> refactor(orderbook): throw error in removeOwnOrder

- docs/api.md
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/types.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- proto/xudrpc.proto
This adds a list of failed swaps to the `PlaceOrderSync` response to match the behavior of the asynchronous `PlaceOrder` call which returns information about failed swaps.
Solves part of #807.
> feat(rpc): add failed swaps to PlaceOrderSync

- lib/p2p/Peer.ts
This moves the logic for toggling the `opened` property of a peer to occur after the handshake is complete and verified. We rely on the `opened` property to determine whether we accept non-handshake packets, previously it would have been possible to accidentally accept all packets from a peer while the handshake was still ongoing.
> fix(p2p): toggle opened after handshake

- package-lock.json
This updates the nested `extend` dependency to address CVE-2018-16492.
> chore: update extend dependency

- lib/p2p/Pool.ts
This only logs messages that we've started and completed connecting to known nodes on startup when we have known, unbanned nodes to connect to.
> refactor: conditionally log init connections

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
This fixes a bug where `once` was being used instead of `on` to handle peer reputation events, meaning that only the first reputation event for a peer would actually update its score.
> fix(p2p): handle multiple peer reputation events

- lib/p2p/packets/types/OrderInvalidationPacket.ts
- lib/p2p/packets/types/OrderPacket.ts
This is a minor fix to the logic to validate an order packet, primarily checking that the `order.id` field is not empty. It also removes a duplicate check on the `id` header field and aligns the logic with the `OrdersPacket` validation which checks that `price` and `quantity` are not just non-zero but positive.
> fix(packets): correct order packet validation

- lib/orderbook/OrderBook.ts
- lib/p2p/Framer.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/swaps/Swaps.ts
- test/integration/Swap.spec.ts
- test/p2p/sanity.spec.ts
- test/unit/Parser.spec.ts
This replaces the synchronous usage of `crypto.randomBytes` with the asynchronous version when framing packets. The synchronous version can block the thread until enough entropy is collected. Since this is done every time an encrypted packet is sent, the delay may become noticeable.
This required rewriting synchronous code as asynchronous in several methods and tests which makes up the bulk of the code changes.
> perf(p2p): use async randomBytes for packet framer

- lib/p2p/Pool.ts
This fixes the way certain errors are logged when attempting to connect to peers. Previously it was possible to see messages like:
`[P2P] warn: could not open connection to peer (xud2.test.exchangeunion.com:8885): undefined`
This would occur when the `err` object in the catch block is a `string`. This change ensures we log `string` errors correctly.
> fix(p2p): peer error logging

- docs/api.md
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.js
- proto/xudrpc.proto
This fixes a bug in the way the `SwapSuccess` proto message was defined where `price` was set as an integer which is inconsistent with how `price` is defined for other messages and with how it is represented and being set internally. This caused the grpc response for the `PlaceOrder` and `ExecuteSwap` calls to be corrupt and fail due to an assertion error.
> fix(proto): set price as double

- lib/grpc/GrpcService.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/errors.ts
- test/integration/Pool.spec.ts
- test/p2p/sanity.spec.ts
This commit addresses an edge case bug whereby one peer finishes the handshake before the other and begins sending regular packets. It is possible for the other peer to attempt to process these regular packets while it is executing asynchronous code to complete the handshake, which results in the regular packets being discarded as "unsolicited."
The key change is marking the peer as `opened` after receiving and authenticating the `SessionInitPacket`, as well as validating the peer (not banned, not ourselves, not an incompatible version, etc...), but before we send the `SessionAckPacket`. This ensures that we are ready to accept packets before the peer is ready to send packets.
This involves restructuring the open flow, splitting it into two methods (`beginOpen` and `completeOpen`). The …
> fix(p2p): open peer before sending session ack

- lib/BaseClient.ts
- lib/Xud.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- test/integration/Swaps.spec.ts
This commit restructures the Swaps module to remove references to LndClient and instead use the BaseClient which can be either lnd or Raiden. This is in anticipation of interoperability between lnd and Raiden.
> refactor(swaps): remove lnd references from swaps

- lib/p2p/Peer.ts
This prevents an edge case bug where the TCP socket to a peer is destroyed as we are about to send data to that peer. This ensures that we check not only that a socket connection exists but that it also hasn't been destroyed. It also adds a try/catch block as a safety measure, since an unhandled error risks crashing the process.
Below is the log from the sort of error this is intended to prevent, note that the socket is closed only 2 milliseconds before responding to a ping packet with a pong packet.
```
19/03/2019 17:59:46.638 [P2P] debug: received disconnecting packet from 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a:{"reason":1,"payload":"482118c0-4a92-11e9-acfd-4d31407af072"}
19/03/2019 17:59:46.640 [P2P] error: Peer …
```
> fix(p2p): prevent writing to closed socket

- docs/api.md
- lib/BaseClient.ts
- lib/cli/commands/addcurrency.ts
- lib/constants/enums.ts
- lib/db/DB.ts
- lib/grpc/GrpcService.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/types.ts
- lib/p2p/Peer.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/raidenclient/RaidenClient.ts
- lib/service/Service.ts
- lib/swaps/Swaps.ts
- proto/xudrpc.proto
- test/integration/OrderBook.spec.ts
- test/integration/Service.spec.ts
- test/integration/Swaps.spec.ts
- test/unit/DB.spec.ts
This replaces the `Peer` `getLndPubKey` method with a generic `getIdentifier` method that will return either an lnd pubkey or a Raiden address. It also adds the raiden address to the `ListPeers` response.
This makes progress towards #797.
>  feat(swaps): get peer identifier for swaps

- test/p2p/sanity.spec.ts
This adds a test case that isolates a bug that was fixed in #845 where we would successfully connect to a peer that had banned us. Although that peer would immediately disconnect with us after establishing the connection, this was not evident to callers of the `Service.connect` method including the gRPC API. This test fails prior to the recent fix.
Closes #735.
> test(p2p): add connect test if we are banned

- lib/BaseClient.ts
- lib/Xud.ts
- lib/lndclient/LndClient.ts
- lib/p2p/Pool.ts
- lib/raidenclient/RaidenClient.ts
This detects if our raiden address changes between calls to `getAddress`. If so it updates peers of our new raiden address.
> feat(raiden): detect raiden address change

- lib/db/types.ts
- lib/orderbook/types.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/SessionAckPacket.ts
- lib/service/Service.ts
- lib/swaps/Swaps.ts
Remove unused imports and replace absolute module paths with relative.
> style: clean up imports

- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
This tweaks the logic around handling exceptions that arise from swap execution to ensure that the exception is a valid `SwapFailureReason` and to clarify the log messages and intent of the code. If the exception is not a `SwapFailureReason` we abort the matching procedure instead of repeating it for the failed amount.
> refactor(orderbook): throw error on non-swap fail

- test/simulation/actions.go
- test/simulation/go.mod
- test/simulation/go.sum
- test/simulation/xud_test.go
This fixes errors reported by `golint` and `go vet` in the simulation test golang code.
> style: fix golint errors in simulation tests

- lib/proto/xudp2p_pb.d.ts
- lib/proto/xudp2p_pb.js
- package.json
This is the result of running the `proto` npm script, which brings the p2p protobuf files up to date with the changes introduced in #869. It also removes the `proto:p2p` npm script and modifies the `proto` script for windows to generate the `p2p` protobufs. In Linux & Mac, the `proto` script already generated the `p2p` protobufs, so this adds consistency between platforms.
I had overlooked generating the p2p proto files and I'm hoping that combining the two into a single script that only needs to be run once will make that less likely to happen in the future.
>  chore: generate protobuf

- lib/lndclient/LndClient.ts
This fixes an oversight where we were leaving the `ClientStatus` for lnd as not initialized when it's actually disabled.
> fix(lndclient): set status disabled when disabled

- lib/Xud.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/NodeStateUpdatePacket.ts
- lib/p2p/packets/types/SessionInitPacket.ts
- lib/p2p/types.ts
- lib/raidenclient/RaidenClient.ts
- test/integration/Pool.spec.ts
- test/p2p/sanity.spec.ts
- test/unit/Parser.spec.ts
This PR refactors the `NodeStateUpdate` type and the logic around it to include all the fields from the `NodeState` type except those which should not change, namely `version` and `nodePubKey`. This is a follow-up to the fix in #876.
> refactor: NodeStateUpdate to include all fields

- .travis.yml
This disables the travis build for the current Node.js version (12.0.0) until all dependencies support it. See: https://github.com/grpc/grpc-node/issues/834
> chore: disable current v12 node travis build

- README.md
- test/simulation/README.md
`xud` Readme documentation fix:
* added slate
* updated typedoc link
* added node min version
`xud-simulation` readme fix:
* added `swap client (lnd/raiden) disconnected` case for order invalidation on network
> Readme documentation fix, xud-simulation readme addon

- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/service/Service.ts
This updates the SubscribeOrders call to notify clients when an own order is removed from the order book. Previously, removing an order via the RemoveOrder gRPC call would not send a message to SubscribeOrders callers.
> feat(rpc): removed own orders in SubscribeOrders

- lib/orderbook/OrderBook.ts
- lib/swaps/Swaps.ts
- test/simulation/tests.go
- test/unit/Swaps.spec.ts
This fixes a bug where the outbound capacity sanity check was comparing against the inbound currency and amount rather than outbound. In addition, this commit refactors & renames the methods used to calculate the amounts and currencies involved in a swap to minimize potential confusion. It also adds tests to detect a regression in the calculation logic.
Fixes #932.
> fix: switch swap capacity check currency

- .gitignore
- lib/p2p/packets/types/SwapFailedPacket.ts
- package-lock.json
- package.json
- tsconfig.json
This upgrades typescript to 3.4 to use its incremental build feature. This will speed up build times both locally and on travis by caching the dist directory and .tsbuildinfo file which is necessary for incremental compilation. It also makes the precompile script which deleted the dist folder obsolete.
> chore: incremental builds & typescript 3.4

- lib/Xud.ts
- lib/cli/commands/listorders.ts
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/OrderBookRepository.ts
- lib/p2p/NodeList.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/PongPacket.ts
- lib/raidenclient/RaidenClient.ts
- lib/service/Service.ts
- lib/swaps/Swaps.ts
- test/crypto/handshake.ts
- test/integration/OrderBook.spec.ts
- test/unit/DB.spec.ts
- test/unit/Swaps.spec.ts
- test/unit/uriUtils.spec.ts
- tsconfig.json
This enables the `noUnusedLocals` option for the typescript compiler and removes examples of unused local variables that violate the rule.
I've had a couple of times where I had to uncover bugs related to unused variables in testing that may have been caught earlier by this rule, and as the code base gets more mature I think this rule makes more sense. @erkarl expressed a similar sentiment I believe.
This drops the packet count and last sent/last received variables on `Peer`. We weren't using them, and I'm not sure there's much value in those any more (especially since the plans of the using the packet count for unique identifiers is long gone). Last sent & received I don't think tells us much useful information. I was thinking about maybe exposing the `bytesReceived` & `bytesSent` fields …
> refactor: enable noUnusedLocals tsconfig option

- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
This modifies the logic for determining which currencies to perform sanity swaps for. Previously, if a sanity swap failed for either currency in a trading pair, when that trading pair was retried we would retry sanity swaps for both currencies in the pair including the one that worked previously. This change tracks currencies for which we have had a successful sanity swap for and prevents retrying sanity swaps for that currency - until we encounter an error that deactivates a trading pair that includes that currency.
Fixes #946.
> fix(swaps): don't retry verified currency sanity

- test/simulation/xudtest/node.go
This preserves the log files generated from running the simulation tests within the simulation test temp folder. Data directories are also moved to the temp folder and are still cleaned up by default after each run, but separating and keeping the logs will help with diagnosing errors that arise during simulation test runs.
> test: preserve xud log files from sim tests

- .gitignore
- .travis.yml
- package.json
- test/simulation/README.md
- test/simulation/install.sh
- test/simulation/lntest/node.go
This modifies our Travis CI configuration to cache the go folder that holds lnd and its dependencies, such that we won't need to install lnd for each build and will reduce test run time significantly. This also moves the `go` folder out of the `temp` folder since this folder need not change unless the version of lnd we're using changes, and in that case the tests will reinstall lnd automatically. Even locally, keeping the go folder in between test runs will save time.
The install and simulation test scripts are modified to use the go folder created for the simulation tests as the only GOPATH value. This means all dependency modules and btcd are put in this folder and separated from the local go environment, preventing the possibility for conflicts and inconsistencies due to the …
> test: cache lnd & dependencies in travis

- test/integration/WebProxy.spec.ts
- test/p2p/networks.spec.ts
- test/p2p/sanity.spec.ts
- test/utils.ts
Closing #574.
Since avoid writing to disk isn't practical (it would require different code to be run for production and under test), a temp directory can be used instead.
> test: use os-specific temp dir as xudir

- lib/cli/command.ts
- lib/grpc/webproxy/GrpcWebProxyServer.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/errors.ts
- lib/p2p/Framer.ts
- lib/p2p/errors.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/Swaps.ts
- package-lock.json
- package.json
- tasks/config/sample.ts
- test/p2p/sanity.spec.ts
- test/unit/Parser.spec.ts
- test/unit/Swaps.spec.ts
This updates the tslint and related packages for more consistent linting and fixes newly detected lint errors. It also runs `npm dedupe` after updating the packages.
> chore: update tslint packages

- lib/p2p/Pool.ts
- lib/swaps/Swaps.ts
This adds a timeout for sanity that we have accepted and added an invoice for. If the time limit is exceeded, we remove the sanity swap and its corresponding invoice. This prevents invoices and sanity swaps that are stalled from accumulating, avoiding a potential memory leak.
Fixes #964.
> fix(swaps): remove stalled sanity swap invoice

- lib/Xud.ts
- lib/swaps/SwapClientManager.ts
- test/jest/SwapClientManager.spec.ts
This fixes the initialization logic for the raiden client and swap manager to load existing raiden currencies from the database.
This should fix the issue observed in xud-simnet where WETH sanity swaps are not being initiated.
> fix: load raiden token addresses from db

- lib/db/models/Order.ts
- lib/orderbook/OrderBook.ts
- lib/swaps/Swaps.ts
- test/unit/DB.spec.ts
- test/unit/Swaps.spec.ts
This fixes a bug where the calculated swap amount for a market buy order could be infinity. This could cause the sanity capacity check to fail when checking a market order. Market buy orders internally have a positive infinity price value for matching logic purposes, but the final price for market orders is not known upon first placing them.
Fixes #978.
> fix: calculate swap amount for market orders

- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- test/jest/Orderbook.spec.ts
This commit adds an `activatePair` public method for the `Peer` class and makes the `activePairs` property private. `activatePair` will both add a pair to the set of active pairs as well as request existing orders for that pair from the peer.
> refactor: make peer activePairs private

- lib/raidenclient/RaidenClient.ts
- lib/raidenclient/errors.ts
This improves the logging when requests to raiden fail with an HTTP 409 response. Previously only a generic error message was logged, here we parse the error response body and set it as the `message` for the error.
Closes #957.
> feat(raiden): log error message for 409 responses

- lib/Xud.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Pool.ts
- lib/p2p/types.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- test/integration/OrderBook.spec.ts
- test/integration/Pool.spec.ts
- test/jest/Orderbook.spec.ts
- test/jest/SwapClientManager.spec.ts
- test/simulation/tests.go
This fixes a bug where the swap clients would fail on their first attempt to initialize because they would try to update `pool.nodeState` which is undefined. `pool.nodeState` is not assigned a value until `pool.init()` is called, which would not happen until after the first attempt to initialize swap clients.
This changes the initialization flow so that the node state is assigned a value in the `Pool` constructor. The properties of `Pool.nodeState` are then updated as the other components (swap clients, order book)
initialize.
>  fix: swap client initialization

- lib/Xud.ts
- lib/orderbook/OrderBook.ts
- test/integration/OrderBook.spec.ts
- test/jest/Orderbook.spec.ts
This refactors the constructor for `OrderBook` to accept a single object rather than 6 parameters. This brings the constructor in line with other recently changed constructors/methods that accept 4+ parameters.
> refactor(orderbook): pass object to constructor

- lib/p2p/Framer.ts
- lib/p2p/Peer.ts
- lib/p2p/packets/Packet.ts
- lib/utils/utils.ts
- test/crypto/handshake.ts
- test/unit/Parser.spec.ts
When running XUD with Node `v10.16.0` (latest LTS) I got this deprecation warnings:
```
(node:7546) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:7546) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:7546) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
```
This PR removes them by not importing everything from `crypto` but just the functions that are needed.
> fix: deprecation warnings from crypto dependency

- lib/cli/commands/executeswap.ts
- lib/cli/commands/listorders.ts
- lib/cli/commands/removeorder.ts
- lib/cli/utils.ts
- test/unit/Command.spec.ts
This fixes edge case rounding errors when converting cli arguments like `2.3 * 100000000 = 229999999.99999997`. It creates conversion methods between coins and satoshis as well as unit tests for those methods.
Fixes #1015.
> fix(cli): quantity rounding

- lib/grpc/GrpcService.ts
- lib/lndclient/types.ts
- lib/service/Service.ts
- lib/swaps/SwapClientManager.ts
This fixes a bug where xud tries to read a property of `undefined` when an instance of `LndClient` is disabled. This refactors the code to use a `Map` when retrieving a mapping of `LndInfo` objects, and also calls `GetInfo` in parallel on all `LndClient`s.
Fixes #1011.
> fix: blockheight prop of `undefined` in GetInfo

- lib/http/HttpService.ts
- lib/raidenclient/types.ts
- test/jest/HttpService.spec.ts
- test/unit/HttpServer.spec.ts
raiden is using secrethash when invoking the resolver and not secret_hash
This is needed to resolve #986
> secrethash and not secret_hash

- bin/xud
- lib/Xud.ts
- lib/lndclient/LndClient.ts
- lib/lndclient/errors.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- test/jest/SwapClientManager.spec.ts
This fixes an issue where attempting a `GetInfo` call to lnd while lnd is locked results in an `UNIMPLEMENTED` grpc error that persists even after lnd has been unlocked and the `GetInfo` call becomes available. We close grpc clients after connection verification attempts so that we have a fresh start for future attempts
Fixes #1039.
>  fix(lndclient): unknown service lnrpc.Lightning

- lib/Logger.ts
- lib/lndclient/types.ts
- lib/swaps/SwapClientManager.ts
- test/jest/SwapClientManager.spec.ts
This adds an optional subcontext for loggers to print on every log statement. This is used in place of wrapping the log methods for the lnd loggers to display currency, but can also be reused in a generic fashion going forward.
Before:
```
19/06/2019 15:44:43.634 [LND] info: BTC: trying to verify connection...
```
After:
```
19/06/2019 15:44:43.634 [LND-BTC] info: trying to verify connection...
```
This is an offshoot of #1039.
> feat(logger): optional subcontext

- lib/raidenclient/RaidenClient.ts
- lib/raidenclient/types.ts
This updates the methods around querying channels to match the latest stable raiden API.
> refactor(raiden): update channel methods

- docs/api.md
- lib/orderbook/types.ts
- lib/proto/xudp2p_pb.js
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.js
- proto/xudp2p.proto
- proto/xudrpc.proto
This makes minor changes to our protobuf definitions files to use unsigned integers where appropriate, have consistent indentation, and clarify comments.
> refactor: proto definition cleanup

- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/NodeStateUpdatePacket.ts
- lib/p2p/packets/types/SessionInitPacket.ts
- lib/p2p/packets/utils.ts
- lib/p2p/types.ts
- lib/proto/xudp2p_pb.d.ts
- lib/proto/xudp2p_pb.js
- lib/raidenclient/RaidenClient.ts
- lib/service/Service.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
- lib/utils/utils.ts
- proto/xudp2p.proto
- test/integration/Pool.spec.ts
- test/jest/Orderbook.spec.ts
- test/jest/Pool.spec.ts
- test/jest/SwapClientManager.spec.ts
- test/p2p/networks.spec.ts
- test/p2p/sanity.spec.ts
- test/unit/Parser.spec.ts
At a high level, this adds a concept of a token identifier for each currency supported by xud that is consistent across the entire network.
NOTE: Although this is a breaking change in terms of the p2p messaging, I wound up implementing this without any changes to the database. We already store token addresses in the database, and the lnd chain is determined dynamically after we call `GetInfo`, so no db changes are made and there's no need to drop existing databases after this PR is merged.
"BTC" can mean mainnet tokens or testnet tokens (or simnet, etc...) and can even be misconfigured to point to the LTC lightning network. Meanwhile, Raiden ERC20 tokens refer to a particular token contract, and there's no guarantee that peers won't be using different (and therefore incompatible) …
> feat: token identifiers for currencies

- lib/orderbook/OrderBook.ts
This uses a named function called `checkPeerCurrencies` in place of an inline function for handling changes in a peer's advertised currencies from within the orderbook.
> refactor: checkPeerCurrencies

- lib/Xud.ts
This removes unnecessary code that created duplicate swap client managers and interfered with the graceful shutdown procedure.
> fix: clean shutdown

- lib/Config.ts
- lib/Xud.ts
- lib/grpc/GrpcService.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
- lib/orderbook/types.ts
- test/integration/OrderBook.spec.ts
- test/jest/Orderbook.spec.ts
Edit: Leaving #163 open to track future enhancements for thresholds.
@sangaman @kilrau The test are failing because of the thresholds I defined. 
Could you please give me default thresholds we should use?
Or should thresholds be disabled by default?
> Pairs thresholds

- docs/api.md
- lib/constants/enums.ts
- lib/db/types.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.js
- lib/raidenclient/RaidenClient.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- proto/xudrpc.proto
- test/integration/Swaps.spec.ts
- test/jest/Orderbook.spec.ts
- test/jest/RaidenClient.spec.ts
- test/unit/DB.spec.ts
- test/unit/Swaps.spec.ts
Fixes #1063.
This scales the `amountReceived`, `amountSent`, `makerAmount`, and `takerAmount` fields to always be denominated in satoshis, even for currencies where the smallest unit is smaller than  a satoshi. In their place this adds `takerUnits` and `makerUnits` to the `SwapDeal` type to track the amounts in each currency's base unit for sending & receiving.
This prevents errors on the rpc layer, where amounts in wei can easily exceed the limits of `int64`. It also prevents issues in storing these values in the database, where these fields are likewise represented as 64 bit integers.
This also renames several enum values to use the word "Payment" instead of "Amount" (as in "PaymentReceived") to avoid any possible confusion since "amount" is typically used to refer to a number.
> fix: swap sent/received amounts in satoshis

- lib/http/HttpService.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
This PR prevents Raiden from being first leg of swap.
It better calculates the maker CLTV by using cltv-delta of 5760 in the case of raiden.
This is only a basis for a better change
> Prevent Raiden from being first swap leg

- lib/raidenclient/RaidenClient.ts
- lib/service/Service.ts
- lib/swaps/SwapClient.ts
- test/jest/RaidenClient.spec.ts
Closes #1051.
Note: This is based off of #1064.
This modifies the logic around querying raiden for channel balances. Rather than summing up all balances across all tokens, it allows for specifying a currency and retrieving only the balance for that currency. Calling `ChannelBalance` without specifying a currency will return each currency separately.
It also scales the balance returned by raiden to satoshis (10^-8). This is because the default units of 10^-18 for currencies such as WETH can exceed the maximum value of a `uint64` used by the gRPC layer.
> feat(raiden): channel balance by currency

- bin/xud
- lib/Config.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
- lib/raidenclient/RaidenClient.ts
- lib/raidenclient/types.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
- test/jest/RaidenClient.spec.ts
- test/jest/SwapClientManager.spec.ts
- test/jest/integration/Swaps.spec.ts
Closes #1027.
This adds logic to check that we have a direct channel with a peer before enabling trading for a given Raiden token. Currently multi-hop Raiden payments are not well supported, and this will prevent any attempts to swap Raiden tokens without a direct channel.
Note, this branch is based off of #1055 (which has useful refactoring for determining whether to disable specific currencies trading) and #1064 (which updates raiden calls used in this PR) so it must be rebased and merged only after those two PRs are merged. The key commit to review for the purposes of this PR is the last one.
> feat(raiden): check for direct channels

- lib/cli/commands/channelbalance.ts
This formats the output of the `channelbalance` xucli command. It prints one currency's balance per line and converts the satoshi amounts provided by the rpc response into whole units as so.
```
$ xucli channelbalance
12.5 BTC
0 DAI
1125 LTC
0 WETH
```
> feat(cli): formatted channelbalance output

- lib/raidenclient/RaidenClient.ts
Reverts ExchangeUnion/xud#1103
`channel.balance` is in units, so we should not be converting to amount.
> Revert "fix(raiden): getRoutes amount comparison"

- lib/p2p/seeds/testnet.ts
Cloud instance was not responsive, had to reinstall - nodepubkey changed.
Tested locally.
> fix: testnet seed node pubkey update

- lib/utils/UnitConverter.ts
This prevents unwanted fractional values from the `unitsToAmount` method return value.
Fixes #1097.
> fix: round unitsToAmount conversion result

- lib/Xud.ts
- lib/grpc/webproxy/GrpcWebProxyServer.ts
- lib/p2p/NodeList.ts
- lib/p2p/Pool.ts
This commit shuts down `xud` when there is an unexpected error during initialization. Allowing it to continue could result in an unexpected or undesirable state without the user being aware. Shutting down prompts the user to investigate and correct the error before restarting.
> feat: shutdown xud on error during init

- lib/constants/enums.ts
- lib/orderbook/OrderBook.ts
- lib/swaps/SwapRepository.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- test/jest/integration/Swaps.spec.ts
- test/unit/DB.spec.ts
This commit persists the state of swap deals to the database upon each phase change once a deal has been accepted to. This is done to be able to prevent loss of funds and recover gracefully from any active swaps should `xud` crash unexpectedly.
This is the first step towards closing #1079.
I wound up leaving the existing phases as is, and just updated the comments instead and renamed `SwapAgreed` to `SwapAccepted` to align with our terminology elsewhere. I started adding separate phases for maker/taker but it would've required changing quite a few lines of code, and ultimately for recovery purposes we can determine the precise state by looking at both `phase` and `role`.
> feat(swap): persist active swap deals to db

- lib/p2p/P2PRepository.ts
- lib/p2p/Pool.ts
- test/integration/Pool.spec.ts
- test/jest/Pool.spec.ts
Closes https://github.com/ExchangeUnion/xud/issues/1091
After thinking a little bit about it I am of the opinion that only checking whether the address belongs to itself when trying to connect is sufficient. All other checks could cause weird edge cases and inconsistent behaviors and that single check is enough to fix the issue.
> feat: not connecting to its own addresses

- test/simulation/xudrpc/README.md
This removes the command to install `protoc-gen-swagger` from the simulation tests protobuf generation instructions since it is not used.
> docs(sim tests): don't install protoc-gen-swagger

- bin/xud
- lib/Config.ts
- lib/http/HttpService.ts
- lib/lndclient/LndClient.ts
- lib/lndclient/types.ts
- lib/p2p/packets/types/SwapAcceptedPacket.ts
- lib/raidenclient/RaidenClient.ts
- lib/raidenclient/types.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- test/jest/HttpService.spec.ts
- test/jest/LndClient.spec.ts
- test/jest/RaidenClient.spec.ts
- test/jest/SwapClientManager.spec.ts
- test/jest/integration/Swaps.spec.ts
Closes #1052. This is a followup of #1072 and builds off of the commit in that PR. I decided to split this into a separate PR because the logic is fairly complex to me and I felt it would greatly expand the scope of the original PR.
This refines the logic to determine whether a Raiden payment on the first leg of a swap (taker to maker) extends sufficient cltv delay according to the maker's specified minimum cltv delay.
This also checks the `token` field of a Raiden resolve request to ensure that it matches the expected token address for the deal. It also improves calculation of the `cltvDeltaFactor` to use hardcoded values for the average time per block for each chain, rather than using the configured cltv delays for each currency. Changing the configured values from the defaults could …
>  feat(raiden): check cltv delay 

- lib/p2p/Peer.ts
This PR fixes a bug described in https://github.com/ExchangeUnion/xud/issues/1136.
I used expectedNodePubKey field of Peer class to get and display the value of pubkey.
Just an observation note: in my opinion the fact that the nodePubKey field of the same class has a value only when the connection is established is a bit unintuitive.
Closes #1136.
> Add xud pubkey to reconnection log message

- lib/db/seeds/testnet.ts
The former one (https://ropsten.etherscan.io/token/0x6d56f1c68356a147897d4f9a3dc63b97a275b8fa) only has 100 DAI supply, whereas Kyber's https://ropsten.etherscan.io/token/0xad6d458402f60fd3bd25163575031acdce07538d has a bit more and is actively in use.
As per https://ropsten-api.kyber.network/currencies.
> fix: change dai ropsten contract to kyber dai ropsten contract

- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClient.ts
This adds a timeout to the initialization procedure for swap clients. Previously, initialization would wait for as long as it took to receive a response from the client. In cases where raiden or lnd hangs on the response, xud would hang as well.
Now, xud will wait a fixed time limit before proceeding with initialization, leaving the client in a not connected state. The swap client will be marked as connected if and when we get a successful response.
> feat(swapclient): add timeout to initialization

- lib/db/seeds/simnet.ts
Offer just reset the simnet and created new tokens on it. Because of that we need to update the default simnet currencies in XUD.
> fix: update simnet token addresses

- lib/lndclient/LndClient.ts
- lib/swaps/SwapClient.ts
This fixes a bug where the first attempt to verify a connection to lnd would fail on the first attempt due to the `deadline` of 0 for the `waitForReady` being exceeded immediately with the latest version of lnd. Subsequent attempts would not exceed the deadline.
Instead, this always uses a deadline of infinity meaning xud will always wait for lnd to be online before it attempts a `GetInfo` call to verify the connection. This leverages the recently added `verifyConnectionWithTimeout` logic to timeout the initial connection verification if lnd remains offline so that it doesn't hold up the xud initialization procedure.
I've tested this both in the case of lnd being online when xud starts and lnd being offline and it works as expected in both cases.
> fix(lnd): waitForReady infinite deadline

- lib/p2p/Peer.ts
- test/p2p/networks.spec.ts
- test/p2p/sanity.spec.ts
- test/simulation/tests-integration.go
This modifies the log messages to print the expected pub key of a peer (when we have one as is the case on outbound connections) along with the peer's address before we have completed the handshake with that peer. After the handshake, we log only the peer's pub key.
> feat(p2p): log peer's expectedpubkey

- docs/api.md
- lib/grpc/GrpcInitService.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/InitService.ts
- lib/swaps/SwapClientManager.ts
- proto/xudrpc.proto
This adds the list of lnd clients that were initialized or unlocked by an `InitNode` or `CreateNode` call to their respective responses. This can be used to display potentially helpful information to the user.
Closes #1018.
> feat(initservice): return list of wallets

- lib/swaps/Swaps.ts
This fixes a bug where we would attempt to set a swap as successful after it had errored due to a send payment failure.
Fixes #1155.
> fix(swaps): prevent crash on send payment failure

- lib/swaps/SwapClientManager.ts
- test/jest/__snapshots__/SwapClientManager.spec.ts.snap
Linked issue: https://github.com/ExchangeUnion/xud/issues/1133
I replaced the suggested "not connected to peer X" with "peer not connected to swap client" as this seemed to be a little bit more precise. As peer's nodePubKey is already mentioned in the same row, I suggest to omit it from the message.
> chore: change openchannel error message

- lib/grpc/GrpcService.ts
- lib/p2p/Peer.ts
Fix for https://github.com/ExchangeUnion/xud/issues/1129
xud was crashing because GrpcService::getGrpcError requires an error object that should have code and message properties, but got a string instead.
> fix(p2p): prevent xud from crashing when connecting to peer times out

- lib/db/types.ts
- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- test/jest/LndClient.spec.ts
- test/jest/integration/Swaps.spec.ts
- test/utils.ts
Fixes #1158.
This fixes a bug whereby the `makerCltvDelta` was erroneously used for the `cltvLimit` for the payment from maker to taker. `makerCltvDelta` is irrelevent to the payment to the taker. Instead, this value is set to the time lock of the route found from maker to taker for lnd, raiden currently has no equivalent to `cltvLimit`.
In tests, payments would still fail occasionally due to no route found. Adding 3 blocks to the `cltvLimit` value consistently resolved these failures - any fewer than 3 and the payments would still fail. More investigation is warranted into why this is necessary, it's possible that there is a bug in the `cltvLimit` implementation within lnd.
This fix makes the new multihop simulation test case in #1160 pass.
> fix(swaps): set cltvLimit correctly

- test/simulation/README.md
- test/simulation/actions.go
- test/simulation/lntest/harness.go
- test/simulation/tests-integration.go
- test/simulation/xud_test.go
This adds a simulation test case for multi-hop swaps. Pairs of LTC & BTC channels are established between Alice & Bob, Bob & Carol, and Carol & Dave. Then a swap is performed between Alice & Dave.
This also modifies the channel setup to use a single channel with balance on both sides rather than two unbalanced channels to better resemble how channels are constructed during live usage.
> test: multi-hop sim test

- npm-shrinkwrap.json
- package.json
This updates typedoc to fix incompatibilities with typescript 3.5.x and vulnerabilities detected by `npm audit`.
> chore: update typedoc

- lib/constants/enums.ts
- lib/lndclient/LndClient.ts
- lib/swaps/Swaps.ts
- lib/swaps/errors.ts
- test/jest/__snapshots__/LndClient.spec.ts.snap
This improves the way swap errors are communicated between participants of a swap. Previously, any error during an attempt to send payment was communicated to the peer via a `SwapFailedPacket`. However, in cases where the maker to taker (2nd leg) payment fails, the maker will reject the 1st leg payment because they were unable to acquire the preimage. This results in two near-simultaneous payment errors on both peers, who send `SwapFailedPacket`s to each other for already failed deals which results in an undesirable `received swap failed packet for unknown deal` log messages.
This change detects an lnd payment that failed due to being rejected (`UnknownPaymentHash` error message) and skips sending the `SwapFailedPacket`. Instead it fails the swap due to a new `RemoteError` swap failure …
> feat(swaps): improved remote error handling

- test/simulation/go.mod
- test/simulation/go.sum
- test/simulation/lntest/node.go
- test/simulation/xudtest/node.go
This dynamically selects unused ports for the lnd and xud nodes used during the simulation tests. This should reduce the likelihood of tests failing due to other running processes on the machine.
> test: use dynamic ports for simulation tests

- lib/grpc/serverProxy.ts
The repository we're using code from for the grpc server proxy recently added a license, so I've added it to the header of the file that's based off of that repository. See https://github.com/echo-health/node-grpc-interceptors/issues/16.
> docs: add grpc server proxy license

- lib/Xud.ts
- lib/grpc/GrpcServer.ts
This fixes a bug whereby xud will not shutdown gracefully while it is waiting to be unlocked.
> fix: allow graceful shutdown while awaiting unlock

- lib/Xud.ts
- lib/lndclient/LndClient.ts
- lib/nodekey/NodeKey.ts
- lib/service/InitService.ts
- lib/swaps/SwapClientManager.ts
This fixes the logic around initializing `LndClient` for a new lnd instance (before wallet creation) and new xud instance (before node key creation). The lnd macaroon file is not created until after its wallet is created, so we relax the check that disables the client if a macaroon is not found during initialization. Instead, we mark the client as `WaitingUnlock` and wait for a successful xud `CreateNode` call to initialize the lnd wallet. After we've successfully loaded the admin macaroon, we then continue with attempting to verify the connection.
I've tested this manually and the create & unlock calls are now interacting with lnd as expected.
> fix(lnd): wait for macaroon before wallet created

- lib/cli/commands/create.ts
- lib/cli/commands/unlock.ts
This prompts the user for a password without displaying it on the screen or saving it to the command history for the `CreateNode` and `UnlockNode` calls via the cli.
The wording for the prompts is currently pretty basic, I'm open to suggestions on how to make it more comprehensive or clear.
> feat(cli): hide password input

- .gitignore
- lib/service/Service.ts
- package.json
- parseGitCommit.js
Closes #1171 
I created a new script (`parseGitCommit.js`) that will be executed before the `compile` NPM script. It parses the latest git commit hash (if that commit doesn't also tag a release) and whether there are uncommitted changes in the working directory and writes a corresponding string into `lib/Version.ts`.
For example the `version` in `xucli getinfo -j` could look like: `1.0.0-testnet.1-9a03442c-dirty`
> feat: show git commit hash in version

- lib/swaps/Swaps.ts
This is a minor fix for logging the swap failure error message. The logic on whether to log the error message was backwards, logging it only when undefined.
> fix: log error message reason correctly

- lib/p2p/Peer.ts
- test/jest/Peer.spec.ts
This fixes a bug with how peers were labeled in the logs. The ternary operator that determined whether to log the pub key or the address was not evaluating as expected. This also adds test cases to prevent regression bugs in the future.
@kilrau This fixes the `undefined` you were seeing when peer pub keys were being logged.
> fix(peer): logging label/node pub key

- docs/api.md
- lib/cli/commands/balance.ts
- lib/grpc/GrpcService.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.d.ts
- lib/proto/xudrpc_grpc_pb.js
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/Service.ts
- proto/xudrpc.proto
First step for solving https://github.com/ExchangeUnion/xud/issues/1062
> refactor(rpc): rename channelbalance to balance

- docs/api.md
- lib/cli/commands/create.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_grpc_pb.js
- proto/xudrpc.proto
Closes #1210.
This improves the output of the `xucli create` command to provide clearer information to the user about how they should proceed and the outcome of the command.
Below is sample output:
```console
$ ./xucli create
You are creating an xud key and underlying wallets secured by a single password.
Enter a password: 
Re-enter password: 
----------------------BEGIN XUD SEED---------------------
1. able        2. desk        3. online      4. that      
5. skill       6. clap        7. color       8. this      
9. figure     10. cage       11. torch      12. main      
13. screen     14. angle      15. hour       16. sail      
17. zoo        18. off        19. push       20. ancient   
21. bubble     22. pitch      23. involve    24. endless   
-----------------------END XUD …
```
> feat(cli): enhance create output

- lib/cli/commands/getbalance.ts
As per discussion in https://github.com/ExchangeUnion/xud/pull/1180, the `balance` command is renamed as `getbalance`.
> refactor(cli): rename balance to getbalance

- lib/lndclient/LndClient.ts
- lib/lndclient/types.ts
This restricts the `unaryCall` functions to only accept supported method names for their respective client. Previously it was possible to pass arbitrary strings as the method name to `unaryCall`.
> refactor(lndclient): strict method types

- lib/Config.ts
- lib/Xud.ts
This commit makes `xud` exit during initialization if it encounters a config file that cannot be parsed properly as TOML. Previously, `xud` would silently error due to any syntax error in the config file and start up without any of settings from the file, potentially leading to confusion and unintended actions.
> feat(config): exit on invalid config file

- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClient.ts
- lib/swaps/Swaps.ts
- test/integration/Swaps.spec.ts
- test/jest/integration/Swaps.spec.ts
This refactors the `getRoutes` call to `getRoute` to match the behavior of lnd which only returns a single route at most for the `QueryRoutes` call.
> refactor(swaps): change getRoutes to getRoute

- docs/api.md
- lib/Xud.ts
- lib/cli/commands/getinfo.ts
- lib/constants/enums.ts
- lib/lndclient/LndClient.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/raidenclient/RaidenClient.ts
- lib/raidenclient/types.ts
- lib/service/Service.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapRecovery.ts
- lib/swaps/Swaps.ts
- package.json
- proto/xudrpc.proto
- test/jest/RaidenClient.spec.ts
- test/jest/SwapRecovery.ts
- test/simulation/harnessTest.go
- test/simulation/tests-instability.go
- test/simulation/xud_test.go
- test/simulation/xudtest/harness.go
- test/simulation/xudtest/node.go
Closes #1079 & #1183. This builds off of PR #1080.
This commit attempts to recover swap deals that were interrupted due to a system or `xud` crash. In the case where we are the maker and have attempted to send payment for the second leg of the swap, we attempt to query the swap client for the preimage of that payment in case it went through. We can then use that preimage to try to claim the payment from the first leg of the swap. In all other cases, we simply attempt to close any open invoices and mark the swap deal as having errored.
Raiden currently does not expose an API call to query for the preimage of a completed payment. Any pending swaps are listed in the `GetInfo` response.
The recovery attempts happen once on `xud` startup by looking for any swap deals in the database that have …
> feat(swaps): recover crashed swap deals

- lib/swaps/SwapClientManager.ts
This fixes the error handling around the call to `genSeed` to actually catch errors thrown from the method. Previously, the method returned before any error could be caught.
> fix(swapclientmanager): catch genseed errors

- lib/constants/limits.ts
This modifies the order size limits for all currencies to equal approximately $10 USD for use on mainnet.
Closes #1230.
> feat: $10 mainnet order size limits

- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClient.ts
This commit shortens the interval for the outbound capacity check timer from 60 to 3 seconds and sets the client as disconnected any time a call fails due to an unreachable server. This makes the capacity checks act like a heartbeat, checking that the server is reachable every few seconds even in the absence of any other activity.
Previously, we had used a dummy server -> client streaming call and listened for the `error` event on the lnd side, however with newer versions of lnd and grpc this is no longer a reliable way to tell when lnd has gone down.
This also closes #1090 where lnd would get stuck in the `WaitingUnlock` state if it is stopped while xud is running and comes back online in the locked state.
> feat(swapclient): heartbeat

- lib/lndclient/LndClient.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- test/jest/SwapClientManager.spec.ts
This adds a `locked` event to `LndClient` which is emitted when the client transitions to `WaitingUnlock` status. If `xud` is using a master password, it will attempt to unlock lnd when it handles the `locked` event.
Closes #1196.
> feat(lnd): automatically unlock wallet on restart

- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClient.ts
- test/jest/RaidenClient.spec.ts
This modifies the logic around updating the maximum outbound capacity for a swap client to occur every time the channel balance is fetched, regardless of whether `channelbalance` was called by the timer to periodically update capacity or via an `xud` gRPC request. This will give us slightly more up-to-date cached balance values without needing to make any additional calls to the swap clients.
> feat(swapclient): update capacity on channelbalance

- lib/cli/command.ts
This sets an exit code of 1 on errored calls to indicate failure and differentiate from the default successful exit code of 0.
> feat(cli): set exit code 1 on errored calls

- lib/swaps/SwapClient.ts
Closes #1240.
This fixes the logic around rescheduling reconnection attempts to ensure that they continue should the previous attempt to verify the connection fail.
> fix(swapclient): continue reconnection attempts

- bin/xud
- lib/Config.ts
- lib/cli/commands/create.ts
- lib/grpc/GrpcInitService.ts
- lib/raidenclient/types.ts
- lib/service/InitService.ts
- lib/swaps/SwapClientManager.ts
- lib/utils/seedutil.ts
- seedutil/README.md
- seedutil/SeedUtil.spec.ts
- seedutil/main.go
- test/jest/RaidenClient.spec.ts
- test/jest/SwapClientManager.spec.ts
Closes #1242.
This commit uses the seed generated during the `CreateNode` call to create the raiden/ethereuem keystore along with the lnd wallets. This is the final step to having a single recovery seed and a single encryption password for all lnd and raiden wallets.
A new configuration option `raiden.keystorepath` specifies where xud should create the keystore directory. 
@reliveyy You should pass in this new option to `xud` when creating the wallets in docker. We will still need to figure out the best approach to ensuring the seedutil binary is available through non-docker installations. For dev/testing purposes if you have Go installed you can just use `npm run compile:seedutil`.
> feat: create eth keystore with master seed

- lib/p2p/Peer.ts
This adds a space between the peer's label and the word "failed" in the logging output.
> fix: reconnect log message

- lib/swaps/SwapRecovery.ts
- lib/swaps/Swaps.ts
Closes #1251.
This adds logic to track recovered swap preimages for claiming raiden payments. A proposed change to raiden has it continuously attempt to resolve a hash until it gets a response - if xud crashes during or before the first attempt then raiden will continue trying until xud comes back online. When it does, xud will check if it has recovered the preimage and return it to raiden if so, effectively claiming the payment and preventing loss of funds.
> feat(swaps): raiden claims recovered swap payments

- lib/grpc/GrpcInitService.ts
- lib/grpc/GrpcServer.ts
- lib/grpc/GrpcService.ts
- lib/grpc/getGrpcError.ts
- lib/lndclient/LndClient.ts
- lib/lndclient/errors.ts
- lib/orderbook/OrderBook.ts
- lib/raidenclient/RaidenClient.ts
- lib/service/InitService.ts
- lib/service/Service.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
- lib/swaps/errors.ts
- test/unit/HttpServer.spec.ts
Closes #1252.
This makes the `CreateNode` call wait briefly for all enabled lnd clients to become available. If any lnd clients remain unavailable, the call returns an error.
I did some refactoring around the way grpc errors are handled and logged as well in separate commits.
I'll open a separate issue to track a new status besides `Disabled` for when an lnd client is enabled by the config but is dysfunctional due to an unrecoverable error such as no tls cert or macaroon found.
> feat: wait for lnd on create call

- lib/db/seeds/testnet.ts
This commit updates the public key and listening uris of our testnet
node that has been migrated to latest docker changes.
In addition I changed DAI and WETH contract addresses to EIP55 format
since it was causing xud's channelbalance calls to fail.
> chore: update testnet seeds

- lib/p2p/Pool.ts
This fix prevents the p2p pool from accepting or initiating new connections while it is closing or after it has closed. This prevents the possibility for race conditions which was affecting the Pool test suite.
> fix: don't allow new connections while pool closes

- package.json
This runs the full suite of simulation tests before tagging a new version, which also runs the `compile` script that it's replacing.
> chore: run sim tests on version

- lib/p2p/Peer.ts
This logs the reason we received a `DisconnectingPacket` as its enum value such as `Banned` instead of its numerical value such as `7`.
Closes #1267.
> feat(p2p): log disconnection packet reason enum

- .gitignore
- package.json
- tsconfig.json
When one executes `rm -r dist` and runs `npm run compile` afterwards the compilation did not work because the `.tsbuildinfo` file was not located in the dist folder.
This PR moves the file into the `dist` folder while still ignoring it when packing the tar archive that is published to NPM.
> chore: move .tsbuildinfo to dist folder

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
This removes the `error` event from `Peer`. Previously it was only used to log the error from the listener in `Pool`, however this was unnecessary and instead the logging can be done directly from `Peer`.
This simplifies the code and also resolves a mysterious crash condition where an unhandled error from `Peer` would crash xud after a failed inbound connection & timeout via tor.
Closes #1129 - the same issue addressed by https://github.com/ExchangeUnion/xud/pull/1291.
This also includes several changes made in the course of trying to debug/resolve the aforementioned crash. Although they didn't resolve the issue, I still consider them useful refactoring/cleanup of existing p2p code.
> fix(p2p): remove error event from Peer

- lib/lndclient/LndClient.ts
- lib/swaps/SwapClient.ts
> fix: show LND info while it is out of sync

- lib/Xud.ts
- lib/grpc/getGrpcError.ts
- lib/lndclient/LndClient.ts
- lib/service/InitService.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/errors.ts
- test/jest/SwapClientManager.spec.ts
Closes #1287 using the approach described below:
> 1. Wait briefly for tls.cert to be created if it is not found immediately upon start and this is the first time xud is being run (pending the create call).
> 
> 2. Fail all calls to create xud if we have a client enabled in the configuration but which could not be initialized.
> feat(rpc): create error if clients misconfigured

- lib/Xud.ts
- lib/cli/command.ts
- lib/grpc/GrpcInitService.ts
- lib/grpc/GrpcServer.ts
- lib/grpc/GrpcService.ts
- lib/service/InitService.ts
- lib/service/Service.ts
This changes the xud initialization procedure to start the grpc server immediately and have it return an `UNAVAILABLE` error with the message 'xud is starting' until all components have finished initializing and xud is ready to handle rpc calls. It also enhances the xucli output somewhat in cases where xud is locked or starting.
Closes #1258.
> feat(rpc): notify when xud is starting

- test/jest/toEip55Address.spec.ts
This adds a test case for the recently added `toEip55Address` method.
> test: toEip55Address example test

- bin/xud-backup
- lib/Logger.ts
- lib/backup/Backup.ts
- lib/lndclient/LndClient.ts
Closes #917 
This PR adds `xu-backup` that starts listening for new LND SCBs and writing them to the disk when executed.
I am not finished yet and have some things to do before this backup daemon can be used but please have a look at this PR nevertheless to acknowledge the concept and give me some feedback on what I have been doing in this branch. 
Todo:
@kilrau we agreed on not implementing a restoring feature for now, right?
> feat: add backup daemon

- npm-shrinkwrap.json
- package.json
This updates the `grpc` dependency to add compatibility with Node.js v13. It also updates the `grpc-dynamic-gateway` dependency to align with the grpc version used by xud.
> chore: update grpc dependency for node v13

- lib/p2p/NodeList.ts
- lib/p2p/P2PRepository.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- test/integration/Pool.spec.ts
- test/jest/Pool.spec.ts
- test/unit/DB.spec.ts
Closes #1309.
This commit makes several changes to address potential race conditions in the case where two peers attempt connections to each other simultaneously.
The key fix is that the p2p pool no longer prunes recently closed peers from the list of active peers by node pub key alone. This could result in scenarios where a pending connection that is closed causes an active connection to be discarded. Instead, only peers that are active get removed from the list when they are closed. Additionally, pending outbound and inbound peers are no longer removed from their respective lists upon the peers being closed. Rather, the `addOutbound` and `addInbound` methods - which currently add pending peers to their lists - now also remove peers from the list if they are no longer pending.
The …
> fix(p2p): handshake race conditions

- lib/orderbook/OrderBookRepository.ts
- test/unit/DB.spec.ts
This refactors the `addOrderIfNotExists` method to correctly follow its behavior in the method comments by returning the created node and to use only a single db query.
> refactor(db): addOrderIfNotExists

- lib/p2p/Peer.ts
This refactors the code to send packets to peers to check if a socket exists immediately before transmitting. It prevents edge case errors where a socket is destroyed immediately before transmission while the packet data is being framed.
> refactor(p2p): check socket on send

- test/simulation/xudtest/node.go
This further extends the wait before the context times out to prevent test flakiness.
Testing this on Travis has had pretty good results so far.
> test(simulation): extend context wait time

- docs/api.md
- lib/cli/commands/unlock.ts
- lib/grpc/GrpcInitService.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/InitService.ts
- lib/swaps/SwapClientManager.ts
- proto/xudrpc.proto
This adds a response parameter for the `UnlockNode` call to include a list of enabled wallets that could not be unlocked. It also uses the existing `waitForLnd` method to wait briefly for lnd clients to come online which will help ensure lnd gets unlocked in cases where it is started near simultaneously with xud. Finally it enhances the `xucli unlock` output.
Closes #1319.
> feat(rpc): unlock returns list of locked wallets

- lib/lndclient/LndClient.ts
- lib/swaps/Swaps.ts
- test/jest/integration/Swaps.spec.ts
This adds a buffer to the `takerMaxTimeLock` equal to our `finalLock` value, which by default is 40 blocks on BTC, which may open the possibility of using alternate routes with slightly longer lock times should payment using the first route we found fail.
Closes #1165.
> feat(swaps): add flexibility to second leg route

- bin/xud
- lib/Config.ts
- lib/Xud.ts
- lib/constants/limits.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
- sample-xud.conf
- test/integration/OrderBook.spec.ts
- test/unit/TradingPair.spec.ts
This adds a new `maxlimits` config option that overrides the hardcoded mainnet limits when set to true. In place of the mainnet limits, the maximum channel size for a currency's respective network is used as the maximum order size. These higher limits are now also enforced on non-mainnet networks regardless of the `maxlimits` value.
Closes #1304.
> feat(config): add maxlimits options

- lib/cli/commands/streamorders.ts
- lib/cli/placeorder.ts
This sets a handler for the error event with streaming gRPC calls to explicitly set the exit code to 1 and log a tidier message, similar to what we do with regular request/response calls.
> refactor(cli): handle stream error event

- lib/backup/Backup.ts
- lib/lndclient/LndClient.ts
This makes the backup process begin listening or watching for channel and database changes asynchronously, instead of one at a time. It also handles the case where a database file does not yet exist at the time the backup process is started by waiting for it to be created.
It also changes the way the backup process is notified when an lnd client becomes connected again from checking on an interval to listening to the `connectionVerified` event which provides immediate notification.
> refactor: asynchronous backup

- lib/cli/command.ts
This fixes the cli output to only print the `could not connect to xud` message when `UNAVAILABLE` errors result from actually not being able to reach xud, as opposed to when particular calls are services within xud are unavailable such as lnd being disconnected.
Fixes #1371.
> fix(cli): print UNAVAILABLE errors correctly

- lib/swaps/SwapClientManager.ts
This fixes the clients that get added to the `lockedLnd` list in the `UnlockNode` response. Previously, lnd clients that were already unlocked were added to this list. This makes it so those are not added, instead only clients where the unlock call fails or those where the call can't be made are added to the list.
> fix(rpc/lnd): lnd already unlocked

- test/jest/NodeKey.spec.ts
This fixes an edge case failure where `allocUnsafe` returns 32 bytes of zeroes, causing a test case to fail.
> test: fix nodekey edge case

- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
- lib/service/InitService.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
This ensures that misconfigured SwapClients get closed properly when xud is shutdown.
> refactor: close misconfigured SwapClients

- lib/Xud.ts
- lib/cli/command.ts
- lib/grpc/GrpcInitService.ts
- lib/grpc/getGrpcError.ts
- lib/service/InitService.ts
- lib/service/errors.ts
This displays better error messages when `xucli unlock`, `xucli create`, or `xucli restore` calls fail due to an xud node not existing or already existing. Instead of the generic `call is not supported by the current state of xud` message being printed, a more helpful message is printed informing the user of the state of xud and which call should be tried instead.
This also returns an error when a wallet that is already unlocked is attempted to be unlocked again.
Closes #1370.
> feat(cli): better messages when unlock/create fail

- lib/p2p/Peer.ts
This replaces the `opening`, `opened`, and `closed` flags on the `Peer` class with a single status enum. This simplifies the logic around the status of a peer and prevents the possibility that more than one flag is `true` at once, which would be an inconsistent state.
> refactor(p2p): use PeerStatus enum 

- lib/swaps/SwapClient.ts
This explicitly sets the status of a swap client to `Disconnected` after time runs out for the initial connection verification of a swap client. Since we wait to make a call until a swap client is "ready" - which means the grpc client `waitForReady` method finishes in the case of lnd - we won't experience a failed call right away in cases where lnd is simply offline. This means the status would remain at `Initialized` when `Disconnected` is more accurate - at that point we should treat lnd as if it is offline.
> refactor: set swap client disconnected on timeout

- lib/service/InitService.ts
This returns an `INVALID_ARGUMENT` error indicating the password was wrong when node key decryption fails during the `UnlockNode` call. Previously, an `UNKNOWN` error with a cryptic message was returned.
> feat(rpc): wrong password error for unlock

- lib/service/InitService.ts
- lib/swaps/SwapClientManager.ts
- lib/utils/seedutil.ts
- seedutil/SeedUtil.spec.ts
- seedutil/main.go
This changes adds the functionality to seedutil to generate a random 24 word mnemonic, which then replaces lnd for the purposes of generating the seed and mnemonic for a new xud node. This removes a dependency and allows xud to create a node without the help of lnd.
Closes #1253.
> feat: use seedutil to generate mnemonic

- lib/cli/placeorder.ts
- lib/service/Service.ts
- lib/utils/utils.ts
https://github.com/ExchangeUnion/xud/issues/1343. We decided to go with 10 ** 12 max precision. The number is easily configurable any time. Actually was quite a challenge to setup xud with lnd, btcd, ltcd and still shows some swapClient when executing order, but precision checks work fine.
> feat(cli): add price max precision checks for orders

- npm-shrinkwrap.json
This fixes known bugs and vulnerabilities in dependencies via the `npm audit fix` command.
`npm audit` still reports one issue with the sequelize package. However, fixing this requires making an upgrade with breaking changes and the vulnerability is not a cause for concern at this time as xud controls all queries made to the database and none are affected by the issue.
> chore: run 'npm audit fix'

- .gitignore
The simulation temp directory is still used but not ignored after #1357. This makes the folder ignored once again to prevent unintentionally committed files.
Note that this is a quick fix, however when examining the issue I was also thinking that the temp folder might not be necessary and can be removed altogether by simply using the dist folder. I'll open a separate PR for that to discuss that approach.
> chore: ignore simulation temp directory

- lib/constants/enums.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Peer.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
- test/integration/OrderBook.spec.ts
- test/integration/Swaps.spec.ts
- test/jest/Orderbook.spec.ts
Closes #1027.
This PR attempts to ensure that we have a direct channel with peers for raiden currencies before exchanging orders with that peer for any pairs involving that currency.
When a peer advertises a trading pair, either via initial handshake or on a node state update, we check that we have a direct channel for any raiden currencies before activating advertised pairs. If the trading pair is not activated, then we do not send or accept orders for that pair with the peer.
An existing timer with an interval of one minute is used for each peer to periodically check if inactive currencies and pairs can be activated by performing the same checks described above, including the direct channel check for raiden currencies.
It also reworks the error handling logic for swaps to identify a …
>  feat: disable raiden currencies w/out direct chan 

- package.json
This automatically generates new slate API documentation when a new version is tagged.
> chore: generate slate on new version

- test/jest/NodeKey.spec.ts
This is a followup to #1373 done for the same reasons.
> test: don't allocUnsafe for NodeKey tests

- lib/service/Service.ts
This is a minor performance improvement to the way the `ListOrders` rpc call concatenates own orders to the list of orders. This uses option 5 from the following benchmark, which is roughly twice as fast in the test than the existing approach which is option 1: http://jsben.ch/SeFSP
> perf(rpc/orderbook): listorders array concatenation

- lib/orderbook/OrderBook.ts
- lib/swaps/SwapClientManager.ts
- test/jest/Orderbook.spec.ts
This modifies the logic around verifying whether peer currencies are tradable to skip over any currencies for which our local swap client is currently disconnected. This prevents foreseeable failures when we try to send or receive with a swap client that is offline.
> refactor: only verify peer currencies if connected

- npm-shrinkwrap.json
- package.json
This updates to the latest typescript version. I am mainly interested in taking advantage of the new [Optional Chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) feature to write more concise code when making nullish checks.
> chore: update typescript

- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- test/jest/Orderbook.spec.ts
This commit attempts to better organize and clarify the `hasRouteToPeer` logic used to determine whether any possible route exists to pay a peer for a given currency before enabling trading pairs involving that currency for that peer.
Previously, lnd and raiden specific logic was located inside the SwapClientManager class. This has been refactored into the respective LndClient and RaidenClient classes.
The naming of the method is also changed from "hasRoute" to "canRoute" to indicate that it only tests whether such a route is possible, not whether one necessarily exists or is functional. Methods have been commented to better indicate what they do.
> refactor: organize/clarify canRouteToPeer logic

- docs/api.md
- lib/cli/commands/listorders.ts
- lib/cli/commands/orderbook.ts
- lib/constants/enums.ts
- lib/proto/xudrpc.swagger.json
- lib/proto/xudrpc_pb.d.ts
- lib/proto/xudrpc_pb.js
- lib/service/Service.ts
- proto/xudrpc.proto
- test/integration/Service.spec.ts
- test/jest/Service.spec.ts
This commit adds an optional `owner` parameter for the `listorders` command while removing `include_own_orders_parmeter` and replacing its functionality.
The default value for the new parameter is `Both`, other options are `Own` and `Peer`.
The commit also fixes a bug that caused a situation where sell orders were displayed instead of buy orders when the limit was set.
Closes #1323
> feat(rpc): add owner parameter for listorders

- lib/Config.ts
- lib/Xud.ts
- test/jest/Config.spec.ts
This adds assertion logic to the `Config` class to validate that any properties specified are of the expected type and, for certain properties, that the value is valid. This may prevent crashes or other unexpected behavior in xud due to invalid configuration, and will also log more instructive errors when a specified property is invalid.
Closes #1222.
> feat(config): property type and value checking

- lib/Xud.ts
- lib/backup/Backup.ts
- lib/lndclient/LndClient.ts
- lib/raidenclient/RaidenClient.ts
- lib/service/Service.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
- test/jest/RaidenClient.spec.ts
- test/jest/SwapClientManager.spec.ts
This commit makes several related changes to the `SwapClient` class, especially in regards to managing the status of a client, with the goal of making future changes and adding new `SwapClient` implementaions or statuses simpler. Key changes include:
- Removing the logic that would enable and disable timers such as the 
`reconnectionTimer` and `updateCapacityTimer` based on the status. Instead, the timers are always running, but only take action if the status matches a specified condition.
- Making all status change calls synchronous. When a particular status involves an asynchronous component, a method that wraps that status change with the asynchronous logic can be used instead (see next point).
- A new `setConnected` method that handles all steps related to marking a client as …
> refactor(swapclient): status and initialization

- .gitignore
- package.json
- test/simulation/Dockerfile
- test/simulation/docker-compose.yml
- test/simulation/docker-xud/Dockerfile
- test/simulation/xudtest/harness.go
Since working on the sim tests mostly involves refactoring test code, binding its deployment to docker with nvm/xud installation caused long docker build times. 
This PR decouples nvm/xud installation to a separate image, so that the test code container can consume it via volumes.
As previously, after changing test code one must run (from within the `test/simulation` dir):
```
$ docker-compose build test
```
> test(sim): decouple nvm/xud installation from the test files image

- test/simulation/docker-btcd/Dockerfile
Locking `btcd` version to v0.20.1-beta.
This is required since tests were broken due to to recent breaking changes in `btcd` rpc. `lnd` rpcclient dependency version was locked, while the test build version wasn't.
> test(sim): lock btcd version

- lib/lndclient/LndClient.ts
- lib/swaps/SwapClient.ts
This adds a status to the swap clients for after a client has been unlocked but before we have verified its connectivity. There can be additional initialization steps after a client has been unlocked and a possibility that it will encounter an error and shutdown, so we can not assume that the client will be available and set the status to `ConnectionVerified`. However, leaving the status as `WaitingUnlock` can be misleading or lead to additional unlock attempt that will fail. The new `Unlocked` status prevents further unlock attempts.
Closes #1411.
> feat(swapclient): add Locked status

- lib/raidenclient/RaidenClient.ts
- lib/swaps/SwapClientManager.ts
EDIT: Closes https://github.com/ExchangeUnion/xud/issues/1433
This adds a check of the swap client type value for each currency before associating it with a given swap client. Currently this only applies to Raiden, which previously was being automatically associated with any currency having a token address.
> refactor(swapclients): currency:client type check

- test/simulation/xud_test.go
- test/simulation/xudtest/node.go
Off-shoot from https://github.com/ExchangeUnion/xud/pull/1403#discussion_r383079401
Before allowing any RPC calls, verify that xud has finished initializing (not returning "xud is starting" error).
---
Part of https://github.com/ExchangeUnion/xud/issues/1356
> test(sim): wait until xud finish initializing

- test/simulation/harnessTest.go
- test/simulation/tests-instability.go
- test/simulation/tests-security.go
- test/simulation/xud_test.go
- test/simulation/xudtest/harness.go
Off-shoot from https://github.com/ExchangeUnion/xud/pull/1403#discussion_r383079446
Whenever a custom xud client is being downloaded/installed, adjust the ctx deadline so that time spent won't consume the test timeout duration.
Also added timeouts to channel openings (lesson from https://github.com/ExchangeUnion/xud/commit/b0ab4eb06bd0bf328675c20894167d3fcd47dbe5).
--- 
Part of #1356
> test(sim): adjust ctx deadline

- lib/lndclient/LndClient.ts
This is a workaround fix to prevent unexplained crashes in lnd after it is unlocked. It prevents lnd from checking if it is manually unlocked outside of xud. The downside is that if lnd is unlocked while xud is running, xud won't be aware.
This is related to #1415 and the issue with lnd crashing suddenly. I'm still not clear on why exactly this change seems to make the issue go away, but I no longer experience the issue with this. I suspect this is related to lnd using multiple services for unlock calls and for regular get info calls, they have plans to merge the two and I'll revisit this after that happens.
> fix(lnd): don't check for manual unlock

- package.json
This ensures we are testing with the latest xud code when running simulation tests before tagging a new version.
> chore: build sim test images on version

- lib/Config.ts
- test/jest/Config.spec.ts
> feat: different gRPC & HTTP port depending on active network

- test/simulation/lntest/node.go
- test/simulation/logs.sh
Export test run bitcoin/litecoin lnd instances logs under `test/simulation/temp/logs` (available for print via `npm run test:sim:logs`).
---
Part of https://github.com/ExchangeUnion/xud/issues/1356
> test(sim): export lnd instances logs

- .gitignore
Running dockerized simulation tests was creating a directory that was not being ignored by git. This change prevents that from being picked up by git.
> chore: ignore xud docker sim test directory

- lib/proto/xudrpc.swagger.json
- proto/README.md
This updates the version of `protoc-gen-swagger` to the version used by lnd. This will reduce conflicts when developing both lnd and xud in the same environment.
> chore: update protoc-gen-swagger

- parseGitCommit.js
This ignores changes to npm-shrinkwrap.json when determining the version being used of xud as this file may be altered unintentionally when using npm to install xud.
Related issue: #1449
> fix: ignore npm-shrinkwrap for commit hash

- lib/orderbook/TradingPair.ts
- test/unit/TradingPair.spec.ts
This fixes the matching engine order book priority to prefer own orders over peer orders when two orders have the same price. Previously, the engine would take whichever order was seen first. This is now only considered if two given orders at the same price point are either both own orders or both peer orders.
Fixes #1206.
> fix(orderbook): match own orders before peers'

- lib/lndclient/LndClient.ts
- test/jest/LndClient.spec.ts
- test/jest/__snapshots__/LndClient.spec.ts.snap
This removes the hard timeout placed on each attempt to connect to a peer's lnd node when attempting to open a channel with that peer. This timeout was causing xud to crash because it threw an error that was not being handled in the encapsulating catch block, which did not catch the error because it was thrown from a callback.
Rather than attempt to correct the asynchronous exception handling, this lifts the timeout limit set within xud and instead will wait on each connect attempt until it succeeds, times out, or fails according to the logic within lnd.
Fixes #1405.
> fix(lnd): relax unhandled openchannel timeout

- lib/lndclient/LndClient.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- test/jest/LndClient.spec.ts
- test/jest/SwapClientManager.spec.ts
- test/jest/__snapshots__/LndClient.spec.ts.snap
- test/jest/__snapshots__/SwapClientManager.spec.ts.snap
We currently attempt to connect to a peer's lnd node using their advertised listening addresses before opening a channel over lnd. If the connection attempt fails for any reason other than that we are already connected to the peer, then we fail the open channel attempt. However, this prematurely fails cases where a peer does not advertise listening addresses, such that connection attempts won't even be made and the `OpenChannel` call will fail right away, but is already connected to us. This could happen if a peer had previously connected to us.
Instead, we first attempt to connect to the peer's lnd node but then proceed to attempt to open a channel regardless of where we were able to connect or not. If we aren't connected to that peer, the lnd `OpenChannel` call will fail right away and …
> feat(lnd): attempt openchannel when connect fails

- lib/grpc/getGrpcError.ts
This fixes an internal bug where passing a string to the `getGrpcError` method - or possibly any object without `code`, `message`, or `name` properties - would result in a gRPC exception of `TypeError: Incorrectly typed arguments to startBatch` that is unhandled and crashes xud. This ensures that the gRPC errors returned by xud are well-formed.
> fix: string message grpc error handling

- lib/cli/command.ts
This fixes an issue where xucli could read an rpc host of `0.0.0.0` from the config file, indicating that xud is listening on all interfaces, and then attempt to connect to it using that ip address which fails. Instead, if the xucli tool detects that xud is configured to listen on all interfaces, it should default to attempting to connect on localhost.
This above behavior would fix the issue on xud1-simnet, which listens to 0.0.0.0 for rpc commands, so that we don't need to explicitly pass `localhost` as the rpc host to xucli commands.
This also adds some error handling to proceed in case loading the xud config fails, so that we go on to attempt the command anyhow.
> fix(cli): use localhost when rpc config 0.0.0.0 

- lib/db/seeds/simnet.ts
I already pointed the dns record for xud1.simnet.exchangeunion.com to the new ip
> chore: move to new xud1-simnet instance

- lib/p2p/Pool.ts
- test/jest/Pool.spec.ts
This adds the ipv6 version `::` of `0.0.0.0` to the self address detection of xud/xucli. Stumbled upon in https://github.com/ExchangeUnion/xud-docker/issues/419#issuecomment-616498254.
> fix: add `::` to selfaddress detection

- lib/cli/commands/deposit.ts
- lib/cli/commands/withdraw.ts
This resolves a merge issue between #1462 and #1481 where the `loadXudClient` method was made async in the latter but still used like a synchronous call in the former.
> refactor(cli): async load client deposit/withdraw

- test/simulation/tests-instability.go
Fixing the following test, from the instability test suite: `maker crashed after send payment with delayed settlement`.
This test relies on the taker delaying invoice settlement, while the maker crashes in the meanwhile. after it restarts, it is expected to not be able to recover the swap immediately, since the taker is still delaying the settlement.
But it looks like that the maker crash was triggered *after* `sendPayment` call returns - hence after the taker delay, and after he already settled the invoice. So when the maker xud restarts, it can immediately recover the swap, and the test fails due to an assertion which assume that the swap should not be able to be recovered immediately.
My only explanation to how this test previously passed is due to a race condition, where after the …
> test(sim): fix maker_crash_after_send instability test case

- lib/swaps/Swaps.ts
This writes out the full name of the `SwapFailureReason` to the logs when sending a `SwapFailurePacket` to a peer, like below:
`Sending NoRouteFound error to peer: {...`
Previously only the numerical enum value was written to the log.
Closes #1499.
> feat(swaps): log full SwapFailureReason name

- lib/swaps/SwapClient.ts
This ensures that we don't attempt to use an lnd client that was marked as `Misconfigured` because we were unable to load the tls.cert file for making rpc calls.
I also added logic to try and detect and prevent similar unintentional status transitions from happening in the future by defining allowed status transitions and preventing disallowed ones.
> fix(swapclient): don't initialize if misconfigured

- lib/db/seeds/simnet.ts
- I set up a new machine for xud1.simnet using the `connext-yy` simnet branch which gives us xud node key backup (& wallet seed & all other backups) so that we can easily restore on another machine and hopefully never have to change this seed entry again
- used new ubuntu 20.04 minimal with live patch setup to decrease maintenance & down time going forward. Plan to switch xud1.testnet and xud1 to such a setup too.
> chore: new xud1.simnet.exchangeunion.com

- bin/xud
- lib/Config.ts
- lib/Xud.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Pool.ts
- test/jest/SwapClientManager.spec.ts
This adds a `debug.testing` config option to be used when testing swaps for development purposes. When enabled, this option does three things.
* It adds peer orders back to the order book should they fail the swap.
* It disables reputation events besides the manual ban and unban events to prevent us from unintentionally banning peers due to too many failed
swaps.
* It always activates trading pairs for peers.
Closes #1496.
> feat: testing config option for develoment/tests

- lib/cli/commands/addpair.ts
- lib/cli/commands/openchannel.ts
This modifies the `addpair` command to use the trading pair ticker format such as LTC/BTC used in different commands, while keeping the ability to specify currencies separately.
Related issue #1521.
> feat(cli): use ticker format for addpair

- lib/p2p/Pool.ts
- lib/swaps/Swaps.ts
- test/simulation/actions.go
- test/simulation/tests-security.go
- test/simulation/xud_test.go
Fixing 2 different issues which caused the security test to fail:
1. **production code**: `swaps.handleSwapTimeout` to support a possibility that the swap peer isn’t connected. Previously it caused `xud` to panic and crash, hence was an attack vector.
2. **test code**: when asserting wallet/channels balance, take into consideration the amount that was pushed when the channels were opened.
Edit by karl:
Fixes https://github.com/ExchangeUnion/xud/issues/1455
> test(sim): fix security tests

- .travis.yml
- test/simulation/custom-xud.patch
- test/simulation/tests-instability.go
* Travis to run all the simulation test suites
* Fix merge conflicts in patch file
* Fix merge conflicts in test code
As since https://github.com/ExchangeUnion/xud/pull/1507, `test:sim:run` npm script will be running all the test suites, and not just the Integration test suite. 
This change is expected to extend the time length of the execution from ~1min to ~15min (not including the build, which takes ~7min).
Both `test:sim:build` and `test:sim:build:xud` npm scripts will be attempting to build `custom-xud` using the [patch file](https://github.com/ExchangeUnion/xud/blob/master/test/simulation/custom-xud.patch), hence changes to `/swaps/Swaps.ts` (like this [line](https://github.com/ExchangeUnion/xud/pull/1512/files#diff-207d104426c9b9c110cdd1c78f1fc6ecR208)) are expected to trigger an …
> test(sim): travis to run security/instability tests

- lib/cli/commands/addcurrency.ts
- lib/cli/commands/ban.ts
- lib/cli/commands/closechannel.ts
- lib/cli/commands/connect.ts
- lib/cli/commands/deposit.ts
- lib/cli/commands/discovernodes.ts
- lib/cli/commands/executeswap.ts
- lib/cli/commands/getbalance.ts
- lib/cli/commands/getnodeinfo.ts
- lib/cli/commands/listorders.ts
- lib/cli/commands/listtrades.ts
- lib/cli/commands/openchannel.ts
- lib/cli/commands/orderbook.ts
- lib/cli/commands/removecurrency.ts
- lib/cli/commands/removeorder.ts
- lib/cli/commands/removepair.ts
- lib/cli/commands/sell.ts
- lib/cli/commands/streamorders.ts
- lib/cli/commands/tradinglimits.ts
- lib/cli/commands/unban.ts
- lib/cli/commands/withdraw.ts
- lib/cli/placeorder.ts
This clarifies the usage and help output of each `xucli` command. Previously, all arguments were described as "Options" - even the positional arguments that were actually required. Specifying these required arguments as flags (for example `xucli ban --node_identifier CheeseMonkey`) would not work.
This commit attempts to properly use yargs' `positional` method wherever applicable for arguments with a fixed position in the command syntax. It also provides examples for the various ways commands can be used.
> feat(cli): clarify positional args & add examples

- lib/orderbook/OrderBook.ts
- test/simulation/actions.go
- test/simulation/tests-integration.go
- test/simulation/xudtest/node.go
Fixes #1547.
This informs peers when an order is matched or filled internally that the order is no longer valid or available for swapping. It includes a simulation test case that fails with the current code and passes with the included fix.
> fix: broadcast invalidation after internal match

- lib/swaps/Swaps.ts
- test/simulation/custom-xud.patch
This handles an edge case described below that causes xud to crash due to an assertion error when a payment fails as taker for a swap that has already completed, as described below.
1. Taker sends payment.
2. Maker sees payment, and sends payment to Taker.
3. Taker receives payment, and marks the swap as complete.
4. Maker fails to claim payment, so the attempt to send payment (from step 1) fails.
5. Error handling logic when Taker's payment attempt doesn't go through causes it to "fail" the deal.
6. But the swap actually succeeded - from Taker's perspective - in step 3, and Taker hits an assertion error trying to fail a deal that has completed.
Fixes #1569.
> fix(swaps): failed payment for completed swap

- lib/cli/commands/create.ts
This PR let `xucli create` command output fit the tty width. So it could be better integrated into other cli commands like in xud-docker.
```
You are creating an xud node key and underlying wallets. All will be secured by
a single password provided below.
Enter a password:
Re-enter password:
----------------------BEGIN XUD SEED---------------------
1. abandon     2. busy        3. canvas      4. join
5. mom         6. erode       7. always      8. lumber
9. sort       10. deer       11. coach      12. story
13. enhance    14. believe    15. fatal      16. oppose
17. home       18. chief      19. balcony    20. cave
21. bitter     22. maximum    23. frequent   24. want
-----------------------END XUD SEED----------------------
The following wallets were initialized: BTC, LTC, ERC20(ETH) …
```
> chore: remove extra newlines in create command to fit tty

- lib/swaps/Swaps.ts
This fixes the changes from #1571, which implemented the logic around completed swaps backwards.
Fixes #1569.
> fix(swaps): don't fail payment for complete swap

- test/simulation/logs.sh
This outputs only the xud logs for the `test:sim:logs` script, ignoring the lnd logs since they are too verbose and can result in too much text in the travis log output when the script is used. This also prints the filename at the top of each log file so they can be differentiated.
> chore: print xud logs only for simulation tests

- lib/Xud.ts
- lib/db/seeds/simnet.ts
ERC20 tokens are currently not deployed on simnet. This commit disables them temporarily.
> chore: disable simnet ERC20 pairs

- .travis.yml
- lib/Logger.ts
- lib/Xud.ts
- lib/connextclient/ConnextClient.ts
- lib/constants/enums.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Pool.ts
- lib/service/Service.ts
- lib/service/types.ts
- lib/swaps/SwapRecovery.ts
- lib/swaps/Swaps.ts
- test/jest/Orderbook.spec.ts
- test/jest/Service.spec.ts
- test/jest/SwapClientManager.spec.ts
- test/jest/SwapRecovery.spec.ts
- test/jest/integration/Swaps.spec.ts
- test/simulation/custom-xud.patch
- test/simulation/tests-security.go
This fixes a bug where we cancel the incoming invoice for swaps that time out as the maker. Although we would put the timed out swap into the SwapRecovery module, the swap cannot be recovered if the incoming invoice has been canceled, and if the taker later claims our payment it leaves us unable to claim the maker's payment.
The widely used `failDeal` method in Swaps was canceling incoming invoices which is what led to this unintended behavior. Now this logic is removed from `failDeal` - since it is only relevant when we attempt a payment as maker and it fails in a permanent fashion. Instead, we only cancel & remove the invoice for this specific case.
Fixes #1574.
> fix(swaps): don't cancel invoice on swap timeout

- lib/swaps/SwapRecovery.ts
- lib/swaps/Swaps.ts
- test/jest/SwapRecovery.spec.ts
This commit makes it so that any swap deals that fail as maker while sending payment will have the payment checked immediately upon being added to set of swaps tracked by the `SwapRecovery` module. This is instead of waiting for the 30 second timer to periodically retry tracked swaps
It also refactors the code around checking and rechecking swaps that may have a pending payment involved, and enhances logging output.
Closes #1598.
> feat(swaps): check payment immediately on recovery

- lib/p2p/NodeList.ts
- lib/p2p/Pool.ts
This fixes the logic used to resolve a node alias - when it is provided via the rpc layer, to a node pub key. Previously, we only checked if the alias matched connected peers and banned nodes, but not nodes we know of but aren't actively connected to.
This also refactors the `resolveAlias` logic to use a map of known aliases to node pub keys, such that we don't dynamically calculate the list of known aliases each time we must resolve an alias. Instead, aliases for all known nodes are determined up front.
Finally it refactors the nodelist to combine the `Map` of banned nodes with that of unbanned nodes, as the distinction was unnecessary. Instead a single map contains all known nodes.
>  fix: resolve alias for all known nodes 

- lib/connextclient/ConnextClient.ts
- lib/lndclient/LndClient.ts
- lib/swaps/Swaps.ts
This fixes a bug where failed swaps in the `SendingPayment` phase as maker would only be tracked by the `SwapRecovery` module if they failed due to a timeout error.
Closes #1606.
This bug was due to an oversight in the changes from #1600.
> fix(swaps): go to recovery for all failures

- lib/backup/Backup.ts
- lib/lndclient/LndClient.ts
- lib/service/Service.ts
- lib/service/errors.ts
- test/jest/__snapshots__/Service.spec.ts.snap
Just a few improvements/additions to the log output.
> Logging improvements

- lib/cli/commands/walletdeposit.ts
- lib/cli/commands/walletwithdraw.ts
This allows xucli to accept lower or mixed case currency tickers (such as `btc` or `Btc`) as well as upper case for the `walletdeposit` and `walletwithdraw` commands.
Closes #1626.
> fix(cli): accept lower case currencies

- lib/swaps/Swaps.ts
This refactors the final steps of the routine to accept a swap deal to make it so that we update the deal phase (and in turn, update the db) in parallel with sending the swap accepted packet to our peer. This can reduce the total time needed to accept a deal request and begin the swap.
> refactor(swaps): parallel swap accept packet send

- lib/connextclient/ConnextClient.ts
- lib/lndclient/LndClient.ts
This adds some more logging statements when a swapclient obtains the preimage for a hash from a payment that was sent successfully.
> feat: log preimage when revealed from sent payment

- lib/cli/commands/streamorders.ts
- lib/grpc/GrpcService.ts
This fixes the behavior of the `streamorders` cli command when xud is not ready for the call. Previously, if xud was locked it would stream an endless series of reconnecting messages and if xud was not running on the specified host/port at all it would simply hang. Now the command exits with an appropriate error message in such cases.
> fix(cli): streamorders handling xud not ready

- lib/backup/Backup.ts
- test/jest/Backup.spec.ts
This changes the behavior of the xud backup from backing up the xud db every time it changes (which is very often) to every 3 minutes, provided that it has changed in the preceding 3 minutes. Note that this approach still needs refinement to prevent corrupted backups as described in issue #1652.
Closes #1368.
> feat(backup): write xud db every 3 minutes max

- lib/grpc/GrpcService.ts
- lib/service/Service.ts
This is a refactoring followup to #1641 per the review here https://github.com/ExchangeUnion/xud/pull/1641#pullrequestreview-429758175.
> refactor(rpc): use rxjs for streaming calls

- .github/workflows/ci.yml
- .github/workflows/seedutil.yml
- .github/workflows/simtest.yml
- parseGitCommit.js
This PR adds build configurations GitHub actions. I split the GitHub action builds in three pieces:
- CI: compiling, linting and testing XUD
- Seedutil: compiling and testing the seedutil
- Simulation tests: building and running the simulation tests
The minor change in `parseGitCommit.js` was required because of the way GitHub actions clone the repository but it shouldn't affect any other builds at all.
> chore: add GitHub actions

- .github/workflows/simtest.yml
- lib/Logger.ts
- lib/constants/enums.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/NodeList.ts
- lib/p2p/Pool.ts
- lib/swaps/SwapRecovery.ts
- lib/swaps/Swaps.ts
- lib/swaps/types.ts
- test/integration/Swaps.spec.ts
- test/jest/SwapRecovery.spec.ts
- test/jest/Swaps.spec.ts
- test/jest/integration/Swaps.spec.ts
- test/simulation/custom-xud.patch
- test/simulation/docker-run.sh
- test/simulation/tests-security.go
- test/utils.ts
This creates a new phase for SwapDeals called `PreimageResolved` that represents the part after the maker has completed its payment to taker and resolved the preimage, but before it has settled its incoming payment using the preimage.
Swaps that have reached this phase are considered atomic - our outgoing payment has been settle and we've acquired the ability to settle our incoming payment - even if they're not complete. Therefore, the maker ends the swap timeout and gives the call to settle the incoming payment as long as it needs to complete while keeping the hold on the order to prevent it from being filled a second time.
Should a swap fail the `settleInvoice` call, it enters swap SwapRecovery where settling the payment will be attempted one more time but only after ensuring we are …
>  feat(swaps): new PreimageResolved swap phase 

- bin/xud-backup
We weren't using the `stop` method in Backup anywhere, so this PR calls it upon sigterm. This is related to #1697 although I haven't tested this with docker yet and I wasn't able to reproduce the original issue outside of docker.
> feat(backup): stop backup on sigterm

- lib/swaps/Swaps.ts
- test/jest/integration/Swaps.spec.ts
- test/simulation/custom-xud.patch
- test/utils.ts
This commit ensures that the taker cancels its incoming invoice when it fails while attempting to send payment.
Fixes #1695
> fix(swaps): cancel taker invoice on swap fail

- lib/connextclient/ConnextClient.ts
- lib/connextclient/errors.ts
- lib/lndclient/LndClient.ts
- lib/types.ts
This catches any errors within the `lookupPayment` swap client method and returns a "pending" status - since we weren't able to determine a resolution for the payment - rather than throwing an error. The error was not being handled in the Swaps module.
I believe this fixes #1701, however I wasn't able to reproduce the crash from that issue. @erkarl If you are able to reproduce could you try the same steps on this branch?
> fix(swaps): lookupPayment return Pending on error

- lib/p2p/NodeList.ts
- lib/p2p/P2PRepository.ts
- lib/p2p/Pool.ts
- test/jest/NodeList.spec.ts
This makes several improvements to the way xud behaves when a node is banned.
1. Only emit the `node.ban` event a single time when a node is banned, previously it was possible for this to fire multiple times when multiple negative reputation events occur at roughly the same time, polluting the logs and sending multiple disconnecting packets to the peer.
2. Log the name of the reputation event that triggered the ban.
3. Only send the recent reputation events to a peer when we ban them, rather than JSON stringifying the entire ReputationEventInstance db object which contains a lot of internal metadata that's irrelevent to
peers.
> feat(p2p): improved ban handling

- test/simulation/docker-run.sh
- test/simulation/logs.sh
- test/simulation/xudtest/node.go
Closing https://github.com/ExchangeUnion/xud/issues/1714.
The problem was with having a nil pointer dereference in a scenario where xud shutdown shortly after launch. This was fixed, but not the shutdown itself, which happens when trying to use an already-used port. I didn't manage to figure out what's causing this known instability, but I might try to use a different free-port generator technique if this happens too frequently. 
Also:
* Added log printing in case of failure, since we lost that after migrating to GitHub Actions. 
* Extended test timeout to 30m, so it will be longer than the test context timeout (for better error messages)
I managed to reproduce the problem after a few attempts, and this is how it looks now:
test
```
2020/07/08 06:12:46 xud: launching network...
2020/07/08 …
```
> fix(simtest): nil pointer deref bug

- lib/p2p/NodeList.ts
- lib/p2p/Pool.ts
- lib/service/Service.ts
- test/integration/Pool.spec.ts
- test/jest/NodeList.spec.ts
- test/jest/Service.spec.ts
- test/jest/__snapshots__/Service.spec.ts.snap
This ensures that we don't prevent ourselves from connecting to nodes that have alias conflicts with other known nodes. Instead, we only throw errors when we try to use a conflicted alias for rpc calls, since we cannot resolve the alias to a unique node.
Fixes #1687.
> fix(p2p): allow connections with alias conflict 

- lib/orderbook/TradingPair.ts
- lib/p2p/Pool.ts
- test/jest/Orderbook.spec.ts
This aims to reduce the verbosity of logging at the `debug` level by lowering the log level of order updates to `trace`. With market makers, there may be a stream of near-constant order updates and logging all of them will quickly flood the logs.
> feat: trace log level for order updates

- lib/utils/seedutil.ts
This uses `__dirname` - which gives the path to the current javascript file - in place of `./` - which gives the current working directory, to find the seedutil tool. Previously, the path to the seedutil tool would be wrong unless xud was launched directly from the main directory of the xud project.
> fix(seedutil): use correct path to seedutil tool

- lib/cli/placeorder.ts
- lib/orderbook/OrderBook.ts
- test/jest/Orderbook.spec.ts
This prints a message when placing orders via the cli when there are no more matches in the order book and a remainder of our order will be discarded. For limit orders, we print a message for the remainder to enter the order book in cases where we do not fully match right away. However there was no such message for market and IOC orders.
A similar message is also printed to the xud logs.
Closes #1656.
> feat(cli): print "no more matches" for place order

- lib/p2p/NodeList.ts
- lib/p2p/Pool.ts
- lib/p2p/errors.ts
- test/integration/Service.spec.ts
This uses a clearer error message when an rpc command specifies an alias that we have never encountered.
Closes #1670.
> feat: better "alias not found" message

- test/simulation/custom-xud.patch
- test/simulation/tests-instability.go
Closing https://github.com/ExchangeUnion/xud/issues/1712.
The previously existing `makerCrashedAfterSend` test wasn’t working well, as it was simulating a crash after swap already completed, due to an issue in the test code.
Instead, 4 tests were added:
* maker crash after send payment, before `PreimageResolved` phase; lnd
* maker crash after send payment, before `PreimageResolved` phase; connext
* maker crash after send payment, after `PreimageResolved` phase; lnd
* maker crash after send payment, after `PreimageResolved` phase; connext
As before, code structure is still messy, waiting for the upcoming refactoring.
> test(sim): PreimageResolved phase instability tests

- lib/cli/commands/tradehistory.ts
- lib/service/Service.ts
This adds an `--all` flag to the `xucli tradehistory` command to return all trades in the database with no limit.
Closes #1744.
> feat(cli): tradehistory --all

- lib/orderbook/OrderBook.ts
This change ensures that we do not add orders that failed a swap back to the order book if the peer which that order belongs to is no longer active/connected.
Closes #1622.
> fix: don't add back orders for inactive peer

- lib/Xud.ts
- lib/p2p/Pool.ts
- lib/swaps/Swaps.ts
- test/integration/Swaps.spec.ts
- test/jest/Orderbook.spec.ts
- test/jest/integration/Swaps.spec.ts
This prevents trading pairs from being deactivated due to failed swaps while in `debug.testing` mode. Previously we would automatically reactivate pairs in this mode, but this change ensures they don't get deactivated in the first place.
> feat: don't deactivate pairs with debug.testing

- lib/connextclient/ConnextClient.ts
Previously we would log "undefined" for every connext request that does not have a payload, this simply logs nothing for that case.
> feat(connext): better empty request logging

- lib/Config.ts
- lib/Xud.ts
- lib/orderbook/OrderBook.ts
- lib/p2p/Pool.ts
- lib/swaps/Swaps.ts
- sample-xud.conf
- test/jest/SwapClientManager.spec.ts
- test/simulation/xudtest/node.go
This replaces the `debug.testing` option with a `strict` option and makes the default behavior non-strict, equivalent to running xud with `debug.testing` before.
I went with `strict` as opposed to `production.strict` because it's less to type out that way and because I can't envision any other options that would go under a "production" category of config options.
It also allows severe reputation events to be registered even when not running in strict mode. Previously only manual reputation events were allowed when not in strict mode.
Closes #1757.
> feat(config): rename debug.testing to strict

- lib/lndclient/LndClient.ts
- test/jest/LndClient.spec.ts
This updates the `channelBalance` and `tradingLimits` calls to exclude the balance from inactive channels in the max allowed trading limits. It does this by going through every channel and ignoring inactive channels, rather than relying on the lnd `ChannelBalance` call, which includes inactive balances.
Closes #1636
> feat(lnd): no inactive balance in trading limits

- lib/lndclient/LndClient.ts
This fixes a log statement to not attempt to log a route when none exists, which would cause `undefined` to be logged.
> fix(swaps): don't log non-existent route

- .github/workflows/simtest.yml
- test/simulation/tests-integration.go
- test/simulation/tests-security.go
- test/simulation/xud_test.go
Simulation tests got broken after latest connext upgrade (https://github.com/ExchangeUnion/xud/pull/1767).
* connext node reachability check: `http://{nodeUrl}/config` returns 404, and I didn't manage to find a different valid endpoint, but I thought that checking for a connection would be good enough. 
* Balances changed a bit due to what seems as smaller fees. 
---
This PR also changes GitHub Actions `simtest` worflow to run on `[pull_request]` instead of `[push, pull_request]`, for reducing some CI overhead.
> test(sim): fix after latest connext upgrade 

- lib/p2p/Pool.ts
It's currently not clear from the logs whether new peers were created via inbound or outbound connections, this attempts to clear that up.
> feat(p2p): log whether socket is inbound/outbound

- lib/p2p/Peer.ts
Fixes #1773
This changes the peer socket error handling to use `on` instead of `once` when listening for `error` events to ensure that an unexpected second `error` event doesn't crash xud after the `once` handler stops listening. Instead we use `on` to listen to all error events and then manually remove all listeners from the socket after it's destroyed.
This also adds a callback to handle errors from the `socket.write` function when sending packets to peers. Previously we would not specify a callback at all, and errors would only get handled by the generic `socket.on('error')` event handler.
> fix(p2p): handle multiple socket errors

- lib/p2p/Peer.ts
This ensures we don't remove listeners from the peer TCP socket before the socket is destroyed. This prevents edge case errors where a socket emits an error in the split second before it is destroyed.
This is a follow-up to #1777 - it's something I encountered just now when running tests repeatedly locally and hitting an occasional unhandled error - but I was a few minutes too late with pushing a fix for it to the PR branch before it was merged.
> fix(p2p): remove socket listeners after destroy

- lib/service/Service.ts
This doesn't fail the entire `TradingLimits` call when a subset of the swap clients hit an error when checking their inbound/outbound capacity. If we get an error for one client, we will log it but still return limits from other clients.
Fixes #1766. This is a similar change/fix as what #1736 did for the `GetBalance` call.
> fix(rpc): don't block TradingLimits on failure

- package.json
- test/jest/integration/Swaps.spec.ts
This prevents unhandled rejections from occurring after the jest test cases have passed.
> test: fix unhandled rejections

- package.json
- test/simulation/docker-run.sh
The `temp/indra` folder for simulation tests was not being removed when running `npm run:sim:clean`. A stale indra folder could cause tests to fail and would need to be manually deleted. This PR deletes it automatically with the clean script.
> test: remove temp/indra folder on clean

- lib/connextclient/ConnextClient.ts
This calls the new `/request-collateral` endpoint after depositing funds to a connext channel. We do not await a response from `/request-collateral` but rather allow it to complete asynchronously after the `/deposit` call finishes.
Closes #1756.
> feat(connext): request collateral after deposit

- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/orderbook/errors.ts
- lib/orderbook/types.ts
- test/integration/OrderBook.spec.ts
- test/unit/TradingPair.spec.ts
This prevents xud from accepting and matching orders that would result in less than a full satoshi from being exchanged for both currencies involved in the swap. It does this three ways:
1. Preventing limit orders from being placed locally that do not meet the satoshi requirement.
2. Preventing peer orders from being added to the order book if they do not meet the satoshi requirement.
3. Preventing matches that do not meet the satoshi requirement, this is needed for handling locally placed market orders since they do not have a price assigned to them until they match with an order.
It is still possible for "dust" orders that cannot be traded to get stuck in the orderbook if they are partially removed or matched leaving a tiny fraction behind. A follow-up PR can automatically remove these. …
> feat(orderbook): prevent sub-satoshi order & match

- lib/p2p/Pool.ts
- test/integration/Pool.spec.ts
This fixes test flakiness with the mocha integration tests by ensuring that we wait for all follow-up actions to an opened peer to occur before continuing with test cases that may rely on those follow-up actions, such as database writes.
I'm going to restart the github actions tests several times to ensure we don't see the test failures this aims to fix.
> test: fix openPeer await

- lib/connextclient/ConnextClient.ts
- lib/connextclient/types.ts
- lib/http/HttpService.ts
This implements the new functionality to cancel incoming hash lock transfers in Connext, automatically freeing any HTLCs.
Closes #1730.
This is still a draft as it needs testing with the newest connext versions. I also believe this might require some modifications to the rest-api-client to ensure the `resolveCondition` call is happening properly, and it might make sense to create a separate endpoint for hashlock cancellations only such as `/hashlock-cancel`. I can open a PR for that the way I created `/withdraw`
> feat(connext): removeInvoice

- lib/swaps/Swaps.ts
- test/simulation/go.mod
- test/simulation/tests-security.go
This prevents the maker from failing a swap due to a swap failed packet received from the taker if the maker has already started sending its payment. This is because the taker may still claim the payment, and the maker needs to continue monitoring its outgoing payment until it is certain that the payment cannot be claimed.
Fixes #1749.
> fix(swaps): no remote fail when sending payment

- .github/workflows/simtest.yml
- test/simulation/connexttest/client.go
- test/simulation/docker-run.sh
- test/simulation/lntest/node.go
- test/simulation/shared/freeport.go
- test/simulation/xudtest/node.go
Introducing changes for improving simtests stability.
* Retry tests after failure (up to 3 times).
We discussed that this should be done only after unique failures, but after spending some time on that and trying different ways to capture stdout/stderr for comparison, my conclusion is that it won't be stable enough, especially if we'll do it from the bash script, and dealing with `docker-compose` output (which isn't very consistent).
Doing that from within the test code is better, but involves with some issues: 1) logging the output in real-time and capturing it at the same time isn't very straightforward, and 2) we still sometimes log data with some uniqueness, and trying to enforce the test code to not do that isn't worthwhile IMO.
So I ended up doing 3 re-runs after every failure, and …
> test(sim): auto retry, safer free ports

- lib/p2p/Pool.ts
- lib/swaps/Swaps.ts
- test/integration/Swaps.spec.ts
This ensures we only add severe and manual reputation events to peers when not running in strict mode by filtering both events that arise from the peer itself as well as those originating from other sources, such as failed swaps. Previously we only checked on events arising from the peer, which, for example, would include packet delays but not a failure to find routes.
Fixes #1802
> fix: restrict reputation events in non-strict mode

- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/orderbook/types.ts
- lib/p2p/Pool.ts
- lib/p2p/packets/types/OrderPacket.ts
- lib/proto/xudp2p_pb.d.ts
- lib/proto/xudp2p_pb.js
- lib/service/Service.ts
- proto/xudp2p.proto
- test/integration/OrderBook.spec.ts
- test/integration/Service.spec.ts
- test/jest/Orderbook.spec.ts
- test/simulation/tests-integration.go
- test/unit/Parser.spec.ts
This modifies the procedure for replacing an order in the order book. Previously, it would go like this:
1. Remove old order & send order invalidation to peers.
2. Place new order and wait for matching to complete (which may take
some time if it involves swap attempts).
3. Send new order to peers.
Now it goes:
1. Put the old order on hold, preventing further swaps/matching.
2. Place the new order and wait for matching to complete.
3. Remove the old order from the order book.
4. Send a single packet to peers with new order info and old order id.
5. Peers that receive this packet will remove the old order and add the new one sequentially.
By default, replaced orders will have the same local order id as the order they are replacing unless a different id is specified.
Closes #1805. Closes …
> feat(p2p): replace order in single packet

- lib/grpc/GrpcServer.ts
This logs each received RPC call with `trace` rather than `debug` as it can quickly flood logs in environments where there are many RPC calls happening. It also changes the log level for TLS certificate creation to `info` from `debug`, as this should only happen on starting a new environment and may be helpful information to end users.
Closes #1817.
> feat(rpc): log each call with trace not debug

- bin/xud
This replaces the obsolete `debug.testing` command line argument with the `strict` option that replaced it.
> fix: strict command arg

- lib/orderbook/OrderBook.ts
This fixes the functionality of non-strict mode to add peer orders back to the order book after they were matched but failed to swap. Previously we would only add back orders that were partially matched, by removing the remaining order from the order book, adding the partially matched quantity back to it, and then adding it back to the order book.
This also adds back orders that were fully matched and removed from the order book during matching after they fail to swap.
Closes #1816.
> fix(orderbook): add back fully matched orders

- lib/p2p/Pool.ts
- test/jest/Pool.spec.ts
This allows passing in a `minCompatibleVersion` value to `Pool` in the constructor, rather than having it be a constant read from package.json. This is helpful for tests to ensure that they don't break with new versions.
> refactor: minCompatible version param for Pool

- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/service/Service.ts
- test/integration/OrderBook.spec.ts
- test/integration/Service.spec.ts
- test/jest/Orderbook.spec.ts
- test/simulation/tests-instability.go
- test/simulation/tests-integration.go
- test/unit/TradingPair.spec.ts
This removes dust orders from the order book as they arise due to orders being partially removed or matched. Dust orders are defined as orders where either side of the trade has less than 100 satoshis of volume.
This logic exists in three places. During matching, we check whether the remainder of any maker order is beneath the dust limit. During partial order removal, we check whether the remainder is beneath the dust limit and, if so, remove the entire order instead. Lastly, any remaining order after matching is checked against the dust limit as well.
Closes #1798.
Follow-up to #1785.
> feat(orderbook): automatically remove dust orders

- lib/grpc/GrpcServer.ts
This PR generates 2048-bit TLS certificate instead of 1024-bit. Related to https://github.com/ExchangeUnion/xud-docker/pull/533#issuecomment-650117698
> feat: generate 2048-bit tls certs

- lib/grpc/GrpcServer.ts
This reverts commit b6bc1ad234aa6e6472e81c422d51b914c5f7b2f5.
Related: #1692 & #1840. I guess we'll have to be more careful and run simulation tests multiple times before changing anything regarding the TLS cert generation in the future.
> revert: feat: generate 2048-bit tls certs

- lib/orderbook/OrderBook.ts
This fixes an oversight where we would only reject peer orders where the price times quantity was below the dust limit, but not necessarily where the quantity itself was below the dust limit.
> fix(orderbook): reject all dust peer orders

- lib/orderbook/OrderBook.ts
- test/jest/Orderbook.spec.ts
This prevents matched orders from being added back to the order book after failing swaps if they were invalidated by the peer while the swap was being attempted.
Fixes #1838.
> feat(orderbook): don't add back invalidated orders

- lib/orderbook/OrderBook.ts
This fixes a bug whereby an order could be placed on hold without that hold ever being removed.
When replacing an order, we place the existing order on hold until the replacement order has finished matching, and only then do we remove the original order. However, the order was being placed on hold before the checks for sufficient balance to fill this order, and in case those checks failed the remainder of the `placeOrder` routine would be skipped including the part that removes the original order. In such a case, the original order would be put on hold indefinitely.
Instead, we place the existing order on hold immediately before we begin matching and after any checks on the validity of the new order are passed. If the checks fail, then the new order is rejected and the order it was …
> fix(orderbook): prevent stuck replace order holds

- lib/connextclient/ConnextClient.ts
- lib/swaps/SwapRecovery.ts
- lib/swaps/Swaps.ts
- test/simulation/custom-xud.patch
- test/simulation/tests-security.go
This monitors all swap client payments until their resolution without putting deals into `SwapRecovery`. Previously, if a call to send payment failed but the payment was still in pending status (as has been the case with Connext), then we would fail the swap deal and monitor the payment in `SwapRecovery`. This had several downsides, namely:
1. Since the deal is marked as having failed in the database, if xud restarts while payment monitoring is ongoing, it won't resume monitoring because it sees the swap as having failed in the database. We only recover swaps that were "active" at the time xud shut down. See #1799.
2. When a deal is failed, the maker order it attempted to swap re-enters the order book and is available to be matched again. However, since the payment for the original deal …
> feat(swaps): monitor pending payments before fail

- lib/cli/commands/closechannel.ts
This removes the no longer applicable `UNIMPLEMENTED` tag from the help output for the ETH example in `closechannel`.
Related issue #1852.
> docs(cli): remove unimplemented eth closechannel

- lib/connextclient/ConnextClient.ts
- lib/swaps/Swaps.ts
- test/simulation/custom-xud.patch
This prevents trying to settle an invoice more than once in case Connext sends us duplicate transfer received events. Previously, ConnextClient could emit the `htlcAccepted` event multiple times, resulting in one successful settleInvoice call and at least one failed call, which would then attempt to fail a completed deal and crash xud.
It also relaxes the assertion in `failDeal` to ensure we don't "fail" a deal that has already been completed. Previously such a case would crash xud, now it only prints an error message and does nothing. Although this shouldn't happen and indicates a flaw with xud code should it arise, it is not a critical error and does not risk funds or indicate that xud is inoperable.
Closes #1851.
> fix(connext): prevent duplicate htlcAccepted evts

- lib/orderbook/TradingPair.ts
This moves the logging statements for order holds being added or removed from debug level to trace, so as not to pollute the debug logs when frequently replacing orders as market makers often do.
> feat(logging): order holds on trace level

- lib/grpc/getGrpcError.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
This returns a clearer error message when the user attempts to replace an order that is on hold via rpc, which is not allowed.
> feat(orderbook): better replace order hold message

- lib/p2p/Peer.ts
This increases the maximum backoff to wait between reconnection attempts to a peer from 5 minutes to 1 hour. It also decreases the total amount of time that we will keep trying to reconnect to a peer before giving up from 7 days to 3 days.
EDIT by @kilrau : closes https://github.com/ExchangeUnion/xud/issues/1868
> feat(p2p): increase reconnection delay backoff

- lib/p2p/Pool.ts
This skips the log statement that logs when a peer sends us zero orders for a given trading pair, as this is more or less a non-event and is currently logged fairly frequently. It also lowers the level of logging when we do get orders from `verbose` to `debug` as it is a common and not particularly important event.
> feat(p2p): don't log empty order packets

- lib/cli/commands/closechannel.ts
- lib/cli/commands/walletdeposit.ts
1. removed redundant space in closechannel help `[node_identifier ]` -> `[node_identifier]`
2. fixed example in walletdeposit help `deposit BTC` -> `walletdeposit BTC`
> docs: fix cli help typos

- lib/service/Service.ts
- test/jest/Service.spec.ts
Fix of #1881, but need ACK from @kilrau that it is a bug :)
> fix: listorders limit displays first orders instead of last

- lib/orderbook/OrderBook.ts
- lib/swaps/SwapClientManager.ts
- test/jest/Orderbook.spec.ts
This ensures that, even when not running in strict mode, we only activate trading pairs with peers when we support both currencies of the pair locally. Previously we would activate every trading pair, like
BTC/LTC when we don't have a swap client for LTC, resulting in us requesting and receiving order updates for trading pairs that are irrelevent to us.
Related https://github.com/ExchangeUnion/xud/pull/1864#issuecomment-687140868:
> after adding new pair, the peer with new pair sends packet update to his peers. And after that these peers send GetOrders packet to this peer even if they have no this pair. It would be good to not ask orders if we have no this new pair.
> fix: don't activate unsupported pairs with peers

- lib/p2p/Peer.ts
attempts to resolve #1801 
This should be as simple as this change as per comments on the issue, could you please check @sangaman @raladev @kilrau
> fix: implemented showing all pairs instead of active ones for listpeers

- lib/connextclient/ConnextClient.ts
This changes the way we convert numbers to strings when building requests to send to the Connext client by using `toLocaleString` instead of `toString` to avoid representing large numbers with scientific notation.
This should help with issues we've faced using toknes that deal with larger quantities like DAI.
An example of how `toLocaleString` compares with `toString` as well as `bigint`:
```typescript
const x = 1725000000000000000000; // 1725 DAI in wei units
const bigX = 1725000000000000000000n;
console.log(x.toString());                                          // 1.725e+21
console.log(x.toLocaleString('fullwide', { useGrouping: false }));  // 1725000000000000000000
console.log(bigX.toString());                                       // 1725000000000000000000
const y = x + 1; …
```
> fix(connext): avoid scientific notation for amount

- lib/connextclient/ConnextClient.ts
- lib/connextclient/errors.ts
- lib/connextclient/types.ts
- lib/grpc/getGrpcError.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/swaps/SwapClient.ts
- test/jest/Connext.spec.ts
- test/jest/LndClient.spec.ts
- test/jest/Orderbook.spec.ts
- test/jest/__snapshots__/Orderbook.spec.ts.snap
This adds a check when a new order is receiving tokens via connext that ensures we have sufficient collateral from the connext node to fulfill the order. If not, we fail the order request and request the additional collateral necessary. This involves the following changes:
1. The Connext client now tracks the inbound node collateral for each currency and refreshes this value every time it queries for channel balances and every time a collateral request completes.
2. Before placing a new order that is receiving Connext tokens we check the inbound amount against the available collateral for that currency. In the case of market orders, we use the best available matching price in the order book to calculate inbound & outbound amounts.
3. If the collateral is insufficient, the order will be …
> feat(connext): request collateral for order amount

- lib/constants/enums.ts
- lib/grpc/GrpcService.ts
- lib/lndclient/LndClient.ts
- lib/swaps/Swaps.ts
- lib/swaps/errors.ts
attempts to resolve #1558 
This's a WIP (Work in Progress) PR, I'm currently having trouble with my local setup and @raladev is helping me with it, apart from that please let me know what else actually need to be done.
I suppose matched orders should return to the orderbook? @kilrau (I couldn't test this yet too)
@sangaman @raladev @kilrau
> fix: handling insufficient balance errors for swap clients

- lib/orderbook/OrderBook.ts
This fixes a bug whereby attempting to remove an order that is entirely on hold would throw an error due to trying to remove zero quantity from an order. Instead, if the entire order is on hold we skip removing any portion that is not on hold (since there is none) and wait for the hold to be lifted and remove any quantity.
> fix(orderbook): don't remove 0 quantity w/ hold

- lib/connextclient/ConnextClient.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- test/integration/OrderBook.spec.ts
- test/jest/Connext.spec.ts
- test/jest/Orderbook.spec.ts
- test/jest/SwapClientManager.spec.ts
- test/simulation/custom-xud.patch
- test/simulation/tests-instability.go
Closes #1896. Branched off of and dependant on #1885. WIP for now but this adds functionality to track reserved outbound & inbound balances each time an own order is added to or removed from the order book. Every time an order is added (and reserved amount increases) we check if the inbound capacity for that currency is sufficient to cover all orders. In Connext's case, if it's not sufficient then we make a collateral request to cover all orders +3% (unless we already have a pending collateral request waiting). We don't do anything on the lnd side since lnd can't dynamically increase its inbound capacity (although we could consider doing something like logging a message).
Related to #1584, which can use the reserved amounts that are being tracked in this PR and expose them over rpc.
Tests …
> feat(connext): lazy collateralization

- test/simulation/custom-xud.patch
- test/simulation/tests-instability.go
This restores the logic to request collateral in the custom xud builds used for instability tests by adding a one second wait after adding an order on the maker side (who then requests collateralization) but before placing a matching order on the taker side.
This appears to work around a brief, transient inability to send a connext payment to a node immediately after that node requests collateral.
Related PR #1916 - specifically the persistent simulation test failures that were eventually avoided by removing the collateral requests from custom-xud, which is being restored here.
> test(sim): connext collateralization with wait

- lib/lndclient/LndClient.ts
- lib/nodekey/NodeKey.ts
- lib/utils/seedutil.ts
- seedutil/SeedUtil.spec.ts
- seedutil/__snapshots__/SeedUtil.spec.ts.snap
- seedutil/main.go
This change uses separate mnemonics and seeds for each swap client that are unique to that client, rather than using a single seed and mnemonic across all clients. To accomplish this, a new method is added to the seedutil tool to derive a child mnemonic from a provided mnemonic. This is done by extracting the 16 bytes of entropy from the provided seed, concatenating the entropy with the name of the client (e.g. "LND-BTC") and then hashing the concatenation and taking 16 bytes from the resulting hash.
Closes #1576.
> feat: derive child seed for swap clients

- lib/cli/commands/addcurrency.ts
- lib/cli/commands/listorders.ts
This makes commands that have enumerated choices - such as `swap_client` which accepts either `Lnd` or `Connext` - case insensitive in regards to those choices. Previously a value of `lnd` in the example above would throw an error due to an invalid value.
> feat(cli): case insensitive choices

- lib/cli/commands/addcurrency.ts
resolves #1957
This was a bug coming from yargs, it was converting only number connext addresses into decimals, instead of letting them stay as hexadecimal so I made a small check and fixed it on coerce method.
This was an easy fix but trickier to find.
> fix:incorrect address conversion for connext currencies while adding currencies #1957

- lib/p2p/Pool.ts
This ensures that we don't attempt to reconnect to peers that have disconnected from us after we have started closing the p2p pool. This may help prevent scenarios where we unintentionally attempt to reconnect to peers after shutting down xud.
> fix(p2p): don't reconnect peers when pool closed

- lib/connextclient/ConnextClient.ts
This introduces better error handling for Connext when using `closeChannel` to remove funds from a Connext channel and specifying an amount to remove that is greater than the available balance.
> fix(connext): not enough balance for closechannel

- lib/connextclient/ConnextClient.ts
- lib/grpc/getGrpcError.ts
- lib/lndclient/LndClient.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/errors.ts
- lib/swaps/SwapClient.ts
- lib/swaps/SwapClientManager.ts
- lib/swaps/Swaps.ts
- lib/swaps/errors.ts
- lib/utils/UnitConverter.ts
- test/jest/Orderbook.spec.ts
- test/jest/SwapClientManager.spec.ts
- test/jest/UnitConverter.spec.ts
- test/jest/__snapshots__/Orderbook.spec.ts.snap
- test/jest/__snapshots__/SwapClientManager.spec.ts.snap
- test/unit/Swaps.spec.ts
This rejects orders that would put our total reserved balance over our total capacity for either the outbound or inbound currency. The sum of the inbound & outbound amounts for a newly placed order are added to the amounts reserved by open orders, and if either of these amounts exceed the corresponding capacity then the request to place the order is rejected.
An exception to this are inbound limits for Connext currencies, since we have the ability to dynamically request additional inbound collateral via our "lazy collateral" approach.
It is still possible for market orders to cause our open orders to exceed our capacity. This is a difficult problem to avoid entirely, as the price that market orders will execute at is unknown until the execution is complete. Even if we simulate the …
> feat: reserved capacity checks on PlaceOrder

- lib/cli/command.ts
resolves #1510 
This's the only thing that I could think of to prevent startup if `tls.cert `doesn't exist. But this spits command help followed by error message.
> fix: tls certificate check on startup (#1510)

- lib/lndclient/LndClient.ts
- lib/swaps/SwapClient.ts
This adds better error handling for when the test calls to verify lnd hold invoices are available fail due to connectivity reasons. Previously any error that occurred at this step would cause us to set lnd's status to `NoHoldInvoiceSupport` including connection issues. There was also a bug that caused us to try to set the status to connected even when a hold invoice status check failed.
This could result in the unusual behavior of status going to `Disconnected` upon a call failing due to the grpc `UNAVAILABLE` error status, then being set to `NoHoldInvoiceSupport` and then to `ConnectionVerified`. Now we only set `NoHoldInvoiceSupport` when the test calls fail for a reason other than `UNAVAILABLE`, and we only set the status to `ConnectionVerified` when the hold invoice calls succeed. …
> fix(lnd): handling hold invoice check errors

- lib/lndclient/LndClient.ts
This fixes a bug in the logic for calculating the inbound & outbound amount/capacity totals. We subtract the channel reserve amounts from the balances when determining how large a payment the channel could support, however we should not end up with a negative number.
> fix(lnd): don't calculate negative capacities

- bin/xud
This fixes a bug where the xud flag to set the network was incorrectly configured as `regnet` when it should be `regtest` to match what xud expects.
> fix: use regtest instead of regnet arg

- lib/p2p/Peer.ts
This fixes a regression introduced in #1994 that prevents enabling the stall timer for peers that checks whether peers are not responding to our packets in a reasonable timeframe and disconnecting those that are not. Without these checks, peers that have gone offline may remain in the list of connected peers, resulting in unexpected behavior and also preventing those peers from establishing new connections with us once they come back online.
Closes #2010.
I'm also hoping, but can't say for sure, that this fixes the test flakiness case that arose recently described here https://github.com/ExchangeUnion/xud/issues/1771#issuecomment-732289609.
> fix(p2p): fix stall timer checks

- lib/cli/commands/removeorder.ts
- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
This fixes a bug where fully removing an order via `RemoveOrder` would return the entire quantity of the order as the remaining quantity instead of zero. The problem was that when removing a quantity in full, we would simply delete it from our collection of orders but not modify its quantity, which is used (since #1986) for informational purposes on the rpc response.
It also tidies up the cli output a bit so as not to display zero amounts for holds or remaining quantity.
Fixes #2020
> fix(rpc): 0 remaining quantity on full remove 

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
This PR also includes some cleanup of duplicate lines in the changelog. Going forward, all release commits need to be in the format of `chore(release): vX.X.X` where the `X`s are numbers. The `v` before the number is required for the changelog tool we use to recognize the commit as a release commit, and there can be nothing after the numbers (such as a reference to a PR, as is automatically added when squash merging through GitHub).
> chore(release): v1.2.3

- npm-shrinkwrap.json
- package.json
This upgrades the `sqlite3` dependency to v5.0.0. 4.x versions have compatibility & build issues with the current node lts version 14.x, and this affects our xud-docker image builds.
Related issue: https://github.com/mapbox/node-sqlite3/issues/1314
> chore: upgrade sqlite3 to v5.0.0

- lib/db/DB.ts
- lib/db/migrations.ts
- lib/db/models/Node.ts
- lib/db/types.ts
- lib/p2p/NodeList.ts
- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
Closing https://github.com/ExchangeUnion/xud/issues/1970.
Few remarks:
* The `offline`/`dead` terminology wasn't used. Instead, `consecutiveConnFailure` counter was added to known nodes, and a ranking function which works in accordance with some thresholds. 
* Peer session can fail even if raw connection was successful (in handshake or validation). These failures suppose to affect the peer's reputation. The current ranking function doesn't consider that, but rather only the `consecutiveConnFailure` counter (it's possible to change that).
* `consecutiveConnFailure` cannot be correlated to time, so simpler thresholds (200 & 1500) than what was specified in https://github.com/ExchangeUnion/xud/issues/1970#issuecomment-733626904 were used.
* If no potential peers found in the first threshold …
> feat(p2p): Track peers' connection failures and rank accordingly

- lib/connextclient/ConnextClient.ts
resolves #2038 
- I'm still unable to access connext and it was still showing ready, so since it's not really much to do to fix this, I decided to take this one.
Can you please check?
> fix: connext status shouldn't show Ready unless connection verified

- lib/orderbook/OrderBook.ts
- lib/orderbook/TradingPair.ts
- lib/service/Service.ts
- test/unit/TradingPair.spec.ts
This fix ensures that we remove the mapping between local id and global order id for orders that have been fully matched or fully removed from the order book. Previously, internally matched orders would be removed from the trading pair queues but not from the global order book mapping between local order ids and global order ids.
Fixes #2045. Fixes #1556.
> fix(orderbook): remove local order id mappings

- lib/p2p/Peer.ts
- lib/p2p/Pool.ts
- test/integration/Pool.spec.ts
This makes several improvements to the way we close the p2p pool.
1. Make the peer `close` function synchronous by not awaiting the disconnection reason packet being sent. Previously we would wait and hold up the closing flow, which could introduce delays on stale or dead sockets. It also meant there was different behavior for closing peers with or without a disconnection reason. Instead we continue with all the steps for closing a peer and destroy the socket whenever the socket write attempt is complete.
2. Immediately destroy the socket if it is in `connecting` state, don't even attempt to send a disconnection reason packet since it
would not work anyway. 
3. Don't increment the connection failure attempt counter for peers when/after we close the pool and thus are canceling any ongoing …
> refactor(p2p): better pool closing

- lib/lndclient/LndClient.ts
This increases the default gRPC limit of 4 MB for a message response length to 200 MB to match the limit used by lnd. It also applies the lnd gRPC client options to all clients created for use with lnd.
Closes #2055.
Note that I used 200 MB instead of the 100 MB used in the code example in the related issue.
> fix(lnd): use 200 MB limit for grpc response

- lib/connextclient/ConnextClient.ts
This fixes a bug where in some cases the requested collateral amount was a decimal and resulted `this.unitConverter.amountToUnit` to fail.
> fix(connext): ensure collateral amount is integer

- lib/connextclient/ConnextClient.ts
- lib/connextclient/ethprovider.ts
This PR ensures that we pass in `rinkeby` as the network name when running in testnet mode. Otherwise `ethers.providers.JsonRpcProvider` would fail to initialize.
Can be tested using https://github.com/ExchangeUnion/xud-docker/pull/819
> fix(connext): fix ethprovider network name
